Vaccine Dashboard: setuptools.command.egg_info.InfoCommon Class Reference
setuptools.command.egg_info.InfoCommon Class Reference
Public Member Functions
def name (self)
def tagged_version (self)
def tags (self)
Static Public Attributes
tag_build = None
tag_date = None
Properties
vtags = property(tags)
Member Function Documentation
name()
def setuptools.command.egg_info.InfoCommon.name (self)
References pip._vendor.pkg_resources.safe_name().
tagged_version()
def setuptools.command.egg_info.InfoCommon.tagged_version (self)
References flask.cli.get_version(), pip._vendor.pkg_resources.safe_version(), and setuptools.command.egg_info.InfoCommon.vtags.
tags()
def setuptools.command.egg_info.InfoCommon.tags (self)
References setuptools.command.egg_info.InfoCommon.tag_build, and setuptools.command.egg_info.InfoCommon.tag_date.
Member Data Documentation
tag_build
setuptools.command.egg_info.InfoCommon.tag_build = None static
tag_date
setuptools.command.egg_info.InfoCommon.tag_date = None static
Property Documentation
vtags
setuptools.command.egg_info.InfoCommon.vtags = property(tags) static
The documentation for this class was generated from the following file:
back-end/flaskenv/Lib/site-packages/setuptools/command/egg_info.py