Vaccine Dashboard: attr._make Namespace Reference
attr._make Namespace Reference
Classes
class _Nothing
class _CacheHashWrapper
class _ClassBuilder
class Attribute
class _CountingAttr
class Factory
class _AndValidator
Functions
def attrib (default=NOTHING, validator=None, repr=True, cmp=None, hash=None, init=True, metadata=None, type=None, converter=None, factory=None, kw_only=False, eq=None, order=None, on_setattr=None)
def attrs (maybe_cls=None, these=None, repr_ns=None, repr=None, cmp=None, hash=None, init=None, slots=False, frozen=False, weakref_slot=True, str=False, auto_attribs=False, kw_only=False, cache_hash=False, auto_exc=False, eq=None, order=None, auto_detect=False, collect_by_mro=False, getstate_setstate=None, on_setattr=None, field_transformer=None)
def fields (cls)
def fields_dict (cls)
def validate (inst)
def make_class (name, attrs, bases=(object,), **attributes_arguments)
def and_ (*validators)
def pipe (*converters)
Variables
NOTHING = _Nothing()
def Attribute
def Factory = _add_hash(_add_eq(_add_repr(Factory, attrs=_f), attrs=_f), attrs=_f)
Function Documentation
and_()
def attr._make.and_ (* validators)
A validator that composes multiple validators into one.
When called on a value, it runs all wrapped validators.
:param callables validators: Arbitrary number of validators.
.. versionadded:: 17.1.0
attrib()
def attr._make.attrib (default = NOTHING, validator = None, repr = True, cmp = None, hash = None, init = True, metadata = None, type = None, converter = None, factory = None, kw_only = False, eq = None, order = None, on_setattr = None)
Create a new attribute on a class.
..  warning::
    Does *not* do anything unless the class is also decorated with
    `attr.s`!
:param default: A value that is used if an ``attrs``-generated ``__init__``
    is used and no value is passed while instantiating or the attribute is
    excluded using ``init=False``.
    If the value is an instance of `Factory`, its callable will be
    used to construct a new value (useful for mutable data types like lists
    or dicts).
    If a default is not set (or set manually to `attr.NOTHING`), a value
    *must* be supplied when instantiating; otherwise a `TypeError`
    will be raised.
    The default can also be set using decorator notation as shown below.
:type default: Any value
:param callable factory: Syntactic sugar for
    ``default=attr.Factory(factory)``.
:param validator: `callable` that is called by ``attrs``-generated
    ``__init__`` methods after the instance has been initialized.  They
    receive the initialized instance, the `Attribute`, and the
    passed value.
    The return value is *not* inspected so the validator has to throw an
    exception itself.
    If a `list` is passed, its items are treated as validators and must
    all pass.
    Validators can be globally disabled and re-enabled using
    `get_run_validators`.
    The validator can also be set using decorator notation as shown below.
:type validator: `callable` or a `list` of `callable`\\ s.
:param repr: Include this attribute in the generated ``__repr__``
    method. If ``True``, include the attribute; if ``False``, omit it. By
    default, the built-in ``repr()`` function is used. To override how the
    attribute value is formatted, pass a ``callable`` that takes a single
    value and returns a string. Note that the resulting string is used
    as-is, i.e. it will be used directly *instead* of calling ``repr()``
    (the default).
:type repr: a `bool` or a `callable` to use a custom function.
:param eq: If ``True`` (default), include this attribute in the
    generated ``__eq__`` and ``__ne__`` methods that check two instances
    for equality. To override how the attribute value is compared,
    pass a ``callable`` that takes a single value and returns the value
    to be compared.
:type eq: a `bool` or a `callable`.
:param order: If ``True`` (default), include this attributes in the
    generated ``__lt__``, ``__le__``, ``__gt__`` and ``__ge__`` methods.
    To override how the attribute value is ordered,
    pass a ``callable`` that takes a single value and returns the value
    to be ordered.
:type order: a `bool` or a `callable`.
:param cmp: Setting *cmp* is equivalent to setting *eq* and *order* to the
    same value. Must not be mixed with *eq* or *order*.
:type cmp: a `bool` or a `callable`.
:param Optional[bool] hash: Include this attribute in the generated
    ``__hash__`` method.  If ``None`` (default), mirror *eq*'s value.  This
    is the correct behavior according the Python spec.  Setting this value
    to anything else than ``None`` is *discouraged*.
:param bool init: Include this attribute in the generated ``__init__``
    method.  It is possible to set this to ``False`` and set a default
    value.  In that case this attributed is unconditionally initialized
    with the specified default value or factory.
:param callable converter: `callable` that is called by
    ``attrs``-generated ``__init__`` methods to convert attribute's value
    to the desired format.  It is given the passed-in value, and the
    returned value will be used as the new value of the attribute.  The
    value is converted before being passed to the validator, if any.
:param metadata: An arbitrary mapping, to be used by third-party
    components.  See `extending_metadata`.
:param type: The type of the attribute.  In Python 3.6 or greater, the
    preferred method to specify the type is using a variable annotation
    (see `PEP 526 <https://www.python.org/dev/peps/pep-0526/>`_).
    This argument is provided for backward compatibility.
    Regardless of the approach used, the type will be stored on
    ``Attribute.type``.
    Please note that ``attrs`` doesn't do anything with this metadata by
    itself. You can use it as part of your own code or for
    `static type checking <types>`.
:param kw_only: Make this attribute keyword-only (Python 3+)
    in the generated ``__init__`` (if ``init`` is ``False``, this
    parameter is ignored).
:param on_setattr: Allows to overwrite the *on_setattr* setting from
    `attr.s`. If left `None`, the *on_setattr* value from `attr.s` is used.
    Set to `attr.setters.NO_OP` to run **no** `setattr` hooks for this
    attribute -- regardless of the setting in `attr.s`.
:type on_setattr: `callable`, or a list of callables, or `None`, or
    `attr.setters.NO_OP`
.. versionadded:: 15.2.0 *convert*
.. versionadded:: 16.3.0 *metadata*
.. versionchanged:: 17.1.0 *validator* can be a ``list`` now.
.. versionchanged:: 17.1.0
   *hash* is ``None`` and therefore mirrors *eq* by default.
.. versionadded:: 17.3.0 *type*
.. deprecated:: 17.4.0 *convert*
.. versionadded:: 17.4.0 *converter* as a replacement for the deprecated
   *convert* to achieve consistency with other noun-based arguments.
.. versionadded:: 18.1.0
   ``factory=f`` is syntactic sugar for ``default=attr.Factory(f)``.
.. versionadded:: 18.2.0 *kw_only*
.. versionchanged:: 19.2.0 *convert* keyword argument removed.
.. versionchanged:: 19.2.0 *repr* also accepts a custom callable.
.. deprecated:: 19.2.0 *cmp* Removal on or after 2021-06-01.
.. versionadded:: 19.2.0 *eq* and *order*
.. versionadded:: 20.1.0 *on_setattr*
.. versionchanged:: 20.3.0 *kw_only* backported to Python 2
.. versionchanged:: 21.1.0
   *eq*, *order*, and *cmp* also accept a custom callable
.. versionchanged:: 21.1.0 *cmp* undeprecated
References attr._make.and_(), cffi.api.callable, cffi.ffiplatform.compile(), py._builtin.enumerate, pip._vendor.chardet.compat.iteritems, attr._make.pipe(), py._builtin.reversed, py._builtin.set, py._builtin.sorted, and pip._vendor.requests.compat.str.
attrs()
def attr._make.attrs (maybe_cls = None, these = None, repr_ns = None, repr = None, cmp = None, hash = None, init = None, slots = False, frozen = False, weakref_slot = True, str = False, auto_attribs = False, kw_only = False, cache_hash = False, auto_exc = False, eq = None, order = None, auto_detect = False, collect_by_mro = False, getstate_setstate = None, on_setattr = None, field_transformer = None)
A class decorator that adds `dunder
<https://wiki.python.org/moin/DunderAlias>`_\ -methods according to the
specified attributes using `attr.ib` or the *these* argument.
:param these: A dictionary of name to `attr.ib` mappings.  This is
    useful to avoid the definition of your attributes within the class body
    because you can't (e.g. if you want to add ``__repr__`` methods to
    Django models) or don't want to.
    If *these* is not ``None``, ``attrs`` will *not* search the class body
    for attributes and will *not* remove any attributes from it.
    If *these* is an ordered dict (`dict` on Python 3.6+,
    `collections.OrderedDict` otherwise), the order is deduced from
    the order of the attributes inside *these*.  Otherwise the order
    of the definition of the attributes is used.
:type these: `dict` of `str` to `attr.ib`
:param str repr_ns: When using nested classes, there's no way in Python 2
    to automatically detect that.  Therefore it's possible to set the
    namespace explicitly for a more meaningful ``repr`` output.
:param bool auto_detect: Instead of setting the *init*, *repr*, *eq*,
    *order*, and *hash* arguments explicitly, assume they are set to
    ``True`` **unless any** of the involved methods for one of the
    arguments is implemented in the *current* class (i.e. it is *not*
    inherited from some base class).
    So for example by implementing ``__eq__`` on a class yourself,
    ``attrs`` will deduce ``eq=False`` and will create *neither*
    ``__eq__`` *nor* ``__ne__`` (but Python classes come with a sensible
    ``__ne__`` by default, so it *should* be enough to only implement
    ``__eq__`` in most cases).
    .. warning::
       If you prevent ``attrs`` from creating the ordering methods for you
       (``order=False``, e.g. by implementing ``__le__``), it becomes
       *your* responsibility to make sure its ordering is sound. The best
       way is to use the `functools.total_ordering` decorator.
    Passing ``True`` or ``False`` to *init*, *repr*, *eq*, *order*,
    *cmp*, or *hash* overrides whatever *auto_detect* would determine.
    *auto_detect* requires Python 3. Setting it ``True`` on Python 2 raises
    a `PythonTooOldError`.
:param bool repr: Create a ``__repr__`` method with a human readable
    representation of ``attrs`` attributes..
:param bool str: Create a ``__str__`` method that is identical to
    ``__repr__``.  This is usually not necessary except for
    `Exception`\ s.
:param Optional[bool] eq: If ``True`` or ``None`` (default), add ``__eq__``
    and ``__ne__`` methods that check two instances for equality.
    They compare the instances as if they were tuples of their ``attrs``
    attributes if and only if the types of both classes are *identical*!
:param Optional[bool] order: If ``True``, add ``__lt__``, ``__le__``,
    ``__gt__``, and ``__ge__`` methods that behave like *eq* above and
    allow instances to be ordered. If ``None`` (default) mirror value of
    *eq*.
:param Optional[bool] cmp: Setting *cmp* is equivalent to setting *eq*
    and *order* to the same value. Must not be mixed with *eq* or *order*.
:param Optional[bool] hash: If ``None`` (default), the ``__hash__`` method
    is generated according how *eq* and *frozen* are set.
    1. If *both* are True, ``attrs`` will generate a ``__hash__`` for you.
    2. If *eq* is True and *frozen* is False, ``__hash__`` will be set to
       None, marking it unhashable (which it is).
    3. If *eq* is False, ``__hash__`` will be left untouched meaning the
       ``__hash__`` method of the base class will be used (if base class is
       ``object``, this means it will fall back to id-based hashing.).
    Although not recommended, you can decide for yourself and force
    ``attrs`` to create one (e.g. if the class is immutable even though you
    didn't freeze it programmatically) by passing ``True`` or not.  Both of
    these cases are rather special and should be used carefully.
    See our documentation on `hashing`, Python's documentation on
    `object.__hash__`, and the `GitHub issue that led to the default \
    behavior <https://github.com/python-attrs/attrs/issues/136>`_ for more
    details.
:param bool init: Create a ``__init__`` method that initializes the
    ``attrs`` attributes. Leading underscores are stripped for the argument
    name. If a ``__attrs_pre_init__`` method exists on the class, it will
    be called before the class is initialized. If a ``__attrs_post_init__``
    method exists on the class, it will be called after the class is fully
    initialized.
    If ``init`` is ``False``, an ``__attrs_init__`` method will be
    injected instead. This allows you to define a custom ``__init__``
    method that can do pre-init work such as ``super().__init__()``,
    and then call ``__attrs_init__()`` and ``__attrs_post_init__()``.
:param bool slots: Create a `slotted class <slotted classes>` that's more
    memory-efficient. Slotted classes are generally superior to the default
    dict classes, but have some gotchas you should know about, so we
    encourage you to read the `glossary entry <slotted classes>`.
:param bool frozen: Make instances immutable after initialization.  If
    someone attempts to modify a frozen instance,
    `attr.exceptions.FrozenInstanceError` is raised.
    .. note::
        1. This is achieved by installing a custom ``__setattr__`` method
           on your class, so you can't implement your own.
        2. True immutability is impossible in Python.
        3. This *does* have a minor a runtime performance `impact
           <how-frozen>` when initializing new instances.  In other words:
           ``__init__`` is slightly slower with ``frozen=True``.
        4. If a class is frozen, you cannot modify ``self`` in
           ``__attrs_post_init__`` or a self-written ``__init__``. You can
           circumvent that limitation by using
           ``object.__setattr__(self, "attribute_name", value)``.
        5. Subclasses of a frozen class are frozen too.
:param bool weakref_slot: Make instances weak-referenceable.  This has no
    effect unless ``slots`` is also enabled.
:param bool auto_attribs: If ``True``, collect `PEP 526`_-annotated
    attributes (Python 3.6 and later only) from the class body.
    In this case, you **must** annotate every field.  If ``attrs``
    encounters a field that is set to an `attr.ib` but lacks a type
    annotation, an `attr.exceptions.UnannotatedAttributeError` is
    raised.  Use ``field_name: typing.Any = attr.ib(...)`` if you don't
    want to set a type.
    If you assign a value to those attributes (e.g. ``x: int = 42``), that
    value becomes the default value like if it were passed using
    ``attr.ib(default=42)``.  Passing an instance of `Factory` also
    works as expected in most cases (see warning below).
    Attributes annotated as `typing.ClassVar`, and attributes that are
    neither annotated nor set to an `attr.ib` are **ignored**.
    .. warning::
       For features that use the attribute name to create decorators (e.g.
       `validators <validators>`), you still *must* assign `attr.ib` to
       them. Otherwise Python will either not find the name or try to use
       the default value to call e.g. ``validator`` on it.
       These errors can be quite confusing and probably the most common bug
       report on our bug tracker.
    .. _`PEP 526`: https://www.python.org/dev/peps/pep-0526/
:param bool kw_only: Make all attributes keyword-only (Python 3+)
    in the generated ``__init__`` (if ``init`` is ``False``, this
    parameter is ignored).
:param bool cache_hash: Ensure that the object's hash code is computed
    only once and stored on the object.  If this is set to ``True``,
    hashing must be either explicitly or implicitly enabled for this
    class.  If the hash code is cached, avoid any reassignments of
    fields involved in hash code computation or mutations of the objects
    those fields point to after object creation.  If such changes occur,
    the behavior of the object's hash code is undefined.
:param bool auto_exc: If the class subclasses `BaseException`
    (which implicitly includes any subclass of any exception), the
    following happens to behave like a well-behaved Python exceptions
    class:
    - the values for *eq*, *order*, and *hash* are ignored and the
      instances compare and hash by the instance's ids (N.B. ``attrs`` will
      *not* remove existing implementations of ``__hash__`` or the equality
      methods. It just won't add own ones.),
    - all attributes that are either passed into ``__init__`` or have a
      default value are additionally available as a tuple in the ``args``
      attribute,
    - the value of *str* is ignored leaving ``__str__`` to base classes.
:param bool collect_by_mro: Setting this to `True` fixes the way ``attrs``
   collects attributes from base classes.  The default behavior is
   incorrect in certain cases of multiple inheritance.  It should be on by
   default but is kept off for backward-compatability.
   See issue `#428 <https://github.com/python-attrs/attrs/issues/428>`_ for
   more details.
:param Optional[bool] getstate_setstate:
   .. note::
      This is usually only interesting for slotted classes and you should
      probably just set *auto_detect* to `True`.
   If `True`, ``__getstate__`` and
   ``__setstate__`` are generated and attached to the class. This is
   necessary for slotted classes to be pickleable. If left `None`, it's
   `True` by default for slotted classes and ``False`` for dict classes.
   If *auto_detect* is `True`, and *getstate_setstate* is left `None`,
   and **either** ``__getstate__`` or ``__setstate__`` is detected directly
   on the class (i.e. not inherited), it is set to `False` (this is usually
   what you want).
:param on_setattr: A callable that is run whenever the user attempts to set
    an attribute (either by assignment like ``i.x = 42`` or by using
    `setattr` like ``setattr(i, "x", 42)``). It receives the same arguments
    as validators: the instance, the attribute that is being modified, and
    the new value.
    If no exception is raised, the attribute is set to the return value of
    the callable.
    If a list of callables is passed, they're automatically wrapped in an
    `attr.setters.pipe`.
:param Optional[callable] field_transformer:
    A function that is called with the original class object and all
    fields right before ``attrs`` finalizes the class.  You can use
    this, e.g., to automatically add converters or validators to
    fields based on their types.  See `transform-fields` for more details.
.. versionadded:: 16.0.0 *slots*
.. versionadded:: 16.1.0 *frozen*
.. versionadded:: 16.3.0 *str*
.. versionadded:: 16.3.0 Support for ``__attrs_post_init__``.
.. versionchanged:: 17.1.0
   *hash* supports ``None`` as value which is also the default now.
.. versionadded:: 17.3.0 *auto_attribs*
.. versionchanged:: 18.1.0
   If *these* is passed, no attributes are deleted from the class body.
.. versionchanged:: 18.1.0 If *these* is ordered, the order is retained.
.. versionadded:: 18.2.0 *weakref_slot*
.. deprecated:: 18.2.0
   ``__lt__``, ``__le__``, ``__gt__``, and ``__ge__`` now raise a
   `DeprecationWarning` if the classes compared are subclasses of
   each other. ``__eq`` and ``__ne__`` never tried to compared subclasses
   to each other.
.. versionchanged:: 19.2.0
   ``__lt__``, ``__le__``, ``__gt__``, and ``__ge__`` now do not consider
   subclasses comparable anymore.
.. versionadded:: 18.2.0 *kw_only*
.. versionadded:: 18.2.0 *cache_hash*
.. versionadded:: 19.1.0 *auto_exc*
.. deprecated:: 19.2.0 *cmp* Removal on or after 2021-06-01.
.. versionadded:: 19.2.0 *eq* and *order*
.. versionadded:: 20.1.0 *auto_detect*
.. versionadded:: 20.1.0 *collect_by_mro*
.. versionadded:: 20.1.0 *getstate_setstate*
.. versionadded:: 20.1.0 *on_setattr*
.. versionadded:: 20.3.0 *field_transformer*
.. versionchanged:: 21.1.0
   ``init=False`` injects ``__attrs_init__``
.. versionchanged:: 21.1.0 Support for ``__attrs_pre_init__``
.. versionchanged:: 21.1.0 *cmp* undeprecated
References pip._vendor.distro.id(), py._builtin.set, and pip._vendor.requests.compat.str.
fields()
def attr._make.fields (cls)
Return the tuple of ``attrs`` attributes for a class.
The tuple also allows accessing the fields by their names (see below for
examples).
:param type cls: Class to introspect.
:raise TypeError: If *cls* is not a class.
:raise attr.exceptions.NotAnAttrsClassError: If *cls* is not an ``attrs``
    class.
:rtype: tuple (with name accessors) of `attr.Attribute`
..  versionchanged:: 16.2.0 Returned tuple allows accessing the fields
    by name.
References attr._compat.isclass().
fields_dict()
def attr._make.fields_dict (cls)
Return an ordered dictionary of ``attrs`` attributes for a class, whose
keys are the attribute names.
:param type cls: Class to introspect.
:raise TypeError: If *cls* is not a class.
:raise attr.exceptions.NotAnAttrsClassError: If *cls* is not an ``attrs``
    class.
:rtype: an ordered dict where keys are attribute names and values are
    `attr.Attribute`\\ s. This will be a `dict` if it's
    naturally ordered like on Python 3.6+ or an
    :class:`~collections.OrderedDict` otherwise.
.. versionadded:: 18.1.0
References attr._compat.isclass(), and attr._compat.ordered_dict.
make_class()
def attr._make.make_class (name, attrs, bases = (object,), ** attributes_arguments)
A quick way to create a new class called *name* with *attrs*.
:param str name: The name for the new class.
:param attrs: A list of names or a dictionary of mappings of names to
    attributes.
    If *attrs* is a list or an ordered dict (`dict` on Python 3.6+,
    `collections.OrderedDict` otherwise), the order is deduced from
    the order of the names or attributes inside *attrs*.  Otherwise the
    order of the definition of the attributes is used.
:type attrs: `list` or `dict`
:param tuple bases: Classes that the new class will subclass.
:param attributes_arguments: Passed unmodified to `attr.s`.
:return: A new class with *attrs*.
:rtype: type
.. versionadded:: 17.1.0 *bases*
.. versionchanged:: 18.1.0 If *attrs* is ordered, the order is retained.
References attr._make.attrib(), and attr._compat.new_class.
pipe()
def attr._make.pipe (* converters)
A converter that composes multiple converters into one.
When called on a value, it runs all wrapped converters, returning the
*last* value.
Type annotations will be inferred from the wrapped converters', if
they have any.
:param callables converters: Arbitrary number of converters.
.. versionadded:: 20.1.0
References dotenv.cli.list().
validate()
def attr._make.validate (inst)
Validate all attributes on *inst* that have a validator.
Leaves all exceptions through.
:param inst: Instance of a class with ``attrs`` attributes.
References attr._make.fields(), dotenv.cli.list(), and pip._vendor.html5lib.serializer.v.
Variable Documentation
Attribute
def attr._make.Attribute
Initial value:
 =  _add_hash(
     _add_eq(
         _add_repr(Attribute, attrs=_a),
         attrs=[a for a in _a if a.name != "inherited"],
     ),
     attrs=[a for a in _a if a.hash and a.name != "inherited"],
 )
Factory
def attr._make.Factory = _add_hash(_add_eq(_add_repr(Factory, attrs=_f), attrs=_f), attrs=_f)
NOTHING
attr._make.NOTHING = _Nothing()