Vaccine Dashboard: _pytest.recwarn Namespace Reference
_pytest.recwarn Namespace Reference
Classes
class WarningsRecorder
class WarningsChecker
Functions
Generator["WarningsRecorder", None, None] recwarn ()
"WarningsRecorder" deprecated_call (*Optional[Union[str, Pattern[str]]] match=...)
T deprecated_call (Callable[..., T] func, *Any args, **Any kwargs)
Union["WarningsRecorder", Any] deprecated_call (Optional[Callable[..., Any]] func=None, *Any args, **Any kwargs)
"WarningsChecker" warns (Optional[Union[Type[Warning], Tuple[Type[Warning],...]]] expected_warning, *Optional[Union[str, Pattern[str]]] match=...)
T warns (Optional[Union[Type[Warning], Tuple[Type[Warning],...]]] expected_warning, Callable[..., T] func, *Any args, **Any kwargs)
Union["WarningsChecker", Any] warns (Optional[Union[Type[Warning], Tuple[Type[Warning],...]]] expected_warning, *Any args, Optional[Union[str, Pattern[str]]] match=None, **Any kwargs)
Variables
T = TypeVar("T")
Detailed Description
Record warnings during test function execution.
Function Documentation
deprecated_call() [1/3]
"WarningsRecorder" _pytest.recwarn.deprecated_call (*Optional[Union[str, Pattern[str]]] match = ...)
deprecated_call() [2/3]
T _pytest.recwarn.deprecated_call (Callable[..., T] func, *Any args, **Any kwargs)
References _pytest.recwarn.deprecated_call().
deprecated_call() [3/3]
Union["WarningsRecorder", Any] _pytest.recwarn.deprecated_call (Optional[Callable[..., Any]] func = None, *Any args, **Any kwargs)
Assert that code produces a ``DeprecationWarning`` or ``PendingDeprecationWarning``.
This function can be used as a context manager::
    >>> import warnings
    >>> def api_call_v2():
    ...     warnings.warn('use v3 of this api', DeprecationWarning)
    ...     return 200
    >>> import pytest
    >>> with pytest.deprecated_call():
    ...    assert api_call_v2() == 200
It can also be used by passing a function and ``*args`` and ``**kwargs``,
in which case it will ensure calling ``func(*args, **kwargs)`` produces one of
the warnings types above. The return value is the return value of the function.
In the context manager form you may use the keyword argument ``match`` to assert
that the warning matches a text or regex.
The context manager produces a list of :class:`warnings.WarningMessage` objects,
one for each warning raised.
References _pytest.recwarn.deprecated_call(), and _pytest.recwarn.warns().
recwarn()
Generator["WarningsRecorder", None, None] _pytest.recwarn.recwarn ()
Return a :class:`WarningsRecorder` instance that records all warnings emitted by test functions.
See http://docs.python.org/library/warnings.html for information
on warning categories.
warns() [1/3]
Union["WarningsChecker", Any] _pytest.recwarn.warns (Optional[Union[Type[Warning], Tuple[Type[Warning], ...]]] expected_warning, *Any args, Optional[Union[str, Pattern[str]]] match = None, **Any kwargs)
Assert that code raises a particular class of warning.
Specifically, the parameter ``expected_warning`` can be a warning class or
sequence of warning classes, and the inside the ``with`` block must issue a warning of that class or
classes.
This helper produces a list of :class:`warnings.WarningMessage` objects,
one for each warning raised.
This function can be used as a context manager, or any of the other ways
:func:`pytest.raises` can be used::
    >>> import pytest
    >>> with pytest.warns(RuntimeWarning):
    ...    warnings.warn("my warning", RuntimeWarning)
In the context manager form you may use the keyword argument ``match`` to assert
that the warning matches a text or regex::
    >>> with pytest.warns(UserWarning, match='must be 0 or None'):
    ...     warnings.warn("value must be 0 or None", UserWarning)
    >>> with pytest.warns(UserWarning, match=r'must be \d+$'):
    ...     warnings.warn("value must be 42", UserWarning)
    >>> with pytest.warns(UserWarning, match=r'must be \d+$'):
    ...     warnings.warn("this is not here", UserWarning)
    Traceback (most recent call last):
      ...
    Failed: DID NOT WARN. No warnings of type ...UserWarning... was emitted...
References cffi.api.callable, py._builtin.sorted, dotenv.cli.type, and _pytest.recwarn.warns().
warns() [2/3]
"WarningsChecker" _pytest.recwarn.warns (Optional[Union[Type[Warning], Tuple[Type[Warning], ...]]] expected_warning, *Optional[Union[str, Pattern[str]]] match = ...)
warns() [3/3]
T _pytest.recwarn.warns (Optional[Union[Type[Warning], Tuple[Type[Warning], ...]]] expected_warning, Callable[..., T] func, *Any args, **Any kwargs)
References _pytest.recwarn.warns().
Variable Documentation
T
_pytest.recwarn.T = TypeVar("T")