Vaccine Dashboard: click._termui_impl Namespace Reference
click._termui_impl Namespace Reference
Classes
class ProgressBar
class Editor
Functions
None pager (t.Iterable[str] generator, t.Optional[bool] color=None)
int open_url (str url, bool wait=False, bool locate=False)
t.Iterator[int] raw_terminal ()
str getchar (bool echo)
Variables
V = t.TypeVar("V")
string BEFORE_BAR = "\r"
string AFTER_BAR = "\n"
Detailed Description
This module contains implementations for the termui module. To keep the
import time of Click down, some infrequently used functionality is
placed in this module and only imported as needed.
Function Documentation
getchar()
str click._termui_impl.getchar (bool echo)
References jwt.api_jws.decode, click._compat.get_best_encoding(), click._compat.isatty(), pip._vendor.distlib._backport.tarfile.open, and click._termui_impl.raw_terminal().
open_url()
int click._termui_impl.open_url (str url, bool wait = False, bool locate = False)
References pip._vendor.distlib._backport.tarfile.open, and pip._internal.utils.filesystem.replace.
pager()
None click._termui_impl.pager (t.Iterable[str] generator, t.Optional[bool] color = None)
Decide what method to use for paging through text.
References click._compat.get_best_encoding(), click._compat.isatty(), click._compat.open_stream(), and click._compat.strip_ansi().
raw_terminal()
t.Iterator[int] click._termui_impl.raw_terminal ()
Variable Documentation
AFTER_BAR
string click._termui_impl.AFTER_BAR = "\n"
BEFORE_BAR
string click._termui_impl.BEFORE_BAR = "\r"
V
click._termui_impl.V = t.TypeVar("V")