Vaccine Dashboard: py._code._assertionold Namespace Reference
py._code._assertionold Namespace Reference
Classes
class Failure
class View
class Interpretable
class Name
class Compare
class And
class Or
class UnaryArith
class BinaryArith
class CallFunc
class Getattr
class Assert
class Assign
class Discard
class Stmt
Functions
def enumsubclasses (cls)
def report_failure (e)
def check (s, frame=None)
def interpret (source, frame, should_fail=False)
API / Entry points.
def getmsg (excinfo)
def getfailure (e)
def run (s, frame=None)
def f ()
def g ()
def h (x)
Variables
passthroughex = py.builtin._sysex
list keepalive = []
int i = 4
Function Documentation
check()
def py._code._assertionold.check (s, frame = None)
References packaging.version.parse(), and py._code._assertionold.report_failure().
enumsubclasses()
def py._code._assertionold.enumsubclasses (cls)
f()
def py._code._assertionold.f ()
g()
def py._code._assertionold.g ()
getfailure()
def py._code._assertionold.getfailure (e)
References pip._vendor.requests.compat.str.
getmsg()
def py._code._assertionold.getmsg (excinfo)
References py._code._assertionold.interpret(), and pip._vendor.requests.compat.str.
h()
def py._code._assertionold.h (x)
References py._code._assertionold.check().
interpret()
def py._code._assertionold.interpret (source, frame, should_fail = False)
API / Entry points.
References py._code._assertionold.getfailure(), and packaging.version.parse().
report_failure()
def py._code._assertionold.report_failure (e)
run()
def py._code._assertionold.run (s, frame = None)
References packaging.version.parse(), and py._code._assertionold.report_failure().
Variable Documentation
i
int py._code._assertionold.i = 4
keepalive
list py._code._assertionold.keepalive = []
passthroughex
py._code._assertionold.passthroughex = py.builtin._sysex