Vaccine Dashboard: _pytest.config.findpaths Namespace Reference
_pytest.config.findpaths Namespace Reference
Functions
Optional[Dict[str, Union[str, List[str]]]] load_config_dict_from_file (Path filepath)
Tuple[ Optional[Path], Optional[Path], Dict[str, Union[str, List[str]]],] locate_config (Iterable[Path] args)
Path get_common_ancestor (Iterable[Path] paths)
List[Path] get_dirs_from_args (Iterable[str] args)
Tuple[Path, Optional[Path], Dict[str, Union[str, List[str]]]] determine_setup (Optional[str] inifile, Sequence[str] args, Optional[str] rootdir_cmd_arg=None, Optional["Config"] config=None)
Variables
string CFG_PYTEST_SECTION = "[pytest] section in {filename} files is no longer supported, change to [tool:pytest] instead."
Function Documentation
determine_setup()
Tuple[Path, Optional[Path], Dict[str, Union[str, List[str]]]] _pytest.config.findpaths.determine_setup (Optional[str] inifile, Sequence[str] args, Optional[str] rootdir_cmd_arg = None, Optional["Config"] config = None)
References _pytest.pathlib.absolutepath(), _pytest.config.findpaths.get_common_ancestor(), _pytest.config.findpaths.get_dirs_from_args(), _pytest.config.findpaths.load_config_dict_from_file(), _pytest.config.findpaths.locate_config(), and pip._vendor.requests.compat.str.
get_common_ancestor()
Path _pytest.config.findpaths.get_common_ancestor (Iterable[Path] paths)
References _pytest.pathlib.commonpath().
get_dirs_from_args()
List[Path] _pytest.config.findpaths.get_dirs_from_args (Iterable[str] args)
References _pytest.pathlib.absolutepath().
load_config_dict_from_file()
Optional[Dict[str, Union[str, List[str]]]] _pytest.config.findpaths.load_config_dict_from_file (Path filepath)
Load pytest configuration from the given file path, if supported.
Return None if the file does not contain valid pytest configuration.
References _pytest.outcomes.fail(), dotenv.cli.get(), toml.load, and pip._vendor.requests.compat.str.
locate_config()
Tuple[ Optional[Path], Optional[Path], Dict[str, Union[str, List[str]]], ] _pytest.config.findpaths.locate_config (Iterable[Path] args)
Search in the list of arguments for a valid ini-file for pytest,
and return a tuple of (rootdir, inifile, cfg-dict).
References _pytest.pathlib.absolutepath(), _pytest.config.findpaths.load_config_dict_from_file(), and pip._vendor.requests.compat.str.
Variable Documentation
CFG_PYTEST_SECTION
string _pytest.config.findpaths.CFG_PYTEST_SECTION = "[pytest] section in {filename} files is no longer supported, change to [tool:pytest] instead."