Vaccine Dashboard: pymysql.converters Namespace Reference
pymysql.converters Namespace Reference
Functions
def escape_item (val, charset, mapping=None)
def escape_dict (val, charset, mapping=None)
def escape_sequence (val, charset, mapping=None)
def escape_set (val, charset, mapping=None)
def escape_bool (value, mapping=None)
def escape_int (value, mapping=None)
def escape_float (value, mapping=None)
def escape_string (value, mapping=None)
def escape_bytes_prefixed (value, mapping=None)
def escape_bytes (value, mapping=None)
def escape_str (value, mapping=None)
def escape_None (value, mapping=None)
def escape_timedelta (obj, mapping=None)
def escape_time (obj, mapping=None)
def escape_datetime (obj, mapping=None)
def escape_date (obj, mapping=None)
def escape_struct_time (obj, mapping=None)
def Decimal2Literal (o, d)
def convert_datetime (obj)
def convert_timedelta (obj)
def convert_time (obj)
def convert_date (obj)
def through (x)
Variables
DATETIME_RE
TIMEDELTA_RE = re.compile(r"(-)?(\d{1,3}):(\d{1,2}):(\d{1,2})(?:.(\d{1,6}))?")
TIME_RE = re.compile(r"(\d{1,2}):(\d{1,2}):(\d{1,2})(?:.(\d{1,6}))?")
def convert_bit = through
dictionary encoders
dictionary decoders
dictionary conversions = encoders.copy()
def Thing2Literal = escape_str
Function Documentation
convert_date()
def pymysql.converters.convert_date (obj)
Returns a DATE column as a date object:
  >>> date_or_None('2007-02-26')
  datetime.date(2007, 2, 26)
Illegal values are returned as None:
  >>> date_or_None('2007-02-31') is None
  True
  >>> date_or_None('0000-00-00') is None
  True
convert_datetime()
def pymysql.converters.convert_datetime (obj)
Returns a DATETIME or TIMESTAMP column value as a datetime object:
  >>> datetime_or_None('2007-02-25 23:06:20')
  datetime.datetime(2007, 2, 25, 23, 6, 20)
  >>> datetime_or_None('2007-02-25T23:06:20')
  datetime.datetime(2007, 2, 25, 23, 6, 20)
Illegal values are returned as None:
  >>> datetime_or_None('2007-02-31T23:06:20') is None
  True
  >>> datetime_or_None('0000-00-00 00:00:00') is None
  True
References pymysql.converters.convert_date(), and dotenv.cli.list().
convert_time()
def pymysql.converters.convert_time (obj)
Returns a TIME column as a time object:
  >>> time_or_None('15:06:17')
  datetime.time(15, 6, 17)
Illegal values are returned as None:
  >>> time_or_None('-25:06:17') is None
  True
  >>> time_or_None('random crap') is None
  True
Note that MySQL always returns TIME columns as (+|-)HH:MM:SS, but
can accept values as (+|-)DD HH:MM:SS. The latter format will not
be parsed correctly by this function.
Also note that MySQL's TIME column corresponds more closely to
Python's timedelta and not time. However if you want TIME columns
to be treated as time-of-day and not a time offset, then you can
use set this function as the converter for FIELD_TYPE.TIME.
References dotenv.cli.list().
convert_timedelta()
def pymysql.converters.convert_timedelta (obj)
Returns a TIME column as a timedelta object:
  >>> timedelta_or_None('25:06:17')
  datetime.timedelta(1, 3977)
  >>> timedelta_or_None('-25:06:17')
  datetime.timedelta(-2, 83177)
Illegal values are returned as None:
  >>> timedelta_or_None('random crap') is None
  True
Note that MySQL always returns TIME columns as (+|-)HH:MM:SS, but
can accept values as (+|-)DD HH:MM:SS. The latter format will not
be parsed correctly by this function.
References dotenv.cli.list().
Decimal2Literal()
def pymysql.converters.Decimal2Literal (o, d)
escape_bool()
def pymysql.converters.escape_bool (value, mapping = None)
References pip._vendor.requests.compat.str.
escape_bytes()
def pymysql.converters.escape_bytes (value, mapping = None)
escape_bytes_prefixed()
def pymysql.converters.escape_bytes_prefixed (value, mapping = None)
escape_date()
def pymysql.converters.escape_date (obj, mapping = None)
escape_datetime()
def pymysql.converters.escape_datetime (obj, mapping = None)
escape_dict()
def pymysql.converters.escape_dict (val, charset, mapping = None)
References pymysql.converters.escape_item().
escape_float()
def pymysql.converters.escape_float (value, mapping = None)
References pip._vendor.pyparsing.range.
escape_int()
def pymysql.converters.escape_int (value, mapping = None)
References pip._vendor.requests.compat.str.
escape_item()
def pymysql.converters.escape_item (val, charset, mapping = None)
References dotenv.cli.type.
escape_None()
def pymysql.converters.escape_None (value, mapping = None)
escape_sequence()
def pymysql.converters.escape_sequence (val, charset, mapping = None)
References pymysql.converters.escape_item().
escape_set()
def pymysql.converters.escape_set (val, charset, mapping = None)
References pymysql.converters.escape_item().
escape_str()
def pymysql.converters.escape_str (value, mapping = None)
References pymysql.converters.escape_string(), and pip._vendor.requests.compat.str.
escape_string()
def pymysql.converters.escape_string (value, mapping = None)
escapes *value* without adding quote.
Value should be unicode
escape_struct_time()
def pymysql.converters.escape_struct_time (obj, mapping = None)
References pymysql.converters.escape_datetime().
escape_time()
def pymysql.converters.escape_time (obj, mapping = None)
escape_timedelta()
def pymysql.converters.escape_timedelta (obj, mapping = None)
through()
def pymysql.converters.through (x)
Variable Documentation
conversions
dictionary pymysql.converters.conversions = encoders.copy()
convert_bit
def pymysql.converters.convert_bit = through
DATETIME_RE
pymysql.converters.DATETIME_RE
Initial value:
 =  re.compile(
     r"(\d{1,4})-(\d{1,2})-(\d{1,2})[T ](\d{1,2}):(\d{1,2}):(\d{1,2})(?:.(\d{1,6}))?"
 )
decoders
dictionary pymysql.converters.decoders
Initial value:
 =  {
     FIELD_TYPE.BIT: convert_bit,
     FIELD_TYPE.TINY: int,
     FIELD_TYPE.SHORT: int,
     FIELD_TYPE.LONG: int,
     FIELD_TYPE.FLOAT: float,
     FIELD_TYPE.DOUBLE: float,
     FIELD_TYPE.LONGLONG: int,
     FIELD_TYPE.INT24: int,
     FIELD_TYPE.YEAR: int,
     FIELD_TYPE.TIMESTAMP: convert_datetime,
     FIELD_TYPE.DATETIME: convert_datetime,
     FIELD_TYPE.TIME: convert_timedelta,
     FIELD_TYPE.DATE: convert_date,
     FIELD_TYPE.BLOB: through,
     FIELD_TYPE.TINY_BLOB: through,
     FIELD_TYPE.MEDIUM_BLOB: through,
     FIELD_TYPE.LONG_BLOB: through,
     FIELD_TYPE.STRING: through,
     FIELD_TYPE.VAR_STRING: through,
     FIELD_TYPE.VARCHAR: through,
     FIELD_TYPE.DECIMAL: Decimal,
     FIELD_TYPE.NEWDECIMAL: Decimal,
 }
encoders
dictionary pymysql.converters.encoders
Initial value:
 =  {
     bool: escape_bool,
     int: escape_int,
     float: escape_float,
     str: escape_str,
     bytes: escape_bytes,
     tuple: escape_sequence,
     list: escape_sequence,
     set: escape_sequence,
     frozenset: escape_sequence,
     dict: escape_dict,
     type(None): escape_None,
     datetime.date: escape_date,
     datetime.datetime: escape_datetime,
     datetime.timedelta: escape_timedelta,
     datetime.time: escape_time,
     time.struct_time: escape_struct_time,
     Decimal: Decimal2Literal,
 }
Thing2Literal
def pymysql.converters.Thing2Literal = escape_str
TIME_RE
pymysql.converters.TIME_RE = re.compile(r"(\d{1,2}):(\d{1,2}):(\d{1,2})(?:.(\d{1,6}))?")
TIMEDELTA_RE
pymysql.converters.TIMEDELTA_RE = re.compile(r"(-)?(\d{1,3}):(\d{1,2}):(\d{1,2})(?:.(\d{1,6}))?")