Vaccine Dashboard: _pytest.main Namespace Reference
_pytest.main Namespace Reference
Classes
class FSHookProxy
class Interrupted
class Failed
class _bestrelpath_cache
class Session
Functions
None pytest_addoption (Parser parser)
str validate_basetemp (str path)
Union[int, ExitCode] wrap_session (Config config, Callable[[Config, "Session"], Optional[Union[int, ExitCode]]] doit)
Union[int, ExitCode] pytest_cmdline_main (Config config)
None pytest_collection ("Session" session)
bool pytest_runtestloop ("Session" session)
Optional[bool] pytest_ignore_collect (py.path.local path, Config config)
None pytest_collection_modifyitems (List[nodes.Item] items, Config config)
str search_pypath (str module_name)
Tuple[py.path.local, List[str]] resolve_collection_argument (Path invocation_path, str arg, *bool as_pypath=False)
Detailed Description
Core implementation of the testing process: init, session, runtest loop.
Function Documentation
pytest_addoption()
None _pytest.main.pytest_addoption (Parser parser)
pytest_cmdline_main()
Union[int, ExitCode] _pytest.main.pytest_cmdline_main (Config config)
References _pytest.main.wrap_session().
pytest_collection()
None _pytest.main.pytest_collection ("Session" session)
pytest_collection_modifyitems()
None _pytest.main.pytest_collection_modifyitems (List[nodes.Item] items, Config config)
pytest_ignore_collect()
Optional[bool] _pytest.main.pytest_ignore_collect (py.path.local path, Config config)
References py._builtin.any, and pip._vendor.requests.compat.str.
pytest_runtestloop()
bool _pytest.main.pytest_runtestloop ("Session" session)
References py._builtin.any, and py._builtin.enumerate.
resolve_collection_argument()
Tuple[py.path.local, List[str]] _pytest.main.resolve_collection_argument (Path invocation_path, str arg, *bool as_pypath = False)
Parse path arguments optionally containing selection parts and return (fspath, names).
Command-line arguments can point to files and/or directories, and optionally contain
parts for specific tests selection, for example:
    "pkg/tests/test_foo.py::TestClass::test_foo"
This function ensures the path exists, and returns a tuple:
    (py.path.path("/full/path/to/pkg/tests/test_foo.py"), ["TestClass", "test_foo"])
When as_pypath is True, expects that the command-line argument actually contains
module paths instead of file-system paths:
    "pkg.tests.test_foo::TestClass::test_foo"
In which case we search sys.path for a matching module, and then return the *path* to the
found module.
If the path doesn't exist, raise UsageError.
If the path is a directory and selection parts are present, raise UsageError.
References _pytest.pathlib.absolutepath(), _pytest.main.search_pypath(), and pip._vendor.requests.compat.str.
search_pypath()
str _pytest.main.search_pypath (str module_name)
Search sys.path for the given a dotted module name, and return its file system path.
validate_basetemp()
str _pytest.main.validate_basetemp (str path)
References _pytest.monkeypatch.resolve().
wrap_session()
Union[int, ExitCode] _pytest.main.wrap_session (Config config, Callable[[Config, "Session"], Optional[Union[int, ExitCode]]] doit)
Skeleton command line program.
References dotenv.cli.type.