Vaccine Dashboard: _pytest.pastebin Namespace Reference
_pytest.pastebin Namespace Reference
Functions
None pytest_addoption (Parser parser)
None pytest_configure (Config config)
None pytest_unconfigure (Config config)
str create_new_paste (Union[str, bytes] contents)
None pytest_terminal_summary (TerminalReporter terminalreporter)
Variables
pastebinfile_key = StoreKey[IO[bytes]]()
Detailed Description
Submit failure or test session information to a pastebin service.
Function Documentation
create_new_paste()
str _pytest.pastebin.create_new_paste (Union[str, bytes] contents)
Create a new paste using the bpaste.net service.
:contents: Paste contents string.
:returns: URL to the pasted contents, or an error message.
References jwt.api_jws.decode, and jwt.api_jws.encode.
pytest_addoption()
None _pytest.pastebin.pytest_addoption (Parser parser)
pytest_configure()
None _pytest.pastebin.pytest_configure (Config config)
pytest_terminal_summary()
None _pytest.pastebin.pytest_terminal_summary (TerminalReporter terminalreporter)
References _pytest.pastebin.create_new_paste(), _pytest.config.create_terminal_writer(), and pip._vendor.six.StringIO.
pytest_unconfigure()
None _pytest.pastebin.pytest_unconfigure (Config config)
References _pytest.pastebin.create_new_paste().
Variable Documentation
pastebinfile_key
_pytest.pastebin.pastebinfile_key = StoreKey[IO[bytes]]()