Vaccine Dashboard: dotenv.main Namespace Reference
dotenv.main Namespace Reference
Classes
class DotEnv
Functions
Iterator[Binding] with_warn_for_invalid_lines (Iterator[Binding] mappings)
Optional[str] get_key (Union[str, _PathLike] dotenv_path, str key_to_get)
Iterator[Tuple[IO[str], IO[str]]] rewrite (Union[str, _PathLike] path)
Tuple[Optional[bool], str, str] set_key (Union[str, _PathLike] dotenv_path, str key_to_set, str value_to_set, str quote_mode="always", bool export=False)
Tuple[Optional[bool], str] unset_key (Union[str, _PathLike] dotenv_path, str key_to_unset, str quote_mode="always")
Mapping[str, Optional[str]] resolve_variables (Iterable[Tuple[str, Optional[str]]] values, bool override)
str find_dotenv (str filename='.env', bool raise_error_if_not_found=False, bool usecwd=False)
bool load_dotenv (Union[str, _PathLike, None] dotenv_path=None, Optional[IO[str]] stream=None, bool verbose=False, bool override=False, bool interpolate=True, Optional[str] encoding="utf-8")
Dict[str, Optional[str]] dotenv_values (Union[str, _PathLike, None] dotenv_path=None, Optional[IO[str]] stream=None, bool verbose=False, bool interpolate=True, Optional[str] encoding="utf-8")
Variables
logger = logging.getLogger(__name__)
Function Documentation
dotenv_values()
Dict[str, Optional[str]] dotenv.main.dotenv_values (Union[str, _PathLike, None] dotenv_path = None, Optional[IO[str]] stream = None, bool verbose = False, bool interpolate = True, Optional[str] encoding = "utf-8")
Parse a .env file and return its content as a dict.
- *dotenv_path*: absolute or relative path to .env file.
- *stream*: `StringIO` object with .env content, used if `dotenv_path` is `None`.
- *verbose*: whether to output a warning the .env file is missing. Defaults to
  `False`.
  in `.env` file.  Defaults to `False`.
- *encoding*: encoding to be used to read the file.
If both `dotenv_path` and `stream`, `find_dotenv()` is used to find the .env file.
References dotenv.main.find_dotenv().
find_dotenv()
str dotenv.main.find_dotenv (str filename = '.env', bool raise_error_if_not_found = False, bool usecwd = False)
Search in increasingly higher folders for the given file
Returns path to the file if found, or an empty string otherwise
get_key()
Optional[str] dotenv.main.get_key (Union[str, _PathLike] dotenv_path, str key_to_get)
Gets the value of a given key from the given .env
If the .env path given doesn't exist, fails
References dotenv.cli.get().
load_dotenv()
bool dotenv.main.load_dotenv (Union[str, _PathLike, None] dotenv_path = None, Optional[IO[str]] stream = None, bool verbose = False, bool override = False, bool interpolate = True, Optional[str] encoding = "utf-8")
Parse a .env file and then load all the variables found as environment variables.
- *dotenv_path*: absolute or relative path to .env file.
- *stream*: Text stream (such as `io.StringIO`) with .env content, used if
  `dotenv_path` is `None`.
- *verbose*: whether to output a warning the .env file is missing. Defaults to
  `False`.
- *override*: whether to override the system environment variables with the variables
  in `.env` file.  Defaults to `False`.
- *encoding*: encoding to be used to read the file.
If both `dotenv_path` and `stream`, `find_dotenv()` is used to find the .env file.
References dotenv.main.find_dotenv().
resolve_variables()
Mapping[str, Optional[str]] dotenv.main.resolve_variables (Iterable[Tuple[str, Optional[str]]] values, bool override)
References dotenv.variables.parse_variables().
rewrite()
Iterator[Tuple[IO[str], IO[str]]] dotenv.main.rewrite (Union[str, _PathLike] path)
set_key()
Tuple[Optional[bool], str, str] dotenv.main.set_key (Union[str, _PathLike] dotenv_path, str key_to_set, str value_to_set, str quote_mode = "always", bool export = False)
Adds or Updates a key/value to the given .env
If the .env path given doesn't exist, fails instead of risking creating
an orphan .env somewhere in the filesystem
References dotenv.parser.parse_stream(), dotenv.main.rewrite(), and dotenv.main.with_warn_for_invalid_lines().
unset_key()
Tuple[Optional[bool], str] dotenv.main.unset_key (Union[str, _PathLike] dotenv_path, str key_to_unset, str quote_mode = "always")
Removes a given key from the given .env
If the .env path given doesn't exist, fails
If the given key doesn't exist in the .env, fails
References dotenv.parser.parse_stream(), dotenv.main.rewrite(), and dotenv.main.with_warn_for_invalid_lines().
with_warn_for_invalid_lines()
Iterator[Binding] dotenv.main.with_warn_for_invalid_lines (Iterator[Binding] mappings)
Variable Documentation
logger
dotenv.main.logger = logging.getLogger(__name__)