Vaccine Dashboard: flask_cors.core Namespace Reference
flask_cors.core Namespace Reference
Functions
def parse_resources (resources)
def get_regexp_pattern (regexp)
def get_cors_origins (options, request_origin)
def get_allow_headers (options, acl_request_headers)
def get_cors_headers (options, request_headers, request_method)
def set_cors_headers (resp, options)
def probably_regex (maybe_regex)
def re_fix (reg)
def try_match_any (inst, patterns)
def try_match (request_origin, maybe_regex)
def get_cors_options (appInstance, *dicts)
def get_app_kwarg_dict (appInstance=None)
def flexible_str (obj)
def serialize_option (options_dict, key, upper=False)
def ensure_iterable (inst)
def sanitize_regex_param (param)
def serialize_options (opts)
Variables
LOG = logging.getLogger(__name__)
string ACL_ORIGIN = 'Access-Control-Allow-Origin'
string ACL_METHODS = 'Access-Control-Allow-Methods'
string ACL_ALLOW_HEADERS = 'Access-Control-Allow-Headers'
string ACL_EXPOSE_HEADERS = 'Access-Control-Expose-Headers'
string ACL_CREDENTIALS = 'Access-Control-Allow-Credentials'
string ACL_MAX_AGE = 'Access-Control-Max-Age'
string ACL_REQUEST_METHOD = 'Access-Control-Request-Method'
string ACL_REQUEST_HEADERS = 'Access-Control-Request-Headers'
list ALL_METHODS = ['GET', 'HEAD', 'POST', 'OPTIONS', 'PUT', 'PATCH', 'DELETE']
list CONFIG_OPTIONS
string FLASK_CORS_EVALUATED = '_FLASK_CORS_EVALUATED'
RegexObject = type(re.compile(''))
DEFAULT_OPTIONS
Function Documentation
ensure_iterable()
def flask_cors.core.ensure_iterable (inst)
Wraps scalars or string types as a list, or returns the iterable instance.
flexible_str()
def flask_cors.core.flexible_str (obj)
A more flexible str function which intelligently handles stringifying
strings, lists and other iterables. The results are lexographically sorted
to ensure generated responses are consistent when iterables such as Set
are used.
References py._builtin.sorted, and pip._vendor.requests.compat.str.
get_allow_headers()
def flask_cors.core.get_allow_headers (options, acl_request_headers)
References pip._vendor.distlib.compat.filter, py._builtin.sorted, and flask_cors.core.try_match_any().
get_app_kwarg_dict()
def flask_cors.core.get_app_kwarg_dict (appInstance = None)
Returns the dictionary of CORS specific app configurations.
References pip._internal.utils.filesystem.replace.
get_cors_headers()
def flask_cors.core.get_cors_headers (options, request_headers, request_method)
References py._builtin.any, flask_cors.core.get_allow_headers(), and flask_cors.core.get_cors_origins().
get_cors_options()
def flask_cors.core.get_cors_options (appInstance, * dicts)
Compute CORS options for an application by combining the DEFAULT_OPTIONS,
the app's configuration-specified options and any dictionaries passed. The
last specified option wins.
References flask_cors.core.get_app_kwarg_dict(), and flask_cors.core.serialize_options().
get_cors_origins()
def flask_cors.core.get_cors_origins (options, request_origin)
References flask_cors.core.probably_regex(), py._builtin.sorted, and flask_cors.core.try_match_any().
get_regexp_pattern()
def flask_cors.core.get_regexp_pattern (regexp)
Helper that returns regexp pattern from given value.
:param regexp: regular expression to stringify
:type regexp: _sre.SRE_Pattern or str
:returns: string representation of given regexp pattern
:rtype: str
References pip._vendor.requests.compat.str.
parse_resources()
def flask_cors.core.parse_resources (resources)
References flask_cors.core.get_regexp_pattern(), flask_cors.core.re_fix(), and py._builtin.sorted.
probably_regex()
def flask_cors.core.probably_regex (maybe_regex)
References py._builtin.any.
re_fix()
def flask_cors.core.re_fix (reg)
    Replace the invalid regex r'*' with the valid, wildcard regex r'/.*' to
    enable the CORS app extension to have a more user friendly api.
sanitize_regex_param()
def flask_cors.core.sanitize_regex_param (param)
References flask_cors.core.ensure_iterable(), and flask_cors.core.re_fix().
serialize_option()
def flask_cors.core.serialize_option (options_dict, key, upper = False)
References flask_cors.core.flexible_str().
serialize_options()
def flask_cors.core.serialize_options (opts)
A helper method to serialize and processes the options dictionary.
References pip._vendor.distlib._backport.shutil.copy(), flask_cors.core.sanitize_regex_param(), flask_cors.core.serialize_option(), pip._vendor.requests.compat.str, and flask.helpers.total_seconds().
set_cors_headers()
def flask_cors.core.set_cors_headers (resp, options)
Performs the actual evaluation of Flas-CORS options and actually
modifies the response object.
This function is used both in the decorator and the after_request
callback
References flask_cors.core.get_cors_headers(), and pip._vendor.requests.compat.str.
try_match()
def flask_cors.core.try_match (request_origin, maybe_regex)
Safely attempts to match a pattern or string to a request origin.
References flask_cors.core.probably_regex().
try_match_any()
def flask_cors.core.try_match_any (inst, patterns)
References py._builtin.any, and flask_cors.core.try_match().
Variable Documentation
ACL_ALLOW_HEADERS
string flask_cors.core.ACL_ALLOW_HEADERS = 'Access-Control-Allow-Headers'
ACL_CREDENTIALS
string flask_cors.core.ACL_CREDENTIALS = 'Access-Control-Allow-Credentials'
ACL_EXPOSE_HEADERS
string flask_cors.core.ACL_EXPOSE_HEADERS = 'Access-Control-Expose-Headers'
ACL_MAX_AGE
string flask_cors.core.ACL_MAX_AGE = 'Access-Control-Max-Age'
ACL_METHODS
string flask_cors.core.ACL_METHODS = 'Access-Control-Allow-Methods'
ACL_ORIGIN
string flask_cors.core.ACL_ORIGIN = 'Access-Control-Allow-Origin'
ACL_REQUEST_HEADERS
string flask_cors.core.ACL_REQUEST_HEADERS = 'Access-Control-Request-Headers'
ACL_REQUEST_METHOD
string flask_cors.core.ACL_REQUEST_METHOD = 'Access-Control-Request-Method'
ALL_METHODS
list flask_cors.core.ALL_METHODS = ['GET', 'HEAD', 'POST', 'OPTIONS', 'PUT', 'PATCH', 'DELETE']
CONFIG_OPTIONS
list flask_cors.core.CONFIG_OPTIONS
Initial value:
 =  ['CORS_ORIGINS', 'CORS_METHODS', 'CORS_ALLOW_HEADERS',
                   'CORS_EXPOSE_HEADERS', 'CORS_SUPPORTS_CREDENTIALS',
                   'CORS_MAX_AGE', 'CORS_SEND_WILDCARD',
                   'CORS_AUTOMATIC_OPTIONS', 'CORS_VARY_HEADER',
                   'CORS_RESOURCES', 'CORS_INTERCEPT_EXCEPTIONS',
                   'CORS_ALWAYS_SEND']
DEFAULT_OPTIONS
flask_cors.core.DEFAULT_OPTIONS
Initial value:
 =  dict(origins='*',
                        methods=ALL_METHODS,
                        allow_headers='*',
                        expose_headers=None,
                        supports_credentials=False,
                        max_age=None,
                        send_wildcard=False,
                        automatic_options=True,
                        vary_header=True,
                        resources=r'/*',
                        intercept_exceptions=True,
                        always_send=True)
FLASK_CORS_EVALUATED
string flask_cors.core.FLASK_CORS_EVALUATED = '_FLASK_CORS_EVALUATED'
LOG
flask_cors.core.LOG = logging.getLogger(__name__)
RegexObject
flask_cors.core.RegexObject = type(re.compile(''))