Vaccine Dashboard: click.utils Namespace Reference
click.utils Namespace Reference
Classes
class LazyFile
class KeepOpenFile
class PacifyFlushWrapper
Functions
F safecall (F func)
str make_str (t.Any value)
str make_default_short_help (str help, int max_length=45)
None echo (t.Optional[t.Any] message=None, t.Optional[t.IO] file=None, bool nl=True, bool err=False, t.Optional[bool] color=None)
t.BinaryIO get_binary_stream ("te.Literal['stdin', 'stdout', 'stderr']" name)
t.TextIO get_text_stream ("te.Literal['stdin', 'stdout', 'stderr']" name, t.Optional[str] encoding=None, t.Optional[str] errors="strict")
t.IO open_file (str filename, str mode="r", t.Optional[str] encoding=None, t.Optional[str] errors="strict", bool lazy=False, bool atomic=False)
t.Sequence[str] get_os_args ()
str format_filename (t.Union[str, bytes, os.PathLike] filename, bool shorten=False)
str get_app_dir (str app_name, bool roaming=True, bool force_posix=False)
Variables
F = t.TypeVar("F", bound=t.Callable[..., t.Any])
Function Documentation
echo()
None click.utils.echo (t.Optional[t.Any] message = None, t.Optional[t.IO] file = None, bool nl = True, bool err = False, t.Optional[bool] color = None)
Print a message and newline to stdout or a file. This should be
used instead of :func:`print` because it provides better support
for different data, files, and environments.
Compared to :func:`print`, this does the following:
-   Ensures that the output encoding is not misconfigured on Linux.
-   Supports Unicode in the Windows console.
-   Supports writing to binary outputs, and supports writing bytes
    to text outputs.
-   Supports colors and styles on Windows.
-   Removes ANSI color and style codes if the output does not look
    like an interactive terminal.
-   Always flushes the output.
:param message: The string or bytes to output. Other objects are
    converted to strings.
:param file: The file to write to. Defaults to ``stdout``.
:param err: Write to ``stderr`` instead of ``stdout``.
:param nl: Print a newline after the message. Enabled by default.
:param color: Force showing or hiding colors and other styles. By
    default Click will remove color if the output does not look like
    an interactive terminal.
.. versionchanged:: 6.0
    Support Unicode output on the Windows console. Click does not
    modify ``sys.stdout``, so ``sys.stdout.write()`` and ``print()``
    will still not support Unicode.
.. versionchanged:: 4.0
    Added the ``color`` parameter.
.. versionadded:: 3.0
    Added the ``err`` parameter.
.. versionchanged:: 2.0
    Support colors on Windows if colorama is installed.
References click._compat.auto_wrap_for_ansi(), click.globals.resolve_color_default(), click._compat.should_strip_ansi(), pip._vendor.requests.compat.str, and click._compat.strip_ansi().
format_filename()
str click.utils.format_filename (t.Union[str, bytes, os.PathLike] filename, bool shorten = False)
Formats a filename for user display.  The main purpose of this
function is to ensure that the filename can be displayed at all.  This
will decode the filename to unicode if necessary in a way that it will
not fail.  Optionally, it can shorten the filename to not include the
full path to the filename.
:param filename: formats a filename for UI display.  This will also convert
                 the filename into unicode without failing.
:param shorten: this optionally shortens the filename to strip of the
                path that leads up to it.
get_app_dir()
str click.utils.get_app_dir (str app_name, bool roaming = True, bool force_posix = False)
Returns the config folder for the application.  The default behavior
is to return whatever is most appropriate for the operating system.
To give you an idea, for an app called ``"Foo Bar"``, something like
the following folders could be returned:
Mac OS X:
  ``~/Library/Application Support/Foo Bar``
Mac OS X (POSIX):
  ``~/.foo-bar``
Unix:
  ``~/.config/foo-bar``
Unix (POSIX):
  ``~/.foo-bar``
Windows (roaming):
  ``C:\Users\<user>\AppData\Roaming\Foo Bar``
Windows (not roaming):
  ``C:\Users\<user>\AppData\Local\Foo Bar``
.. versionadded:: 2.0
:param app_name: the application name.  This should be properly capitalized
                 and can contain whitespace.
:param roaming: controls if the folder should be roaming or not on Windows.
                Has no affect otherwise.
:param force_posix: if this is set to `True` then on any POSIX system the
                    folder will be stored in the home folder with a leading
                    dot instead of the XDG config home or darwin's
                    application support folder.
get_binary_stream()
t.BinaryIO click.utils.get_binary_stream ("te.Literal['stdin', 'stdout', 'stderr']" name)
Returns a system stream for byte processing.
:param name: the name of the stream to open.  Valid names are ``'stdin'``,
             ``'stdout'`` and ``'stderr'``
get_os_args()
t.Sequence[str] click.utils.get_os_args ()
Returns the argument part of ``sys.argv``, removing the first
value which is the name of the script.
.. deprecated:: 8.0
    Will be removed in Click 8.1. Access ``sys.argv[1:]`` directly
    instead.
get_text_stream()
t.TextIO click.utils.get_text_stream ("te.Literal['stdin', 'stdout', 'stderr']" name, t.Optional[str] encoding = None, t.Optional[str] errors = "strict")
Returns a system stream for text processing.  This usually returns
a wrapped stream around a binary stream returned from
:func:`get_binary_stream` but it also can take shortcuts for already
correctly configured streams.
:param name: the name of the stream to open.  Valid names are ``'stdin'``,
             ``'stdout'`` and ``'stderr'``
:param encoding: overrides the detected default encoding.
:param errors: overrides the default error mode.
make_default_short_help()
str click.utils.make_default_short_help (str help, int max_length = 45)
Returns a condensed version of help string.
References py._builtin.enumerate.
make_str()
str click.utils.make_str (t.Any value)
Converts a value into a valid string.
References click._compat.get_filesystem_encoding(), and pip._vendor.requests.compat.str.
open_file()
t.IO click.utils.open_file (str filename, str mode = "r", t.Optional[str] encoding = None, t.Optional[str] errors = "strict", bool lazy = False, bool atomic = False)
This is similar to how the :class:`File` works but for manual
usage.  Files are opened non lazy by default.  This can open regular
files as well as stdin/stdout if ``'-'`` is passed.
If stdin/stdout is returned the stream is wrapped so that the context
manager will not close the stream accidentally.  This makes it possible
to always use the function like this without having to worry to
accidentally close a standard stream::
    with open_file(filename) as f:
        ...
.. versionadded:: 3.0
:param filename: the name of the file to open (or ``'-'`` for stdin/stdout).
:param mode: the mode in which to open the file.
:param encoding: the encoding to use.
:param errors: the error handling for this file.
:param lazy: can be flipped to true to open the file lazily.
:param atomic: in atomic mode writes go into a temporary file and it's
               moved on close.
References click._compat.open_stream().
safecall()
F click.utils.safecall (F func)
Wraps a function so that it swallows exceptions.
Variable Documentation
F
click.utils.F = t.TypeVar("F", bound=t.Callable[..., t.Any])