Vaccine Dashboard: _pytest.mark Namespace Reference
_pytest.mark Namespace Reference
Namespaces
expression
structures
Classes
class KeywordMatcher
class MarkMatcher
Functions
ParameterSet param (*object values, Union[MarkDecorator, Collection[Union[MarkDecorator, Mark]]] marks=(), Optional[str] id=None)
None pytest_addoption (Parser parser)
Optional[Union[int, ExitCode]] pytest_cmdline_main (Config config)
None deselect_by_keyword ("List[Item]" items, Config config)
None deselect_by_mark ("List[Item]" items, Config config)
None pytest_collection_modifyitems ("List[Item]" items, Config config)
None pytest_configure (Config config)
None pytest_unconfigure (Config config)
Variables
old_mark_config_key = StoreKey[Optional[Config]]()
Detailed Description
Generic mechanism for marking and selecting python functions.
Function Documentation
deselect_by_keyword()
None _pytest.mark.deselect_by_keyword ("List[Item]" items, Config config)
deselect_by_mark()
None _pytest.mark.deselect_by_mark ("List[Item]" items, Config config)
param()
ParameterSet _pytest.mark.param (*object values, Union[MarkDecorator, Collection[Union[MarkDecorator, Mark]]] marks = (), Optional[str] id = None)
Specify a parameter in `pytest.mark.parametrize`_ calls or
:ref:`parametrized fixtures <fixture-parametrize-marks>`.
.. code-block:: python
    @pytest.mark.parametrize(
        "test_input,expected",
        [("3+5", 8), pytest.param("6*9", 42, marks=pytest.mark.xfail),],
    )
    def test_eval(test_input, expected):
        assert eval(test_input) == expected
:param values: Variable args of the values of the parameter set, in order.
:keyword marks: A single mark or a list of marks to be applied to this parameter set.
:keyword str id: The id to attribute to this parameter set.
pytest_addoption()
None _pytest.mark.pytest_addoption (Parser parser)
pytest_cmdline_main()
Optional[Union[int, ExitCode]] _pytest.mark.pytest_cmdline_main (Config config)
References _pytest.config.create_terminal_writer().
pytest_collection_modifyitems()
None _pytest.mark.pytest_collection_modifyitems ("List[Item]" items, Config config)
References _pytest.mark.deselect_by_keyword(), and _pytest.mark.deselect_by_mark().
pytest_configure()
None _pytest.mark.pytest_configure (Config config)
pytest_unconfigure()
None _pytest.mark.pytest_unconfigure (Config config)
Variable Documentation
old_mark_config_key
_pytest.mark.old_mark_config_key = StoreKey[Optional[Config]]()