Vaccine Dashboard: _pytest.runner Namespace Reference
_pytest.runner Namespace Reference
Classes
class CallInfo
class SetupState
Functions
None pytest_addoption (Parser parser)
None pytest_terminal_summary ("TerminalReporter" terminalreporter)
None pytest_sessionstart ("Session" session)
None pytest_sessionfinish ("Session" session)
bool pytest_runtest_protocol (Item item, Optional[Item] nextitem)
List[TestReport] runtestprotocol (Item item, bool log=True, Optional[Item] nextitem=None)
None show_test_item (Item item)
None pytest_runtest_setup (Item item)
None pytest_runtest_call (Item item)
None pytest_runtest_teardown (Item item, Optional[Item] nextitem)
Optional[Tuple[str, str, str]] pytest_report_teststatus (BaseReport report)
TestReport call_and_report (Item item, "Literal['setup', 'call', 'teardown']" when, bool log=True, **kwds)
bool check_interactive_exception ("CallInfo[object]" call, BaseReport report)
"CallInfo[None]" call_runtest_hook (Item item, "Literal['setup', 'call', 'teardown']" when, **kwds)
TestReport pytest_runtest_makereport (Item item, CallInfo[None] call)
CollectReport pytest_make_collect_report (Collector collector)
CollectReport collect_one_node (Collector collector)
Variables
TResult = TypeVar("TResult", covariant=True)
Detailed Description
Basic collect and runtest protocol implementations.
Function Documentation
call_and_report()
TestReport _pytest.runner.call_and_report (Item item, "Literal['setup', 'call', 'teardown']" when, bool log = True, ** kwds)
References _pytest.runner.call_runtest_hook(), and _pytest.runner.check_interactive_exception().
call_runtest_hook()
"CallInfo[None]" _pytest.runner.call_runtest_hook (Item item, "Literal['setup', 'call', 'teardown']" when, ** kwds)
check_interactive_exception()
bool _pytest.runner.check_interactive_exception ("CallInfo[object]" call, BaseReport report)
Check whether the call raised an exception that should be reported as
interactive.
collect_one_node()
CollectReport _pytest.runner.collect_one_node (Collector collector)
References _pytest.runner.check_interactive_exception().
pytest_addoption()
None _pytest.runner.pytest_addoption (Parser parser)
pytest_make_collect_report()
CollectReport _pytest.runner.pytest_make_collect_report (Collector collector)
References dotenv.cli.list(), and pip._vendor.requests.compat.str.
pytest_report_teststatus()
Optional[Tuple[str, str, str]] _pytest.runner.pytest_report_teststatus (BaseReport report)
pytest_runtest_call()
None _pytest.runner.pytest_runtest_call (Item item)
References dotenv.cli.type.
pytest_runtest_makereport()
TestReport _pytest.runner.pytest_runtest_makereport (Item item, CallInfo[None] call)
pytest_runtest_protocol()
bool _pytest.runner.pytest_runtest_protocol (Item item, Optional[Item] nextitem)
References _pytest.runner.runtestprotocol().
pytest_runtest_setup()
None _pytest.runner.pytest_runtest_setup (Item item)
pytest_runtest_teardown()
None _pytest.runner.pytest_runtest_teardown (Item item, Optional[Item] nextitem)
pytest_sessionfinish()
None _pytest.runner.pytest_sessionfinish ("Session" session)
pytest_sessionstart()
None _pytest.runner.pytest_sessionstart ("Session" session)
pytest_terminal_summary()
None _pytest.runner.pytest_terminal_summary ("TerminalReporter" terminalreporter)
References py._builtin.enumerate.
runtestprotocol()
List[TestReport] _pytest.runner.runtestprotocol (Item item, bool log = True, Optional[Item] nextitem = None)
References _pytest.runner.call_and_report(), and _pytest.runner.show_test_item().
show_test_item()
None _pytest.runner.show_test_item (Item item)
Show test function, parameters and the fixtures of the test item.
References py._builtin.sorted.
Variable Documentation
TResult
_pytest.runner.TResult = TypeVar("TResult", covariant=True)