Vaccine Dashboard: _pytest.mark.structures Namespace Reference
_pytest.mark.structures Namespace Reference
Classes
class ParameterSet
class Mark
class MarkDecorator
class _SkipMarkDecorator
class _SkipifMarkDecorator
class _XfailMarkDecorator
class _ParametrizeMarkDecorator
class _UsefixturesMarkDecorator
class _FilterwarningsMarkDecorator
class MarkGenerator
class NodeKeywords
Functions
bool istestfunc (func)
"MarkDecorator" get_empty_parameterset_mark (Config config, Sequence[str] argnames, func)
List[Mark] get_unpacked_marks (obj)
List[Mark] normalize_mark_list (Iterable[Union[Mark, MarkDecorator]] mark_list)
None store_mark (obj, Mark mark)
Variables
string EMPTY_PARAMETERSET_OPTION = "empty_parameter_set_mark"
MARK_GEN = MarkGenerator()
Function Documentation
get_empty_parameterset_mark()
"MarkDecorator" _pytest.mark.structures.get_empty_parameterset_mark (Config config, Sequence[str] argnames, func)
References _pytest._code.code.getfslineno().
get_unpacked_marks()
List[Mark] _pytest.mark.structures.get_unpacked_marks (obj)
Obtain the unpacked marks that are stored on an object.
References _pytest.mark.structures.normalize_mark_list().
istestfunc()
bool _pytest.mark.structures.istestfunc (func)
normalize_mark_list()
List[Mark] _pytest.mark.structures.normalize_mark_list (Iterable[Union[Mark, MarkDecorator]] mark_list)
Normalize marker decorating helpers to mark objects.
:type List[Union[Mark, Markdecorator]] mark_list:
:rtype: List[Mark]
store_mark()
None _pytest.mark.structures.store_mark (obj, Mark mark)
Store a Mark on an object.
This is used to implement the Mark declarations/decorators correctly.
References _pytest.mark.structures.get_unpacked_marks().
Variable Documentation
EMPTY_PARAMETERSET_OPTION
string _pytest.mark.structures.EMPTY_PARAMETERSET_OPTION = "empty_parameter_set_mark"
MARK_GEN
_pytest.mark.structures.MARK_GEN = MarkGenerator()