Vaccine Dashboard: click.decorators Namespace Reference
click.decorators Namespace Reference
Functions
F pass_context (F f)
F pass_obj (F f)
"t.Callable[[F], F]" make_pass_decorator (t.Type object_type, bool ensure=False)
"t.Callable[[F], F]" pass_meta_key (str key, *t.Optional[str] doc_description=None)
t.Callable[[F], Command] command (t.Optional[str] name=None, t.Optional[t.Type[Command]] cls=None, **t.Any attrs)
t.Callable[[F], Group] group (t.Optional[str] name=None, **t.Any attrs)
t.Callable[[FC], FC] argument (*str param_decls, **t.Any attrs)
t.Callable[[FC], FC] option (*str param_decls, **t.Any attrs)
t.Callable[[FC], FC] confirmation_option (*str param_decls, **t.Any kwargs)
t.Callable[[FC], FC] password_option (*str param_decls, **t.Any kwargs)
t.Callable[[FC], FC] version_option (t.Optional[str] version=None, *str param_decls, t.Optional[str] package_name=None, t.Optional[str] prog_name=None, t.Optional[str] message=None, **t.Any kwargs)
t.Callable[[FC], FC] help_option (*str param_decls, **t.Any kwargs)
Variables
F = t.TypeVar("F", bound=t.Callable[..., t.Any])
FC = t.TypeVar("FC", t.Callable[..., t.Any], Command)
Function Documentation
argument()
t.Callable[[FC], FC] click.decorators.argument (*str param_decls, **t.Any attrs)
Attaches an argument to the command.  All positional arguments are
passed as parameter declarations to :class:`Argument`; all keyword
arguments are forwarded unchanged (except ``cls``).
This is equivalent to creating an :class:`Argument` instance manually
and attaching it to the :attr:`Command.params` list.
:param cls: the argument class to instantiate.  This defaults to
            :class:`Argument`.
command()
t.Callable[[F], Command] click.decorators.command (t.Optional[str] name = None, t.Optional[t.Type[Command]] cls = None, **t.Any attrs)
Creates a new :class:`Command` and uses the decorated function as
callback.  This will also automatically attach all decorated
:func:`option`\s and :func:`argument`\s as parameters to the command.
The name of the command defaults to the name of the function with
underscores replaced by dashes.  If you want to change that, you can
pass the intended name as the first argument.
All keyword arguments are forwarded to the underlying command class.
Once decorated the function turns into a :class:`Command` instance
that can be invoked as a command line utility or be attached to a
command :class:`Group`.
:param name: the name of the command.  This defaults to the function
             name with underscores replaced by dashes.
:param cls: the command class to instantiate.  This defaults to
            :class:`Command`.
confirmation_option()
t.Callable[[FC], FC] click.decorators.confirmation_option (*str param_decls, **t.Any kwargs)
Add a ``--yes`` option which shows a prompt before continuing if
not passed. If the prompt is declined, the program will exit.
:param param_decls: One or more option names. Defaults to the single
    value ``"--yes"``.
:param kwargs: Extra arguments are passed to :func:`option`.
References click.decorators.option().
group()
t.Callable[[F], Group] click.decorators.group (t.Optional[str] name = None, **t.Any attrs)
Creates a new :class:`Group` with a function as callback.  This
works otherwise the same as :func:`command` just that the `cls`
parameter is set to :class:`Group`.
References click.decorators.command().
help_option()
t.Callable[[FC], FC] click.decorators.help_option (*str param_decls, **t.Any kwargs)
Add a ``--help`` option which immediately prints the help page
and exits the program.
This is usually unnecessary, as the ``--help`` option is added to
each command automatically unless ``add_help_option=False`` is
passed.
:param param_decls: One or more option names. Defaults to the single
    value ``"--help"``.
:param kwargs: Extra arguments are passed to :func:`option`.
References click.utils.echo(), and click.decorators.option().
make_pass_decorator()
"t.Callable[[F], F]" click.decorators.make_pass_decorator (t.Type object_type, bool ensure = False)
Given an object type this creates a decorator that will work
similar to :func:`pass_obj` but instead of passing the object of the
current context, it will find the innermost context of type
:func:`object_type`.
This generates a decorator that works roughly like this::
    from functools import update_wrapper
    def decorator(f):
        @pass_context
        def new_func(ctx, *args, **kwargs):
            obj = ctx.find_object(object_type)
            return ctx.invoke(f, obj, *args, **kwargs)
        return update_wrapper(new_func, f)
    return decorator
:param object_type: the type of the object to pass.
:param ensure: if set to `True`, a new object will be created and
               remembered on the context if it's not there yet.
References click.globals.get_current_context().
option()
t.Callable[[FC], FC] click.decorators.option (*str param_decls, **t.Any attrs)
Attaches an option to the command.  All positional arguments are
passed as parameter declarations to :class:`Option`; all keyword
arguments are forwarded unchanged (except ``cls``).
This is equivalent to creating an :class:`Option` instance manually
and attaching it to the :attr:`Command.params` list.
:param cls: the option class to instantiate.  This defaults to
            :class:`Option`.
pass_context()
F click.decorators.pass_context (F f)
Marks a callback as wanting to receive the current context
object as first argument.
References pycparser.ply.cpp.f, and click.globals.get_current_context().
pass_meta_key()
"t.Callable[[F], F]" click.decorators.pass_meta_key (str key, *t.Optional[str] doc_description = None)
Create a decorator that passes a key from
:attr:`click.Context.meta` as the first argument to the decorated
function.
:param key: Key in ``Context.meta`` to pass.
:param doc_description: Description of the object being passed,
    inserted into the decorator's docstring. Defaults to "the 'key'
    key from Context.meta".
.. versionadded:: 8.0
References click.globals.get_current_context(), and pip._internal.utils.filesystem.replace.
pass_obj()
F click.decorators.pass_obj (F f)
Similar to :func:`pass_context`, but only pass the object on the
context onwards (:attr:`Context.obj`).  This is useful if that object
represents the state of a nested system.
References pycparser.ply.cpp.f, and click.globals.get_current_context().
password_option()
t.Callable[[FC], FC] click.decorators.password_option (*str param_decls, **t.Any kwargs)
Add a ``--password`` option which prompts for a password, hiding
input and asking to enter the value again for confirmation.
:param param_decls: One or more option names. Defaults to the single
    value ``"--password"``.
:param kwargs: Extra arguments are passed to :func:`option`.
References click.decorators.option().
version_option()
t.Callable[[FC], FC] click.decorators.version_option (t.Optional[str] version = None, *str param_decls, t.Optional[str] package_name = None, t.Optional[str] prog_name = None, t.Optional[str] message = None, **t.Any kwargs)
Add a ``--version`` option which immediately prints the version
number and exits the program.
If ``version`` is not provided, Click will try to detect it using
:func:`importlib.metadata.version` to get the version for the
``package_name``. On Python < 3.8, the ``importlib_metadata``
backport must be installed.
If ``package_name`` is not provided, Click will try to detect it by
inspecting the stack frames. This will be used to detect the
version, so it must match the name of the installed package.
:param version: The version number to show. If not provided, Click
    will try to detect it.
:param param_decls: One or more option names. Defaults to the single
    value ``"--version"``.
:param package_name: The package name to detect the version from. If
    not provided, Click will try to detect it.
:param prog_name: The name of the CLI to show in the message. If not
    provided, it will be detected from the command.
:param message: The message to show. The values ``%(prog)s``,
    ``%(package)s``, and ``%(version)s`` are available. Defaults to
    ``"%(prog)s, version %(version)s"``.
:param kwargs: Extra arguments are passed to :func:`option`.
:raise RuntimeError: ``version`` could not be detected.
.. versionchanged:: 8.0
    Add the ``package_name`` parameter, and the ``%(package)s``
    value for messages.
.. versionchanged:: 8.0
    Use :mod:`importlib.metadata` instead of ``pkg_resources``. The
    version is detected based on the package name, not the entry
    point name. The Python package name must match the installed
    package name, or be passed with ``package_name=``.
References click.utils.echo(), and click.decorators.option().
Variable Documentation
F
click.decorators.F = t.TypeVar("F", bound=t.Callable[..., t.Any])
FC
click.decorators.FC = t.TypeVar("FC", t.Callable[..., t.Any], Command)