Vaccine Dashboard: _pytest.unittest Namespace Reference
_pytest.unittest Namespace Reference
Classes
class UnitTestCase
class TestCaseFunction
Functions
Optional["UnitTestCase"] pytest_pycollect_makeitem (PyCollector collector, str name, object obj)
None pytest_runtest_makereport (Item item, CallInfo[None] call)
Generator[None, None, None] pytest_runtest_protocol (Item item)
None check_testcase_implements_trial_reporter (List[int] done=[])
Detailed Description
Discover and run std-library "unittest" style tests.
Function Documentation
check_testcase_implements_trial_reporter()
None _pytest.unittest.check_testcase_implements_trial_reporter (List[int] done = [])
pytest_pycollect_makeitem()
Optional["UnitTestCase"] _pytest.unittest.pytest_pycollect_makeitem (PyCollector collector, str name, object obj)
pytest_runtest_makereport()
None _pytest.unittest.pytest_runtest_makereport (Item item, CallInfo[None] call)
References _pytest.unittest.check_testcase_implements_trial_reporter(), _pytest.unittest.pytest_runtest_protocol(), and pip._vendor.requests.compat.str.
pytest_runtest_protocol()
Generator[None, None, None] _pytest.unittest.pytest_runtest_protocol (Item item)
References _pytest.unittest.check_testcase_implements_trial_reporter(), and dotenv.cli.type.