Vaccine Dashboard: importlib_metadata Namespace Reference
importlib_metadata Namespace Reference
Namespaces
_adapters
_collections
_compat
_functools
_itertools
_meta
_text
Classes
class PackageNotFoundError
class Sectioned
class EntryPoint
class DeprecatedList
class EntryPoints
class Deprecated
class SelectableGroups
class PackagePath
class FileHash
class Distribution
class DistributionFinder
class FastPath
class Lookup
class Prepared
class MetadataPathFinder
class PathDistribution
Functions
def distribution (distribution_name)
def distributions (**kwargs)
_meta.PackageMetadata metadata (distribution_name)
def version (distribution_name)
Union[EntryPoints, SelectableGroups] entry_points (**params)
def files (distribution_name)
def requires (distribution_name)
Mapping[str, List[str]] packages_distributions ()
Function Documentation
distribution()
def importlib_metadata.distribution (distribution_name)
Get the ``Distribution`` instance for the named package.
:param distribution_name: The name of the distribution package as a string.
:return: A ``Distribution`` instance (or subclass thereof).
distributions()
def importlib_metadata.distributions (** kwargs)
Get all ``Distribution`` instances in the current environment.
:return: An iterable of ``Distribution`` instances.
entry_points()
Union[EntryPoints, SelectableGroups] importlib_metadata.entry_points (** params)
Return EntryPoint objects for all installed packages.
Pass selection parameters (group or name) to filter the
result to entry points matching those properties (see
EntryPoints.select()).
For compatibility, returns ``SelectableGroups`` object unless
selection parameters are supplied. In the future, this function
will return ``EntryPoints`` instead of ``SelectableGroups``
even when no selection parameters are supplied.
For maximum future compatibility, pass selection parameters
or invoke ``.select`` with parameters on the result.
:return: EntryPoints or SelectableGroups for all installed packages.
References distributions().
files()
def importlib_metadata.files (distribution_name)
Return a list of files for the named package.
:param distribution_name: The name of the distribution package to query.
:return: List of files composing the distribution.
References distribution().
metadata()
_meta.PackageMetadata importlib_metadata.metadata (distribution_name)
Get the metadata for the named package.
:param distribution_name: The name of the distribution package to query.
:return: A PackageMetadata containing the parsed metadata.
packages_distributions()
Mapping[str, List[str]] importlib_metadata.packages_distributions ()
Return a mapping of top-level packages to their
distributions.
>>> import collections.abc
>>> pkgs = packages_distributions()
>>> all(isinstance(dist, collections.abc.Sequence) for dist in pkgs.values())
True
References pip._vendor.urllib3.append, and distributions().
requires()
def importlib_metadata.requires (distribution_name)
Return a list of requirements for the named package.
:return: An iterator of requirements, suitable for
    packaging.requirement.Requirement.
References distribution().
version()
def importlib_metadata.version (distribution_name)
Get the version string for the named package.
:param distribution_name: The name of the distribution package to query.
:return: The version string for the package as defined in the package's
    "Version" metadata key.
References distribution().