Vaccine Dashboard: jwt.utils Namespace Reference
jwt.utils Namespace Reference
Functions
bytes force_bytes (Union[str, bytes] value)
bytes base64url_decode (Union[str, bytes] input)
bytes base64url_encode (bytes input)
bytes to_base64url_uint (int val)
int from_base64url_uint (Union[str, bytes] val)
bytes number_to_bytes (int num, int num_bytes)
int bytes_to_number (bytes string)
bytes bytes_from_int (int val)
bytes der_to_raw_signature (bytes der_sig, EllipticCurve curve)
bytes raw_to_der_signature (bytes raw_sig, EllipticCurve curve)
Variables
EllipticCurve = Any
Function Documentation
base64url_decode()
bytes jwt.utils.base64url_decode (Union[str, bytes] input)
base64url_encode()
bytes jwt.utils.base64url_encode (bytes input)
References pip._internal.utils.filesystem.replace.
bytes_from_int()
bytes jwt.utils.bytes_from_int (int val)
bytes_to_number()
int jwt.utils.bytes_to_number (bytes string)
der_to_raw_signature()
bytes jwt.utils.der_to_raw_signature (bytes der_sig, EllipticCurve curve)
References cryptography.hazmat.primitives.asymmetric.utils.decode_dss_signature(), and jwt.utils.number_to_bytes().
force_bytes()
bytes jwt.utils.force_bytes (Union[str, bytes] value)
from_base64url_uint()
int jwt.utils.from_base64url_uint (Union[str, bytes] val)
References jwt.utils.base64url_decode().
number_to_bytes()
bytes jwt.utils.number_to_bytes (int num, int num_bytes)
raw_to_der_signature()
bytes jwt.utils.raw_to_der_signature (bytes raw_sig, EllipticCurve curve)
References jwt.utils.bytes_to_number(), and cryptography.hazmat.primitives.asymmetric.utils.encode_dss_signature().
to_base64url_uint()
bytes jwt.utils.to_base64url_uint (int val)
References jwt.utils.base64url_encode(), and jwt.utils.bytes_from_int().
Variable Documentation
EllipticCurve
jwt.utils.EllipticCurve = Any