Vaccine Dashboard: werkzeug.http Namespace Reference
werkzeug.http Namespace Reference
Classes
class COEP
class COOP
Functions
str quote_header_value (t.Union[str, int] value, str extra_chars="", bool allow_token=True)
str unquote_header_value (str value, bool is_filename=False)
str dump_options_header (t.Optional[str] header, t.Mapping[str, t.Optional[t.Union[str, int]]] options)
str dump_header (t.Union[t.Dict[str, t.Union[str, int]], t.Iterable[str]] iterable, bool allow_token=True)
str dump_csp_header ("ds.ContentSecurityPolicy" header)
t.List[str] parse_list_header (str value)
t.Dict[str, str] parse_dict_header (str value, t.Type[dict] cls=dict)
t.Tuple[str, t.Dict[str, str]] parse_options_header (t.Optional[str] value, "te.Literal[False]" multiple=False)
t.Tuple[t.Any,...] parse_options_header (t.Optional[str] value, "te.Literal[True]" multiple)
t.Union[t.Tuple[str, t.Dict[str, str]], t.Tuple[t.Any,...]] parse_options_header (t.Optional[str] value, bool multiple=False)
"ds.Accept" parse_accept_header (t.Optional[str] value)
_TAnyAccept parse_accept_header (t.Optional[str] value, t.Type[_TAnyAccept] cls)
_TAnyAccept parse_accept_header (t.Optional[str] value, t.Optional[t.Type[_TAnyAccept]] cls=None)
"ds.RequestCacheControl" parse_cache_control_header (t.Optional[str] value, _t_cc_update on_update, None cls=None)
_TAnyCC parse_cache_control_header (t.Optional[str] value, _t_cc_update on_update, t.Type[_TAnyCC] cls)
_TAnyCC parse_cache_control_header (t.Optional[str] value, _t_cc_update on_update=None, t.Optional[t.Type[_TAnyCC]] cls=None)
"ds.ContentSecurityPolicy" parse_csp_header (t.Optional[str] value, _t_csp_update on_update, None cls=None)
_TAnyCSP parse_csp_header (t.Optional[str] value, _t_csp_update on_update, t.Type[_TAnyCSP] cls)
_TAnyCSP parse_csp_header (t.Optional[str] value, _t_csp_update on_update=None, t.Optional[t.Type[_TAnyCSP]] cls=None)
"ds.HeaderSet" parse_set_header (t.Optional[str] value, t.Optional[t.Callable[["ds.HeaderSet"], None]] on_update=None)
t.Optional["ds.Authorization"] parse_authorization_header (t.Optional[str] value)
"ds.WWWAuthenticate" parse_www_authenticate_header (t.Optional[str] value, t.Optional[t.Callable[["ds.WWWAuthenticate"], None]] on_update=None)
"ds.IfRange" parse_if_range_header (t.Optional[str] value)
t.Optional["ds.Range"] parse_range_header (t.Optional[str] value, bool make_inclusive=True)
t.Optional["ds.ContentRange"] parse_content_range_header (t.Optional[str] value, t.Optional[t.Callable[["ds.ContentRange"], None]] on_update=None)
str quote_etag (str etag, bool weak=False)
t.Union[t.Tuple[str, bool], t.Tuple[None, None]] unquote_etag (t.Optional[str] etag)
"ds.ETags" parse_etags (t.Optional[str] value)
str generate_etag (bytes data)
t.Optional[datetime] parse_date (t.Optional[str] value)
str cookie_date (t.Optional[t.Union[datetime, date, int, float, struct_time]] expires=None)
str http_date (t.Optional[t.Union[datetime, date, int, float, struct_time]] timestamp=None)
t.Optional[timedelta] parse_age (t.Optional[str] value=None)
t.Optional[str] dump_age (t.Optional[t.Union[timedelta, int]] age=None)
bool is_resource_modified ("WSGIEnvironment" environ, t.Optional[str] etag=None, t.Optional[bytes] data=None, t.Optional[t.Union[datetime, str]] last_modified=None, bool ignore_if_range=True)
None remove_entity_headers (t.Union["ds.Headers", t.List[t.Tuple[str, str]]] headers, t.Iterable[str] allowed=("expires", "content-location"))
None remove_hop_by_hop_headers (t.Union["ds.Headers", t.List[t.Tuple[str, str]]] headers)
bool is_entity_header (str header)
bool is_hop_by_hop_header (str header)
"ds.MultiDict[str, str]" parse_cookie (t.Union["WSGIEnvironment", str, bytes, None] header, str charset="utf-8", str errors="replace", t.Optional[t.Type["ds.MultiDict"]] cls=None)
str dump_cookie (str key, t.Union[bytes, str] value="", t.Optional[t.Union[timedelta, int]] max_age=None, t.Optional[t.Union[str, datetime, int, float]] expires=None, t.Optional[str] path="/", t.Optional[str] domain=None, bool secure=False, bool httponly=False, str charset="utf-8", bool sync_expires=True, int max_size=4093, t.Optional[str] samesite=None)
bool is_byte_range_valid (t.Optional[int] start, t.Optional[int] stop, t.Optional[int] length)
Variables
dictionary HTTP_STATUS_CODES
Function Documentation
cookie_date()
str werkzeug.http.cookie_date (t.Optional[t.Union[datetime, date, int, float, struct_time]] expires = None)
Format a datetime object or timestamp into an :rfc:`2822` date
string for ``Set-Cookie expires``.
.. deprecated:: 2.0
    Will be removed in Werkzeug 2.1. Use :func:`http_date` instead.
References werkzeug.http.http_date().
dump_age()
t.Optional[str] werkzeug.http.dump_age (t.Optional[t.Union[timedelta, int]] age = None)
Formats the duration as a base-10 integer.
:param age: should be an integer number of seconds,
            a :class:`datetime.timedelta` object, or,
            if the age is unknown, `None` (default).
References pip._vendor.requests.compat.str.
dump_cookie()
str werkzeug.http.dump_cookie (str key, t.Union[bytes, str] value = "", t.Optional[t.Union[timedelta, int]] max_age = None, t.Optional[t.Union[str, datetime, int, float]] expires = None, t.Optional[str] path = "/", t.Optional[str] domain = None, bool secure = False, bool httponly = False, str charset = "utf-8", bool sync_expires = True, int max_size = 4093, t.Optional[str] samesite = None)
Create a Set-Cookie header without the ``Set-Cookie`` prefix.
The return value is usually restricted to ascii as the vast majority
of values are properly escaped, but that is no guarantee. It's
tunneled through latin1 as required by :pep:`3333`.
The return value is not ASCII safe if the key contains unicode
characters.  This is technically against the specification but
happens in the wild.  It's strongly recommended to not use
non-ASCII values for the keys.
:param max_age: should be a number of seconds, or `None` (default) if
                the cookie should last only as long as the client's
                browser session.  Additionally `timedelta` objects
                are accepted, too.
:param expires: should be a `datetime` object or unix timestamp.
:param path: limits the cookie to a given path, per default it will
             span the whole domain.
:param domain: Use this if you want to set a cross-domain cookie. For
               example, ``domain=".example.com"`` will set a cookie
               that is readable by the domain ``www.example.com``,
               ``foo.example.com`` etc. Otherwise, a cookie will only
               be readable by the domain that set it.
:param secure: The cookie will only be available via HTTPS
:param httponly: disallow JavaScript to access the cookie.  This is an
                 extension to the cookie standard and probably not
                 supported by all browsers.
:param charset: the encoding for string values.
:param sync_expires: automatically set expires if max_age is defined
                     but expires not.
:param max_size: Warn if the final header value exceeds this size. The
    default, 4093, should be safely `supported by most browsers
    <cookie_>`_. Set to 0 to disable this check.
:param samesite: Limits the scope of the cookie such that it will
    only be attached to requests if those requests are same-site.
.. _`cookie`: http://browsercookielimits.squawky.net/
.. versionchanged:: 1.0.0
    The string ``'None'`` is accepted for ``samesite``.
References pip._vendor.requests.compat.bytes, werkzeug.http.http_date(), werkzeug.urls.iri_to_uri(), and pip._vendor.requests.compat.str.
dump_csp_header()
str werkzeug.http.dump_csp_header ("ds.ContentSecurityPolicy" header)
Dump a Content Security Policy header.
These are structured into policies such as "default-src 'self';
script-src 'self'".
.. versionadded:: 1.0.0
   Support for Content Security Policy headers was added.
dump_header()
str werkzeug.http.dump_header (t.Union[t.Dict[str, t.Union[str, int]], t.Iterable[str]] iterable, bool allow_token = True)
Dump an HTTP header again.  This is the reversal of
:func:`parse_list_header`, :func:`parse_set_header` and
:func:`parse_dict_header`.  This also quotes strings that include an
equals sign unless you pass it as dict of key, value pairs.
>>> dump_header({'foo': 'bar baz'})
'foo="bar baz"'
>>> dump_header(('foo', 'bar baz'))
'foo, "bar baz"'
:param iterable: the iterable or dict of values to quote.
:param allow_token: if set to `False` tokens as values are disallowed.
                    See :func:`quote_header_value` for more details.
References werkzeug.http.quote_header_value().
dump_options_header()
str werkzeug.http.dump_options_header (t.Optional[str] header, t.Mapping[str, t.Optional[t.Union[str, int]]] options)
The reverse function to :func:`parse_options_header`.
:param header: the header to dump
:param options: a dict of options to append.
generate_etag()
str werkzeug.http.generate_etag (bytes data)
Generate an etag for some data.
.. versionchanged:: 2.0
    Use SHA-1. MD5 may not be available in some environments.
http_date()
str werkzeug.http.http_date (t.Optional[t.Union[datetime, date, int, float, struct_time]] timestamp = None)
Format a datetime object or timestamp into an :rfc:`2822` date
string.
This is a wrapper for :func:`email.utils.format_datetime`. It
assumes naive datetime objects are in UTC instead of raising an
exception.
:param timestamp: The datetime or timestamp to format. Defaults to
    the current time.
.. versionchanged:: 2.0
    Use ``email.utils.format_datetime``. Accept ``date`` objects.
is_byte_range_valid()
bool werkzeug.http.is_byte_range_valid (t.Optional[int] start, t.Optional[int] stop, t.Optional[int] length)
Checks if a given byte content range is valid for the given length.
.. versionadded:: 0.7
is_entity_header()
bool werkzeug.http.is_entity_header (str header)
Check if a header is an entity header.
.. versionadded:: 0.5
:param header: the header to test.
:return: `True` if it's an entity header, `False` otherwise.
is_hop_by_hop_header()
bool werkzeug.http.is_hop_by_hop_header (str header)
Check if a header is an HTTP/1.1 "Hop-by-Hop" header.
.. versionadded:: 0.5
:param header: the header to test.
:return: `True` if it's an HTTP/1.1 "Hop-by-Hop" header, `False` otherwise.
is_resource_modified()
bool werkzeug.http.is_resource_modified ("WSGIEnvironment" environ, t.Optional[str] etag = None, t.Optional[bytes] data = None, t.Optional[t.Union[datetime, str]] last_modified = None, bool ignore_if_range = True)
Convenience method for conditional requests.
:param environ: the WSGI environment of the request to be checked.
:param etag: the etag for the response for comparison.
:param data: or alternatively the data of the response to automatically
             generate an etag using :func:`generate_etag`.
:param last_modified: an optional date of the last modification.
:param ignore_if_range: If `False`, `If-Range` header will be taken into
                        account.
:return: `True` if the resource was modified, otherwise `False`.
.. versionchanged:: 2.0
    SHA-1 is used to generate an etag value for the data. MD5 may
    not be available in some environments.
.. versionchanged:: 1.0.0
    The check is run for methods other than ``GET`` and ``HEAD``.
References werkzeug.http.generate_etag(), werkzeug.http.parse_date(), werkzeug.http.parse_etags(), werkzeug.http.parse_if_range_header(), and werkzeug.http.unquote_etag().
parse_accept_header() [1/3]
"ds.Accept" werkzeug.http.parse_accept_header (t.Optional[str] value)
parse_accept_header() [2/3]
_TAnyAccept werkzeug.http.parse_accept_header (t.Optional[str] value, t.Optional[t.Type[_TAnyAccept]] cls = None)
Parses an HTTP Accept-* header.  This does not implement a complete
valid algorithm but one that supports at least value and quality
extraction.
Returns a new :class:`Accept` object (basically a list of ``(value, quality)``
tuples sorted by the quality with some additional accessor methods).
The second parameter can be a subclass of :class:`Accept` that is created
with the parsed values and returned.
:param value: the accept header string to be parsed.
:param cls: the wrapper class for the return value (can be
                     :class:`Accept` or a subclass thereof)
:return: an instance of `cls`.
References werkzeug.http.parse_accept_header().
parse_accept_header() [3/3]
_TAnyAccept werkzeug.http.parse_accept_header (t.Optional[str] value, t.Type[_TAnyAccept] cls)
References werkzeug.http.parse_accept_header().
parse_age()
t.Optional[timedelta] werkzeug.http.parse_age (t.Optional[str] value = None)
Parses a base-10 integer count of seconds into a timedelta.
If parsing fails, the return value is `None`.
:param value: a string consisting of an integer represented in base-10
:return: a :class:`datetime.timedelta` object or `None`.
parse_authorization_header()
t.Optional["ds.Authorization"] werkzeug.http.parse_authorization_header (t.Optional[str] value)
Parse an HTTP basic/digest authorization header transmitted by the web
browser.  The return value is either `None` if the header was invalid or
not given, otherwise an :class:`~werkzeug.datastructures.Authorization`
object.
:param value: the authorization header to parse.
:return: a :class:`~werkzeug.datastructures.Authorization` object or `None`.
References werkzeug.http.parse_dict_header().
parse_cache_control_header() [1/3]
"ds.RequestCacheControl" werkzeug.http.parse_cache_control_header (t.Optional[str] value, _t_cc_update on_update, None cls = None)
parse_cache_control_header() [2/3]
_TAnyCC werkzeug.http.parse_cache_control_header (t.Optional[str] value, _t_cc_update on_update, t.Type[_TAnyCC] cls)
References werkzeug.http.parse_cache_control_header().
parse_cache_control_header() [3/3]
_TAnyCC werkzeug.http.parse_cache_control_header (t.Optional[str] value, _t_cc_update on_update = None, t.Optional[t.Type[_TAnyCC]] cls = None)
Parse a cache control header.  The RFC differs between response and
request cache control, this method does not.  It's your responsibility
to not use the wrong control statements.
.. versionadded:: 0.5
   The `cls` was added.  If not specified an immutable
   :class:`~werkzeug.datastructures.RequestCacheControl` is returned.
:param value: a cache control header to be parsed.
:param on_update: an optional callable that is called every time a value
                  on the :class:`~werkzeug.datastructures.CacheControl`
                  object is changed.
:param cls: the class for the returned object.  By default
            :class:`~werkzeug.datastructures.RequestCacheControl` is used.
:return: a `cls` object.
References werkzeug.http.parse_cache_control_header(), and werkzeug.http.parse_dict_header().
parse_content_range_header()
t.Optional["ds.ContentRange"] werkzeug.http.parse_content_range_header (t.Optional[str] value, t.Optional[t.Callable[["ds.ContentRange"], None]] on_update = None)
Parses a range header into a
:class:`~werkzeug.datastructures.ContentRange` object or `None` if
parsing is not possible.
.. versionadded:: 0.7
:param value: a content range header to be parsed.
:param on_update: an optional callable that is called every time a value
                  on the :class:`~werkzeug.datastructures.ContentRange`
                  object is changed.
References werkzeug.http.is_byte_range_valid().
parse_cookie()
"ds.MultiDict[str, str]" werkzeug.http.parse_cookie (t.Union["WSGIEnvironment", str, bytes, None] header, str charset = "utf-8", str errors = "replace", t.Optional[t.Type["ds.MultiDict"]] cls = None)
Parse a cookie from a string or WSGI environ.
The same key can be provided multiple times, the values are stored
in-order. The default :class:`MultiDict` will have the first value
first, and all values can be retrieved with
:meth:`MultiDict.getlist`.
:param header: The cookie header as a string, or a WSGI environ dict
    with a ``HTTP_COOKIE`` key.
:param charset: The charset for the cookie values.
:param errors: The error behavior for the charset decoding.
:param cls: A dict-like class to store the parsed cookies in.
    Defaults to :class:`MultiDict`.
.. versionchanged:: 1.0.0
    Returns a :class:`MultiDict` instead of a
    ``TypeConversionDict``.
.. versionchanged:: 0.5
   Returns a :class:`TypeConversionDict` instead of a regular dict.
   The ``cls`` parameter was added.
parse_csp_header() [1/3]
"ds.ContentSecurityPolicy" werkzeug.http.parse_csp_header (t.Optional[str] value, _t_csp_update on_update, None cls = None)
parse_csp_header() [2/3]
_TAnyCSP werkzeug.http.parse_csp_header (t.Optional[str] value, _t_csp_update on_update, t.Type[_TAnyCSP] cls)
References werkzeug.http.parse_csp_header().
parse_csp_header() [3/3]
_TAnyCSP werkzeug.http.parse_csp_header (t.Optional[str] value, _t_csp_update on_update = None, t.Optional[t.Type[_TAnyCSP]] cls = None)
Parse a Content Security Policy header.
.. versionadded:: 1.0.0
   Support for Content Security Policy headers was added.
:param value: a csp header to be parsed.
:param on_update: an optional callable that is called every time a value
                  on the object is changed.
:param cls: the class for the returned object.  By default
            :class:`~werkzeug.datastructures.ContentSecurityPolicy` is used.
:return: a `cls` object.
References werkzeug.http.parse_csp_header().
parse_date()
t.Optional[datetime] werkzeug.http.parse_date (t.Optional[str] value)
Parse an :rfc:`2822` date into a timezone-aware
:class:`datetime.datetime` object, or ``None`` if parsing fails.
This is a wrapper for :func:`email.utils.parsedate_to_datetime`. It
returns ``None`` if parsing fails instead of raising an exception,
and always returns a timezone-aware datetime object. If the string
doesn't have timezone information, it is assumed to be UTC.
:param value: A string with a supported date format.
.. versionchanged:: 2.0
    Return a timezone-aware datetime object. Use
    ``email.utils.parsedate_to_datetime``.
parse_dict_header()
t.Dict[str, str] werkzeug.http.parse_dict_header (str value, t.Type[dict] cls = dict)
Parse lists of key, value pairs as described by RFC 2068 Section 2 and
convert them into a python dict (or any other mapping object created from
the type with a dict like interface provided by the `cls` argument):
>>> d = parse_dict_header('foo="is a fish", bar="as well"')
>>> type(d) is dict
True
>>> sorted(d.items())
[('bar', 'as well'), ('foo', 'is a fish')]
If there is no value for a key it will be `None`:
>>> parse_dict_header('key_without_value')
{'key_without_value': None}
To create a header from the :class:`dict` again, use the
:func:`dump_header` function.
.. versionchanged:: 0.9
   Added support for `cls` argument.
:param value: a string with a dict header.
:param cls: callable to use for storage of parsed results.
:return: an instance of `cls`
References werkzeug.http.unquote_header_value().
parse_etags()
"ds.ETags" werkzeug.http.parse_etags (t.Optional[str] value)
Parse an etag header.
:param value: the tag header to parse
:return: an :class:`~werkzeug.datastructures.ETags` object.
parse_if_range_header()
"ds.IfRange" werkzeug.http.parse_if_range_header (t.Optional[str] value)
Parses an if-range header which can be an etag or a date.  Returns
a :class:`~werkzeug.datastructures.IfRange` object.
.. versionchanged:: 2.0
    If the value represents a datetime, it is timezone-aware.
.. versionadded:: 0.7
References werkzeug.http.parse_date(), and werkzeug.http.unquote_etag().
parse_list_header()
t.List[str] werkzeug.http.parse_list_header (str value)
Parse lists as described by RFC 2068 Section 2.
In particular, parse comma-separated lists where the elements of
the list may include quoted-strings.  A quoted-string could
contain a comma.  A non-quoted string could have quotes in the
middle.  Quotes are removed automatically after parsing.
It basically works like :func:`parse_set_header` just that items
may appear multiple times and case sensitivity is preserved.
The return value is a standard :class:`list`:
>>> parse_list_header('token, "quoted value"')
['token', 'quoted value']
To create a header from the :class:`list` again, use the
:func:`dump_header` function.
:param value: a string with a list header.
:return: :class:`list`
References werkzeug.http.unquote_header_value().
parse_options_header() [1/3]
t.Tuple[str, t.Dict[str, str]] werkzeug.http.parse_options_header (t.Optional[str] value, "te.Literal[False]" multiple = False)
parse_options_header() [2/3]
t.Tuple[t.Any, ...] werkzeug.http.parse_options_header (t.Optional[str] value, "te.Literal[True]" multiple)
References werkzeug.http.parse_options_header().
parse_options_header() [3/3]
t.Union[t.Tuple[str, t.Dict[str, str]], t.Tuple[t.Any, ...]] werkzeug.http.parse_options_header (t.Optional[str] value, bool multiple = False)
Parse a ``Content-Type`` like header into a tuple with the content
type and the options:
>>> parse_options_header('text/html; charset=utf8')
('text/html', {'charset': 'utf8'})
This should not be used to parse ``Cache-Control`` like headers that use
a slightly different format.  For these headers use the
:func:`parse_dict_header` function.
.. versionchanged:: 0.15
    :rfc:`2231` parameter continuations are handled.
.. versionadded:: 0.5
:param value: the header to parse.
:param multiple: Whether try to parse and return multiple MIME types
:return: (mimetype, options) or (mimetype, options, mimetype, options,)
         if multiple=True
References jwt.api_jws.decode, werkzeug.http.parse_options_header(), and werkzeug.http.unquote_header_value().
parse_range_header()
t.Optional["ds.Range"] werkzeug.http.parse_range_header (t.Optional[str] value, bool make_inclusive = True)
Parses a range header into a :class:`~werkzeug.datastructures.Range`
object.  If the header is missing or malformed `None` is returned.
`ranges` is a list of ``(start, stop)`` tuples where the ranges are
non-inclusive.
.. versionadded:: 0.7
parse_set_header()
"ds.HeaderSet" werkzeug.http.parse_set_header (t.Optional[str] value, t.Optional[t.Callable[["ds.HeaderSet"], None]] on_update = None)
Parse a set-like header and return a
:class:`~werkzeug.datastructures.HeaderSet` object:
>>> hs = parse_set_header('token, "quoted value"')
The return value is an object that treats the items case-insensitively
and keeps the order of the items:
>>> 'TOKEN' in hs
True
>>> hs.index('quoted value')
1
>>> hs
HeaderSet(['token', 'quoted value'])
To create a header from the :class:`HeaderSet` again, use the
:func:`dump_header` function.
:param value: a set header to be parsed.
:param on_update: an optional callable that is called every time a
                  value on the :class:`~werkzeug.datastructures.HeaderSet`
                  object is changed.
:return: a :class:`~werkzeug.datastructures.HeaderSet`
References werkzeug.http.parse_list_header().
parse_www_authenticate_header()
"ds.WWWAuthenticate" werkzeug.http.parse_www_authenticate_header (t.Optional[str] value, t.Optional[t.Callable[["ds.WWWAuthenticate"], None]] on_update = None)
Parse an HTTP WWW-Authenticate header into a
:class:`~werkzeug.datastructures.WWWAuthenticate` object.
:param value: a WWW-Authenticate header to parse.
:param on_update: an optional callable that is called every time a value
                  on the :class:`~werkzeug.datastructures.WWWAuthenticate`
                  object is changed.
:return: a :class:`~werkzeug.datastructures.WWWAuthenticate` object.
References werkzeug.http.parse_dict_header().
quote_etag()
str werkzeug.http.quote_etag (str etag, bool weak = False)
Quote an etag.
:param etag: the etag to quote.
:param weak: set to `True` to tag it "weak".
quote_header_value()
str werkzeug.http.quote_header_value (t.Union[str, int] value, str extra_chars = "", bool allow_token = True)
Quote a header value if necessary.
.. versionadded:: 0.5
:param value: the value to quote.
:param extra_chars: a list of extra characters to skip quoting.
:param allow_token: if this is enabled token values are returned
                    unchanged.
References pip._internal.utils.filesystem.replace, py._builtin.set, and pip._vendor.requests.compat.str.
remove_entity_headers()
None werkzeug.http.remove_entity_headers (t.Union["ds.Headers", t.List[t.Tuple[str, str]]] headers, t.Iterable[str] allowed = ("expires", "content-location"))
Remove all entity headers from a list or :class:`Headers` object.  This
operation works in-place.  `Expires` and `Content-Location` headers are
by default not removed.  The reason for this is :rfc:`2616` section
10.3.5 which specifies some entity headers that should be sent.
.. versionchanged:: 0.5
   added `allowed` parameter.
:param headers: a list or :class:`Headers` object.
:param allowed: a list of headers that should still be allowed even though
                they are entity headers.
References werkzeug.http.is_entity_header().
remove_hop_by_hop_headers()
None werkzeug.http.remove_hop_by_hop_headers (t.Union["ds.Headers", t.List[t.Tuple[str, str]]] headers)
Remove all HTTP/1.1 "Hop-by-Hop" headers from a list or
:class:`Headers` object.  This operation works in-place.
.. versionadded:: 0.5
:param headers: a list or :class:`Headers` object.
References werkzeug.http.is_hop_by_hop_header().
unquote_etag()
t.Union[t.Tuple[str, bool], t.Tuple[None, None]] werkzeug.http.unquote_etag (t.Optional[str] etag)
Unquote a single etag:
>>> unquote_etag('W/"bar"')
('bar', True)
>>> unquote_etag('"bar"')
('bar', False)
:param etag: the etag identifier to unquote.
:return: a ``(etag, weak)`` tuple.
unquote_header_value()
str werkzeug.http.unquote_header_value (str value, bool is_filename = False)
Unquotes a header value.  (Reversal of :func:`quote_header_value`).
This does not use the real unquoting but what browsers are actually
using for quoting.
.. versionadded:: 0.5
:param value: the header value to unquote.
:param is_filename: The value represents a filename or path.
References pip._internal.utils.filesystem.replace.
Variable Documentation
HTTP_STATUS_CODES
dictionary werkzeug.http.HTTP_STATUS_CODES