Vaccine Dashboard: _pytest.python Namespace Reference
_pytest.python Namespace Reference
Classes
class PyobjMixin
class _EmptyClass
Functions
None pytest_addoption (Parser parser)
Optional[Union[int, ExitCode]] pytest_cmdline_main (Config config)
None pytest_generate_tests ("Metafunc" metafunc)
None pytest_configure (Config config)
None async_warn_and_skip (str nodeid)
Optional[object] pytest_pyfunc_call ("Function" pyfuncitem)
Optional["Module"] pytest_collect_file (py.path.local path, nodes.Collector parent)
bool path_matches_patterns (py.path.local path, Iterable[str] patterns)
"Module" pytest_pycollect_makemodule (py.path.local path, parent)
def pytest_pycollect_makeitem ("PyCollector" collector, str name, object obj)
Detailed Description
Python test discovery, setup and run of test functions.
Function Documentation
async_warn_and_skip()
None _pytest.python.async_warn_and_skip (str nodeid)
References _pytest.outcomes.skip().
path_matches_patterns()
bool _pytest.python.path_matches_patterns (py.path.local path, Iterable[str] patterns)
Return whether path matches any of the patterns in the list of globs given.
References py._builtin.any.
pytest_addoption()
None _pytest.python.pytest_addoption (Parser parser)
pytest_cmdline_main()
Optional[Union[int, ExitCode]] _pytest.python.pytest_cmdline_main (Config config)
pytest_collect_file()
Optional["Module"] _pytest.python.pytest_collect_file (py.path.local path, nodes.Collector parent)
References _pytest.python.path_matches_patterns().
pytest_configure()
None _pytest.python.pytest_configure (Config config)
pytest_generate_tests()
None _pytest.python.pytest_generate_tests ("Metafunc" metafunc)
pytest_pycollect_makeitem()
def _pytest.python.pytest_pycollect_makeitem ("PyCollector" collector, str name, object obj)
References _pytest.compat.get_real_func(), _pytest._code.code.getfslineno(), _pytest.compat.is_generator(), dotenv.cli.list(), _pytest.compat.safe_isclass(), and pip._vendor.requests.compat.str.
pytest_pycollect_makemodule()
"Module" _pytest.python.pytest_pycollect_makemodule (py.path.local path, parent)
pytest_pyfunc_call()
Optional[object] _pytest.python.pytest_pyfunc_call ("Function" pyfuncitem)
References _pytest.python.async_warn_and_skip(), and _pytest.compat.is_async_function().