Vaccine Dashboard: werkzeug.sansio.utils Namespace Reference
werkzeug.sansio.utils Namespace Reference
Functions
bool host_is_trusted (str hostname, t.Iterable[str] trusted_list)
str get_host (str scheme, t.Optional[str] host_header, t.Optional[t.Tuple[str, t.Optional[int]]] server=None, t.Optional[t.Iterable[str]] trusted_hosts=None)
str get_current_url (str scheme, str host, t.Optional[str] root_path=None, t.Optional[str] path=None, t.Optional[bytes] query_string=None)
Function Documentation
get_current_url()
str werkzeug.sansio.utils.get_current_url (str scheme, str host, t.Optional[str] root_path = None, t.Optional[str] path = None, t.Optional[bytes] query_string = None)
Recreate the URL for a request. If an optional part isn't
provided, it and subsequent parts are not included in the URL.
The URL is an IRI, not a URI, so it may contain Unicode characters.
Use :func:`~werkzeug.urls.iri_to_uri` to convert it to ASCII.
:param scheme: The protocol the request used, like ``"https"``.
:param host: The host the request was made to. See :func:`get_host`.
:param root_path: Prefix that the application is mounted under. This
    is prepended to ``path``.
:param path: The path part of the URL after ``root_path``.
:param query_string: The portion of the URL after the "?".
References werkzeug.urls.uri_to_iri(), and jinja2.utils.url_quote().
get_host()
str werkzeug.sansio.utils.get_host (str scheme, t.Optional[str] host_header, t.Optional[t.Tuple[str, t.Optional[int]]] server = None, t.Optional[t.Iterable[str]] trusted_hosts = None)
Return the host for the given parameters.
This first checks the ``host_header``. If it's not present, then
``server`` is used. The host will only contain the port if it is
different than the standard port for the protocol.
Optionally, verify that the host is trusted using
:func:`host_is_trusted` and raise a
:exc:`~werkzeug.exceptions.SecurityError` if it is not.
:param scheme: The protocol the request used, like ``"https"``.
:param host_header: The ``Host`` header value.
:param server: Address of the server. ``(host, port)``, or
    ``(path, None)`` for unix sockets.
:param trusted_hosts: A list of trusted host names.
:return: Host, with port if necessary.
:raise ~werkzeug.exceptions.SecurityError: If the host is not
    trusted.
References werkzeug.sansio.utils.host_is_trusted().
host_is_trusted()
bool werkzeug.sansio.utils.host_is_trusted (str hostname, t.Iterable[str] trusted_list)
Check if a host matches a list of trusted names.
:param hostname: The name to check.
:param trusted_list: A list of valid names to match. If a name
    starts with a dot it will match all subdomains.
.. versionadded:: 0.9