Vaccine Dashboard: _pytest.config Namespace Reference
_pytest.config Namespace Reference
Namespaces
argparsing
exceptions
findpaths
Classes
class ExitCode
class ConftestImportFailure
class cmdline
class PytestPluginManager
class Notset
class Config
Functions
bool filter_traceback_for_conftest_import_failure (_pytest._code.TracebackEntry entry)
Union[int, ExitCode] main (Optional[Union[List[str], py.path.local]] args=None, Optional[Sequence[Union[str, _PluggyPlugin]]] plugins=None)
int console_main ()
str filename_arg (str path, str optname)
str directory_arg (str path, str optname)
"Config" get_config (Optional[List[str]] args=None, Optional[Sequence[Union[str, _PluggyPlugin]]] plugins=None)
"PytestPluginManager" get_plugin_manager ()
TerminalWriter create_terminal_writer (Config config, Optional[TextIO] file=None)
Tuple[str, str, Type[Warning], str, int] parse_warning_filter (str arg, *bool escape)
None apply_warning_filters (Iterable[str] config_filters, Iterable[str] cmdline_filters)
Variables
hookimpl = HookimplMarker("pytest")
hookspec = HookspecMarker("pytest")
tuple essential_plugins
tuple default_plugins
builtin_plugins = set(default_plugins)
notset = Notset()
Detailed Description
Command line options, ini-file and conftest.py processing.
Function Documentation
apply_warning_filters()
None _pytest.config.apply_warning_filters (Iterable[str] config_filters, Iterable[str] cmdline_filters)
Applies pytest-configured filters to the warnings module
References _pytest.config.parse_warning_filter().
console_main()
int _pytest.config.console_main ()
The CLI entry point of pytest.
This function is not meant for programmable use; use `main()` instead.
References _pytest.config.main().
create_terminal_writer()
TerminalWriter _pytest.config.create_terminal_writer (Config config, Optional[TextIO] file = None)
Create a TerminalWriter instance configured according to the options
in the config object.
Every code which requires a TerminalWriter object and has access to a
config object should use this function.
directory_arg()
str _pytest.config.directory_arg (str path, str optname)
Argparse type validator for directory arguments.
:path: Path of directory.
:optname: Name of the option.
filename_arg()
str _pytest.config.filename_arg (str path, str optname)
Argparse type validator for filename arguments.
:path: Path of filename.
:optname: Name of the option.
filter_traceback_for_conftest_import_failure()
bool _pytest.config.filter_traceback_for_conftest_import_failure (_pytest._code.TracebackEntry entry)
Filter tracebacks entries which point to pytest internals or importlib.
Make a special case for importlib because we use it to import test modules and conftest files
in _pytest.pathlib.import_path.
References _pytest._code.code.filter_traceback(), and pip._vendor.requests.compat.str.
get_config()
"Config" _pytest.config.get_config (Optional[List[str]] args = None, Optional[Sequence[Union[str, _PluggyPlugin]]] plugins = None)
get_plugin_manager()
"PytestPluginManager" _pytest.config.get_plugin_manager ()
Obtain a new instance of the
:py:class:`_pytest.config.PytestPluginManager`, with default plugins
already loaded.
This function can be used by integration with other tools, like hooking
into pytest to run tests into an IDE.
References _pytest.config.get_config(), pip._vendor.requests.compat.str, and dotenv.cli.type.
main()
Union[int, ExitCode] _pytest.config.main (Optional[Union[List[str], py.path.local]] args = None, Optional[Sequence[Union[str, _PluggyPlugin]]] plugins = None)
Perform an in-process test run.
:param args: List of command line arguments.
:param plugins: List of plugin objects to be auto-registered during initialization.
:returns: An exit code.
References pip._vendor.requests.compat.str.
parse_warning_filter()
Tuple[str, str, Type[Warning], str, int] _pytest.config.parse_warning_filter (str arg, *bool escape)
Parse a warnings filter string.
This is copied from warnings._setoption, but does not apply the filter,
only parses it, and makes the escaping optional.
Variable Documentation
builtin_plugins
_pytest.config.builtin_plugins = set(default_plugins)
default_plugins
tuple _pytest.config.default_plugins
Initial value:
 =  essential_plugins + (
     "python",
     "terminal",
     "debugging",
     "unittest",
     "capture",
     "skipping",
     "tmpdir",
     "monkeypatch",
     "recwarn",
     "pastebin",
     "nose",
     "assertion",
     "junitxml",
     "doctest",
     "cacheprovider",
     "freeze_support",
     "setuponly",
     "setupplan",
     "stepwise",
     "warnings",
     "logging",
     "reports",
     *(["unraisableexception", "threadexception"] if sys.version_info >= (3, 8) else []),
     "faulthandler",
 )
essential_plugins
tuple _pytest.config.essential_plugins
Initial value:
 =  (
     "mark",
     "main",
     "runner",
     "fixtures",
     "helpconfig",  # Provides -p.
 )
hookimpl
_pytest.config.hookimpl = HookimplMarker("pytest")
hookspec
_pytest.config.hookspec = HookspecMarker("pytest")
notset
_pytest.config.notset = Notset()