Vaccine Dashboard: _pytest.compat Namespace Reference
_pytest.compat Namespace Reference
Classes
class NotSetType
class _PytestWrapper
class cached_property
Functions
bool is_generator (object func)
bool iscoroutinefunction (object func)
bool is_async_function (object func)
str getlocation (function, Optional[str] curdir=None)
int num_mock_patch_args (function)
Tuple[str,...] getfuncargnames (Callable[..., Any] function, *str name="", bool is_method=False, Optional[type] cls=None)
def nullcontext ()
Tuple[str,...] get_default_arg_names (Callable[..., Any] function)
str ascii_escaped (Union[bytes, str] val)
def get_real_func (obj)
def get_real_method (obj, holder)
def getimfunc (func)
Any safe_getattr (Any object, str name, Any default)
bool safe_isclass (object obj)
def final (f)
"NoReturn" assert_never ("NoReturn" value)
Variables
REGEX_TYPE = type(re.compile(""))
STRING_TYPES = bytes, str
Detailed Description
Python version compatibility code.
Function Documentation
ascii_escaped()
str _pytest.compat.ascii_escaped (Union[bytes, str] val)
If val is pure ASCII, return it as an str, otherwise, escape
bytes objects into a sequence of escaped bytes:
b'\xc3\xb4\xc5\xd6' -> r'\xc3\xb4\xc5\xd6'
and escapes unicode objects into a sequence of escaped unicode
ids, e.g.:
r'4\nV\U00043efa\x0eMXWB\x1e\u3028\u15fd\xcd\U0007d944'
Note:
   The obvious "v.decode('unicode-escape')" will return
   valid UTF-8 unicode if it finds them in bytes, but we
   want to return escaped bytes for any byte, even if they match
   a UTF-8 string.
References jwt.api_jws.decode.
assert_never()
"NoReturn" _pytest.compat.assert_never ("NoReturn" value)
References dotenv.cli.type.
final()
def _pytest.compat.final (f)
get_default_arg_names()
Tuple[str, ...] _pytest.compat.get_default_arg_names (Callable[..., Any] function)
References pip._vendor.pyparsing.range.
get_real_func()
def _pytest.compat.get_real_func (obj)
Get the real function object of the (possibly) wrapped object by
functools.wraps or functools.partial.
References pip._vendor.pyparsing.range, and _pytest._io.saferepr.saferepr().
get_real_method()
def _pytest.compat.get_real_method (obj, holder)
Attempt to obtain the real function object that might be wrapping
``obj``, while at the same time returning a bound method to ``holder`` if
the original object was a bound method.
References pip._vendor.distlib.compat.callable(), and _pytest.compat.get_real_func().
getfuncargnames()
Tuple[str, ...] _pytest.compat.getfuncargnames (Callable[..., Any] function, *str name = "", bool is_method = False, Optional[type] cls = None)
Return the names of a function's mandatory arguments.
Should return the names of all function arguments that:
* Aren't bound to an instance or type as in instance or class methods.
* Don't have default values.
* Aren't bound with functools.partial.
* Aren't replaced with mocks.
The is_method and cls arguments indicate that the function should
be treated as a bound method even though it's not unless, only in
the case of cls, the function is a static method.
The name parameter should be the original name in which the function was collected.
References _pytest.outcomes.fail(), dotenv.cli.get(), and _pytest.compat.num_mock_patch_args().
getimfunc()
def _pytest.compat.getimfunc (func)
getlocation()
str _pytest.compat.getlocation (function, Optional[str] curdir = None)
References _pytest.compat.get_real_func().
is_async_function()
bool _pytest.compat.is_async_function (object func)
Return True if the given function seems to be an async function or
an async generator.
References _pytest.compat.iscoroutinefunction().
is_generator()
bool _pytest.compat.is_generator (object func)
References _pytest.compat.iscoroutinefunction().
iscoroutinefunction()
bool _pytest.compat.iscoroutinefunction (object func)
Return True if func is a coroutine function (a function defined with async
def syntax, and doesn't contain yield), or a function decorated with
@asyncio.coroutine.
Note: copied and modified from Python 3.5's builtin couroutines.py to avoid
importing asyncio directly, which in turns also initializes the "logging"
module as a side-effect (see issue #8).
nullcontext()
def _pytest.compat.nullcontext ()
num_mock_patch_args()
int _pytest.compat.num_mock_patch_args (function)
Return number of arguments used up by mock arguments (if any).
safe_getattr()
Any _pytest.compat.safe_getattr (Any object, str name, Any default)
Like getattr but return default upon any Exception or any OutcomeException.
Attribute access can potentially fail for 'evil' Python objects.
See issue #214.
It catches OutcomeException because of #2490 (issue #580), new outcomes
are derived from BaseException instead of Exception (for more details
check #2707).
safe_isclass()
bool _pytest.compat.safe_isclass (object obj)
Ignore any exception via isinstance on Python 3.
Variable Documentation
REGEX_TYPE
_pytest.compat.REGEX_TYPE = type(re.compile(""))
STRING_TYPES
_pytest.compat.STRING_TYPES = bytes, str