My Project: test_api Namespace Reference
test_api Namespace Reference
Functions
def client ()
def getData (client, data)
def login (client, data)
def getCard (client, data)
def test_get_state (client)
def test_get_state_age (client)
def test_get_state_age_vax (client)
def test_valid_login (client)
def test_invalid_username (client)
def test_invalid_password (client)
def test_getCard_noLogin (client)
def test_getCard_invalidToken (client)
Detailed Description
@package API test
Tests the API.
Dependencies:
 - Flask
 - Pytest
 - Dotenv
Function Documentation
client()
def test_api.client ()
Creates the API client to be used.
@return the test_client() module of the API
getCard()
def test_api.getCard (client, data)
A helper function for the getCard() tests
@param client - the api client being tested
@param data - the authenication header being tested
@return the HTTP status of the authentication and the image data
Referenced by test_getCard_invalidToken(), and test_getCard_noLogin().
getData()
def test_api.getData (client, data)
A helper function for getVaccineData() tests
@param client - the api client being tested
@param data - the data to be passed as the query string
@return the data retrieved
Referenced by test_get_state(), test_get_state_age(), and test_get_state_age_vax().
login()
def test_api.login (client, data)
A helper function for the login() tests
@param client - the api client being tested
@param data - the username and password used to login
@return the HTTP status and token
Referenced by test_invalid_password(), test_invalid_username(), and test_valid_login().
test_get_state()
def test_api.test_get_state (client)
Tests whether the getVaccineData() API hook works when passed a state.
@param client - the api client being tested
References getData().
test_get_state_age()
def test_api.test_get_state_age (client)
Tests whether the getVaccineData() API hook works when passed a state and age group
@param client - the api client being tested
References getData().
test_get_state_age_vax()
def test_api.test_get_state_age_vax (client)
Tests whether the getVaccineData() API hook works when passed a state, age group, and vaccine type.
@param client - the api client being tested
References getData().
test_getCard_invalidToken()
def test_api.test_getCard_invalidToken (client)
Tests whether the getCard() API hook returns an error status when given an invalid token but valid user data
@param client - the api client being tested
References getCard().
test_getCard_noLogin()
def test_api.test_getCard_noLogin (client)
Tests whether the getCard() API hook returns an error status when given no authentication data
@param client - the api client being tested
References getCard().
test_invalid_password()
def test_api.test_invalid_password (client)
Tests whether the login() API hook returns an error status when given a valid username and invalid password
@param client - the api client being tested
References login().
test_invalid_username()
def test_api.test_invalid_username (client)
Tests whether the login() API hook returns an error status when given an invalid username
@param client - the api client being tested
References login().
test_valid_login()
def test_api.test_valid_login (client)
Tests whether the login() API hook works given a valid user
@param client - the api client being tested
References login().