Vaccine Dashboard: werkzeug.local.Local Class Reference
werkzeug.local.Local Class Reference
Public Member Functions
None __init__ (self)
t.Dict[str, t.Any] __storage__ (self)
t.Callable[[], int] __ident_func__ (self)
None __ident_func__ (self, t.Callable[[], int] func)
t.Iterator[t.Tuple[int, t.Any]] __iter__ (self)
"LocalProxy" __call__ (self, str proxy)
None __release_local__ (self)
t.Any __getattr__ (self, str name)
None __setattr__ (self, str name, t.Any value)
None __delattr__ (self, str name)
Constructor & Destructor Documentation
__init__()
None werkzeug.local.Local.__init__ (self)
Member Function Documentation
__call__()
"LocalProxy" werkzeug.local.Local.__call__ (self, str proxy)
Create a proxy for a name.
__delattr__()
None werkzeug.local.Local.__delattr__ (self, str name)
References pip._vendor.distlib._backport.shutil.copy(), dotenv.cli.get(), and py._builtin.set.
__getattr__()
t.Any werkzeug.local.Local.__getattr__ (self, str name)
References dotenv.cli.get().
__ident_func__() [1/2]
t.Callable[[], int] werkzeug.local.Local.__ident_func__ (self)
__ident_func__() [2/2]
None werkzeug.local.Local.__ident_func__ (self, t.Callable[[], int] func)
References werkzeug.local.Local.__ident_func__().
__iter__()
t.Iterator[t.Tuple[int, t.Any]] werkzeug.local.Local.__iter__ (self)
References dotenv.cli.get().
__release_local__()
None werkzeug.local.Local.__release_local__ (self)
References py._builtin.set.
__setattr__()
None werkzeug.local.Local.__setattr__ (self, str name, t.Any value)
References pip._vendor.distlib._backport.shutil.copy(), dotenv.cli.get(), and py._builtin.set.
__storage__()
t.Dict[str, t.Any] werkzeug.local.Local.__storage__ (self)
References dotenv.cli.get().
The documentation for this class was generated from the following file:
back-end/flaskenv/Lib/site-packages/werkzeug/local.py