Vaccine Dashboard: jinja2.debug Namespace Reference
jinja2.debug Namespace Reference
Classes
class _CTraceback
Functions
BaseException rewrite_traceback_stack (t.Optional[str] source=None)
TracebackType fake_traceback (BaseException exc_value, t.Optional[TracebackType] tb, str filename, int lineno)
t.Dict[str, t.Any] get_template_locals (t.Mapping[str, t.Any] real_locals)
TracebackType tb_set_next (TracebackType tb, t.Optional[TracebackType] tb_next)
Function Documentation
fake_traceback()
TracebackType jinja2.debug.fake_traceback (BaseException exc_value, t.Optional[TracebackType] tb, str filename, int lineno)
Produce a new traceback object that looks like it came from the
template source instead of the compiled code. The filename, line
number, and location name will point to the template, and the local
variables will be the current template context.
:param exc_value: The original exception to be re-raised to create
    the new traceback.
:param tb: The original traceback to get the local variables and
    code info from.
:param filename: The template filename.
:param lineno: The line number in the template source.
References cffi.ffiplatform.compile(), and jinja2.debug.get_template_locals().
get_template_locals()
t.Dict[str, t.Any] jinja2.debug.get_template_locals (t.Mapping[str, t.Any] real_locals)
Based on the runtime locals, get the context that would be
available at that point in the template.
References pip._vendor.distlib._backport.shutil.copy().
rewrite_traceback_stack()
BaseException jinja2.debug.rewrite_traceback_stack (t.Optional[str] source = None)
Rewrite the current exception to replace any tracebacks from
within compiled template code with tracebacks that look like they
came from the template source.
This must be called within an ``except`` block.
:param source: For ``TemplateSyntaxError``, the original source if
    known.
:return: The original exception with the rewritten traceback.
References jinja2.debug.fake_traceback(), py._builtin.reversed, and jinja2.debug.tb_set_next().
tb_set_next()
TracebackType jinja2.debug.tb_set_next (TracebackType tb, t.Optional[TracebackType] tb_next)