Vaccine Dashboard: _pytest.skipping Namespace Reference
_pytest.skipping Namespace Reference
Classes
class Skip
class Xfail
Functions
None pytest_addoption (Parser parser)
None pytest_configure (Config config)
Tuple[bool, str] evaluate_condition (Item item, Mark mark, object condition)
Optional[Skip] evaluate_skip_marks (Item item)
Optional[Xfail] evaluate_xfail_marks (Item item)
None pytest_runtest_setup (Item item)
Generator[None, None, None] pytest_runtest_call (Item item)
def pytest_runtest_makereport (Item item, CallInfo[None] call)
Optional[Tuple[str, str, str]] pytest_report_teststatus (BaseReport report)
Variables
skipped_by_mark_key = StoreKey[bool]()
xfailed_key = StoreKey[Optional[Xfail]]()
unexpectedsuccess_key = StoreKey[str]()
Detailed Description
Support for skip/xfail functions and markers.
Function Documentation
evaluate_condition()
Tuple[bool, str] _pytest.skipping.evaluate_condition (Item item, Mark mark, object condition)
Evaluate a single skipif/xfail condition.
If an old-style string condition is given, it is eval()'d, otherwise the
condition is bool()'d. If this fails, an appropriately formatted pytest.fail
is raised.
Returns (result, reason). The reason is only relevant if the result is True.
References cffi.ffiplatform.compile(), _pytest.outcomes.fail(), py._builtin.reversed, and dotenv.cli.type.
evaluate_skip_marks()
Optional[Skip] _pytest.skipping.evaluate_skip_marks (Item item)
Evaluate skip and skipif marks on item, returning Skip if triggered.
References _pytest.skipping.evaluate_condition().
evaluate_xfail_marks()
Optional[Xfail] _pytest.skipping.evaluate_xfail_marks (Item item)
Evaluate xfail marks on item, returning Xfail if triggered.
References _pytest.skipping.evaluate_condition().
pytest_addoption()
None _pytest.skipping.pytest_addoption (Parser parser)
pytest_configure()
None _pytest.skipping.pytest_configure (Config config)
pytest_report_teststatus()
Optional[Tuple[str, str, str]] _pytest.skipping.pytest_report_teststatus (BaseReport report)
pytest_runtest_call()
Generator[None, None, None] _pytest.skipping.pytest_runtest_call (Item item)
References _pytest.skipping.evaluate_xfail_marks(), and _pytest.outcomes.xfail().
pytest_runtest_makereport()
def _pytest.skipping.pytest_runtest_makereport (Item item, CallInfo[None] call)
References pip._vendor.requests.compat.str, and dotenv.cli.type.
pytest_runtest_setup()
None _pytest.skipping.pytest_runtest_setup (Item item)
References _pytest.skipping.evaluate_skip_marks(), _pytest.skipping.evaluate_xfail_marks(), _pytest.outcomes.skip(), and _pytest.outcomes.xfail().
Variable Documentation
skipped_by_mark_key
_pytest.skipping.skipped_by_mark_key = StoreKey[bool]()
unexpectedsuccess_key
_pytest.skipping.unexpectedsuccess_key = StoreKey[str]()
xfailed_key
_pytest.skipping.xfailed_key = StoreKey[Optional[Xfail]]()