Vaccine Dashboard: py._io.terminalwriter Namespace Reference
py._io.terminalwriter Namespace Reference
Classes
class TerminalWriter
class Win32ConsoleWriter
class WriteFile
class COORD
class SMALL_RECT
class CONSOLE_SCREEN_BUFFER_INFO
Functions
def get_terminal_width ()
def get_line_width (text)
def ansi_print (text, esc, file=None, newline=True, flush=False)
def should_do_markup (file)
def GetStdHandle (kind)
def GetConsoleInfo (handle)
def write_out (fil, msg)
Variables
int py3k = 3
tuple py33 = (3, 3)
bool win32_and_ctypes = False
colorama = None
def terminal_width = get_terminal_width()
dictionary char_width
TerminalWriter = Win32ConsoleWriter
int STD_OUTPUT_HANDLE = -11
int STD_ERROR_HANDLE = -12
int FOREGROUND_BLACK = 0x0000
int FOREGROUND_BLUE = 0x0001
int FOREGROUND_GREEN = 0x0002
int FOREGROUND_RED = 0x0004
int FOREGROUND_WHITE = 0x0007
int FOREGROUND_INTENSITY = 0x0008
int BACKGROUND_BLACK = 0x0000
int BACKGROUND_BLUE = 0x0010
int BACKGROUND_GREEN = 0x0020
int BACKGROUND_RED = 0x0040
int BACKGROUND_WHITE = 0x0070
int BACKGROUND_INTENSITY = 0x0080
SHORT = ctypes.c_short
argtypes
restype
SetConsoleTextAttribute = ctypes.windll.kernel32.SetConsoleTextAttribute
Detailed Description
Helper functions for writing to terminals and files.
Function Documentation
ansi_print()
def py._io.terminalwriter.ansi_print (text, esc, file = None, newline = True, flush = False)
References py._io.terminalwriter.GetConsoleInfo(), py._io.terminalwriter.GetStdHandle(), and py._io.terminalwriter.SetConsoleTextAttribute.
get_line_width()
def py._io.terminalwriter.get_line_width (text)
get_terminal_width()
def py._io.terminalwriter.get_terminal_width ()
GetConsoleInfo()
def py._io.terminalwriter.GetConsoleInfo (handle)
References py._io.terminalwriter.GetStdHandle().
GetStdHandle()
def py._io.terminalwriter.GetStdHandle (kind)
should_do_markup()
def py._io.terminalwriter.should_do_markup (file)
write_out()
def py._io.terminalwriter.write_out (fil, msg)
References jwt.api_jws.decode.
Variable Documentation
argtypes
py._io.terminalwriter.argtypes
BACKGROUND_BLACK
int py._io.terminalwriter.BACKGROUND_BLACK = 0x0000
BACKGROUND_BLUE
int py._io.terminalwriter.BACKGROUND_BLUE = 0x0010
BACKGROUND_GREEN
int py._io.terminalwriter.BACKGROUND_GREEN = 0x0020
BACKGROUND_INTENSITY
int py._io.terminalwriter.BACKGROUND_INTENSITY = 0x0080
BACKGROUND_RED
int py._io.terminalwriter.BACKGROUND_RED = 0x0040
BACKGROUND_WHITE
int py._io.terminalwriter.BACKGROUND_WHITE = 0x0070
char_width
dictionary py._io.terminalwriter.char_width
Initial value:
 =  {
     'A': 1,   # "Ambiguous"
     'F': 2,   # Fullwidth
     'H': 1,   # Halfwidth
     'N': 1,   # Neutral
     'Na': 1,  # Narrow
     'W': 2,   # Wide
 }
colorama
py._io.terminalwriter.colorama = None
FOREGROUND_BLACK
int py._io.terminalwriter.FOREGROUND_BLACK = 0x0000
FOREGROUND_BLUE
int py._io.terminalwriter.FOREGROUND_BLUE = 0x0001
FOREGROUND_GREEN
int py._io.terminalwriter.FOREGROUND_GREEN = 0x0002
FOREGROUND_INTENSITY
int py._io.terminalwriter.FOREGROUND_INTENSITY = 0x0008
FOREGROUND_RED
int py._io.terminalwriter.FOREGROUND_RED = 0x0004
FOREGROUND_WHITE
int py._io.terminalwriter.FOREGROUND_WHITE = 0x0007
py33
tuple py._io.terminalwriter.py33 = (3, 3)
py3k
int py._io.terminalwriter.py3k = 3
restype
py._io.terminalwriter.restype
SetConsoleTextAttribute
py._io.terminalwriter.SetConsoleTextAttribute = ctypes.windll.kernel32.SetConsoleTextAttribute
SHORT
py._io.terminalwriter.SHORT = ctypes.c_short
STD_ERROR_HANDLE
int py._io.terminalwriter.STD_ERROR_HANDLE = -12
STD_OUTPUT_HANDLE
int py._io.terminalwriter.STD_OUTPUT_HANDLE = -11
terminal_width
def py._io.terminalwriter.terminal_width = get_terminal_width()
TerminalWriter
py._io.terminalwriter.TerminalWriter = Win32ConsoleWriter
win32_and_ctypes
bool py._io.terminalwriter.win32_and_ctypes = False