Vaccine Dashboard: werkzeug.test Namespace Reference
werkzeug.test Namespace Reference
Classes
class _TestCookieHeaders
class _TestCookieResponse
class _TestCookieJar
class EnvironBuilder
class ClientRedirectError
class Client
class TestResponse
Functions
t.Tuple[t.BinaryIO, int, str] stream_encode_multipart (t.Mapping[str, t.Any] data, bool use_tempfile=True, int threshold=1024 *500, t.Optional[str] boundary=None, str charset="utf-8")
t.Tuple[str, bytes] encode_multipart (t.Mapping[str, t.Any] values, t.Optional[str] boundary=None, str charset="utf-8")
"WSGIEnvironment" create_environ (*t.Any args, **t.Any kwargs)
t.Tuple[t.Iterable[bytes], str, Headers] run_wsgi_app ("WSGIApplication" app, "WSGIEnvironment" environ, bool buffered=False)
Function Documentation
create_environ()
"WSGIEnvironment" werkzeug.test.create_environ (*t.Any args, **t.Any kwargs)
Create a new WSGI environ dict based on the values passed.  The first
parameter should be the path of the request which defaults to '/'.  The
second one can either be an absolute path (in that case the host is
localhost:80) or a full path to the request with scheme, netloc port and
the path to the script.
This accepts the same arguments as the :class:`EnvironBuilder`
constructor.
.. versionchanged:: 0.5
   This function is now a thin wrapper over :class:`EnvironBuilder` which
   was added in 0.5.  The `headers`, `environ_base`, `environ_overrides`
   and `charset` parameters were added.
encode_multipart()
t.Tuple[str, bytes] werkzeug.test.encode_multipart (t.Mapping[str, t.Any] values, t.Optional[str] boundary = None, str charset = "utf-8")
Like `stream_encode_multipart` but returns a tuple in the form
(``boundary``, ``data``) where data is bytes.
References werkzeug.test.stream_encode_multipart().
run_wsgi_app()
t.Tuple[t.Iterable[bytes], str, Headers] werkzeug.test.run_wsgi_app ("WSGIApplication" app, "WSGIEnvironment" environ, bool buffered = False)
Return a tuple in the form (app_iter, status, headers) of the
application output.  This works best if you pass it an application that
returns an iterator all the time.
Sometimes applications may use the `write()` callable returned
by the `start_response` function.  This tries to resolve such edge
cases automatically.  But if you don't get the expected output you
should set `buffered` to `True` which enforces buffering.
If passed an invalid WSGI application the behavior of this function is
undefined.  Never pass non-conforming WSGI applications to this function.
:param app: the application to execute.
:param buffered: set to `True` to enforce buffering.
:return: tuple in the form ``(app_iter, status, headers)``
References api.app, pip._vendor.distlib._backport.shutil.copy(), and dotenv.cli.list().
stream_encode_multipart()
t.Tuple[t.BinaryIO, int, str] werkzeug.test.stream_encode_multipart (t.Mapping[str, t.Any] data, bool use_tempfile = True, int threshold = 1024 * 500, t.Optional[str] boundary = None, str charset = "utf-8")
Encode a dict of values (either strings or file descriptors or
:class:`FileStorage` objects.) into a multipart encoded string stored
in a file descriptor.
References pip._vendor.six.BytesIO, and pip._vendor.requests.compat.str.