Vaccine Dashboard: py._code.source Namespace Reference
py._code.source Namespace Reference
Classes
class Source
Functions
def compile_ (source, filename=None, mode='exec', flags=generators.compiler_flag, dont_inherit=0)
def getfslineno (obj)
def findsource (obj)
def getsource (obj, **kwargs)
def deindent (lines, offset=None)
def get_statement_startend2 (lineno, node)
def getstatementrange_ast (lineno, source, assertion=False, astnode=None)
def getstatementrange_old (lineno, source, assertion=False)
Variables
cpy_compile = compile
Function Documentation
compile_()
def py._code.source.compile_ (source, filename = None, mode = 'exec', flags = generators.compiler_flag, dont_inherit = 0)
 compile the given source to a raw code object,
    and maintain an internal cache which allows later
    retrieval of the source code for the code object
    and any recursively created code objects.
References py._code.source.cpy_compile.
deindent()
def py._code.source.deindent (lines, offset = None)
References dotenv.cli.list(), pip._vendor.six.next, and pip._vendor.pyparsing.range.
findsource()
def py._code.source.findsource (obj)
get_statement_startend2()
def py._code.source.get_statement_startend2 (lineno, node)
getfslineno()
def py._code.source.getfslineno (obj)
 Return source location (path, lineno) for the given object.
If the source cannot be determined return ("", -1)
References py._code.source.findsource().
getsource()
def py._code.source.getsource (obj, ** kwargs)
getstatementrange_ast()
def py._code.source.getstatementrange_ast (lineno, source, assertion = False, astnode = None)
References cffi.ffiplatform.compile(), py._code.source.get_statement_startend2(), py._code.source.getstatementrange_old(), pip._vendor.six.next, and pip._vendor.requests.compat.str.
getstatementrange_old()
def py._code.source.getstatementrange_old (lineno, source, assertion = False)
 return (start, end) tuple which spans the minimal
    statement region which containing the given lineno.
    raise an IndexError if no such statementrange can be found.
References pip._vendor.pyparsing.range.
Variable Documentation
cpy_compile
py._code.source.cpy_compile = compile