Vaccine Dashboard: flask_cors.decorator Namespace Reference
flask_cors.decorator Namespace Reference
Functions
def cross_origin (*args, **kwargs)
Variables
LOG = logging.getLogger(__name__)
Function Documentation
cross_origin()
def flask_cors.decorator.cross_origin (* args, ** kwargs)
This function is the decorator which is used to wrap a Flask route with.
In the simplest case, simply use the default parameters to allow all
origins in what is the most permissive configuration. If this method
modifies state or performs authentication which may be brute-forced, you
should add some degree of protection, such as Cross Site Forgery
Request protection.
:param origins:
    The origin, or list of origins to allow requests from.
    The origin(s) may be regular expressions, case-sensitive strings,
    or else an asterisk
    Default : '*'
:type origins: list, string or regex
:param methods:
    The method or list of methods which the allowed origins are allowed to
    access for non-simple requests.
    Default : [GET, HEAD, POST, OPTIONS, PUT, PATCH, DELETE]
:type methods: list or string
:param expose_headers:
    The header or list which are safe to expose to the API of a CORS API
    specification.
    Default : None
:type expose_headers: list or string
:param allow_headers:
    The header or list of header field names which can be used when this
    resource is accessed by allowed origins. The header(s) may be regular
    expressions, case-sensitive strings, or else an asterisk.
    Default : '*', allow all headers
:type allow_headers: list, string or regex
:param supports_credentials:
    Allows users to make authenticated requests. If true, injects the
    `Access-Control-Allow-Credentials` header in responses. This allows
    cookies and credentials to be submitted across domains.
    :note: This option cannot be used in conjuction with a '*' origin
    Default : False
:type supports_credentials: bool
:param max_age:
    The maximum time for which this CORS request maybe cached. This value
    is set as the `Access-Control-Max-Age` header.
    Default : None
:type max_age: timedelta, integer, string or None
:param send_wildcard: If True, and the origins parameter is `*`, a wildcard
    `Access-Control-Allow-Origin` header is sent, rather than the
    request's `Origin` header.
    Default : False
:type send_wildcard: bool
:param vary_header:
    If True, the header Vary: Origin will be returned as per the W3
    implementation guidelines.
    Setting this header when the `Access-Control-Allow-Origin` is
    dynamically generated (e.g. when there is more than one allowed
    origin, and an Origin than '*' is returned) informs CDNs and other
    caches that the CORS headers are dynamic, and cannot be cached.
    If False, the Vary header will never be injected or altered.
    Default : True
:type vary_header: bool
:param automatic_options:
    Only applies to the `cross_origin` decorator. If True, Flask-CORS will
    override Flask's default OPTIONS handling to return CORS headers for
    OPTIONS requests.
    Default : True
:type automatic_options: bool
References pycparser.ply.cpp.f, flask_cors.core.get_cors_options(), flask.helpers.make_response(), py._builtin.set, and flask_cors.core.set_cors_headers().
Variable Documentation
LOG
flask_cors.decorator.LOG = logging.getLogger(__name__)