Vaccine Dashboard: attr._funcs Namespace Reference
attr._funcs Namespace Reference
Functions
def asdict (inst, recurse=True, filter=None, dict_factory=dict, retain_collection_types=False, value_serializer=None)
def astuple (inst, recurse=True, filter=None, tuple_factory=tuple, retain_collection_types=False)
def has (cls)
def assoc (inst, **changes)
def evolve (inst, **changes)
def resolve_types (cls, globalns=None, localns=None, attribs=None)
Function Documentation
asdict()
def attr._funcs.asdict (inst, recurse = True, filter = None, dict_factory = dict, retain_collection_types = False, value_serializer = None)
Return the ``attrs`` attribute values of *inst* as a dict.
Optionally recurse into other ``attrs``-decorated classes.
:param inst: Instance of an ``attrs``-decorated class.
:param bool recurse: Recurse into classes that are also
    ``attrs``-decorated.
:param callable filter: A callable whose return code determines whether an
    attribute or element is included (``True``) or dropped (``False``).  Is
    called with the `attr.Attribute` as the first argument and the
    value as the second argument.
:param callable dict_factory: A callable to produce dictionaries from.  For
    example, to produce ordered dictionaries instead of normal Python
    dictionaries, pass in ``collections.OrderedDict``.
:param bool retain_collection_types: Do not convert to ``list`` when
    encountering an attribute whose type is ``tuple`` or ``set``.  Only
    meaningful if ``recurse`` is ``True``.
:param Optional[callable] value_serializer: A hook that is called for every
    attribute or dict key/value.  It receives the current instance, field
    and value and must return the (updated) value.  The hook is run *after*
    the optional *filter* has been applied.
:rtype: return type of *dict_factory*
:raise attr.exceptions.NotAnAttrsClassError: If *cls* is not an ``attrs``
    class.
..  versionadded:: 16.0.0 *dict_factory*
..  versionadded:: 16.1.0 *retain_collection_types*
..  versionadded:: 20.3.0 *value_serializer*
References attr._make.fields(), pip._vendor.distlib.compat.filter, attr._funcs.has(), and pip._vendor.chardet.compat.iteritems.
assoc()
def attr._funcs.assoc (inst, ** changes)
Copy *inst* and apply *changes*.
:param inst: Instance of a class with ``attrs`` attributes.
:param changes: Keyword changes in the new copy.
:return: A copy of inst with *changes* incorporated.
:raise attr.exceptions.AttrsAttributeNotFoundError: If *attr_name* couldn't
    be found on *cls*.
:raise attr.exceptions.NotAnAttrsClassError: If *cls* is not an ``attrs``
    class.
..  deprecated:: 17.1.0
    Use `evolve` instead.
References attr._make.fields(), and pip._vendor.chardet.compat.iteritems.
astuple()
def attr._funcs.astuple (inst, recurse = True, filter = None, tuple_factory = tuple, retain_collection_types = False)
Return the ``attrs`` attribute values of *inst* as a tuple.
Optionally recurse into other ``attrs``-decorated classes.
:param inst: Instance of an ``attrs``-decorated class.
:param bool recurse: Recurse into classes that are also
    ``attrs``-decorated.
:param callable filter: A callable whose return code determines whether an
    attribute or element is included (``True``) or dropped (``False``).  Is
    called with the `attr.Attribute` as the first argument and the
    value as the second argument.
:param callable tuple_factory: A callable to produce tuples from.  For
    example, to produce lists instead of tuples.
:param bool retain_collection_types: Do not convert to ``list``
    or ``dict`` when encountering an attribute which type is
    ``tuple``, ``dict`` or ``set``.  Only meaningful if ``recurse`` is
    ``True``.
:rtype: return type of *tuple_factory*
:raise attr.exceptions.NotAnAttrsClassError: If *cls* is not an ``attrs``
    class.
..  versionadded:: 16.2.0
References attr._make.fields(), pip._vendor.distlib.compat.filter, attr._funcs.has(), and pip._vendor.chardet.compat.iteritems.
evolve()
def attr._funcs.evolve (inst, ** changes)
Create a new instance, based on *inst* with *changes* applied.
:param inst: Instance of a class with ``attrs`` attributes.
:param changes: Keyword changes in the new copy.
:return: A copy of inst with *changes* incorporated.
:raise TypeError: If *attr_name* couldn't be found in the class
    ``__init__``.
:raise attr.exceptions.NotAnAttrsClassError: If *cls* is not an ``attrs``
    class.
..  versionadded:: 17.1.0
References attr._make.fields().
has()
def attr._funcs.has (cls)
Check whether *cls* is a class with ``attrs`` attributes.
:param type cls: Class to introspect.
:raise TypeError: If *cls* is not a class.
:rtype: bool
resolve_types()
def attr._funcs.resolve_types (cls, globalns = None, localns = None, attribs = None)
Resolve any strings and forward annotations in type annotations.
This is only required if you need concrete types in `Attribute`'s *type*
field. In other words, you don't need to resolve your types if you only
use them for static type checking.
With no arguments, names will be looked up in the module in which the class
was created. If this is not what you want, e.g. if the name only exists
inside a method, you may pass *globalns* or *localns* to specify other
dictionaries in which to look up these names. See the docs of
`typing.get_type_hints` for more details.
:param type cls: Class to resolve.
:param Optional[dict] globalns: Dictionary containing global variables.
:param Optional[dict] localns: Dictionary containing local variables.
:param Optional[list] attribs: List of attribs for the given class.
    This is necessary when calling from inside a ``field_transformer``
    since *cls* is not an ``attrs`` class yet.
:raise TypeError: If *cls* is not a class.
:raise attr.exceptions.NotAnAttrsClassError: If *cls* is not an ``attrs``
    class and you didn't pass any attribs.
:raise NameError: If types cannot be resolved because of missing variables.
:returns: *cls* so you can use this function also as a class decorator.
    Please note that you have to apply it **after** `attr.s`. That means
    the decorator has to come in the line **before** `attr.s`.
..  versionadded:: 20.1.0
..  versionadded:: 21.1.0 *attribs*
References attr._make.fields().