Vaccine Dashboard: flask.cli Namespace Reference
flask.cli Namespace Reference
Classes
class NoAppException
class DispatchingApp
class ScriptInfo
class AppGroup
class FlaskGroup
class CertParamType
class SeparatedPathType
Functions
def find_best_app (script_info, module)
def call_factory (script_info, app_factory, args=None, kwargs=None)
def find_app_by_string (script_info, module, app_name)
def prepare_import (path)
def locate_app (script_info, module_name, app_name, raise_if_not_found=True)
def get_version (ctx, param, value)
def with_appcontext (f)
def load_dotenv (path=None)
def show_server_banner (env, debug, app_import_path, eager_loading)
def run_command (info, host, port, reload, debugger, eager_loading, with_threads, cert, extra_files)
None shell_command ()
None routes_command (str sort, bool all_methods)
None main ()
Variables
dotenv = None
ssl = None
version_option
pass_script_info = click.make_pass_decorator(ScriptInfo, ensure=True)
cli
Function Documentation
call_factory()
def flask.cli.call_factory (script_info, app_factory, args = None, kwargs = None)
Takes an app factory, a ``script_info` object and  optionally a tuple
of arguments. Checks for the existence of a script_info argument and calls
the app_factory depending on that and the arguments provided.
References pip._vendor.six.next.
find_app_by_string()
def flask.cli.find_app_by_string (script_info, module, app_name)
Check if the given string is a variable name or a function. Call
a function to get the app instance, or return the variable directly.
References flask.cli.call_factory().
find_best_app()
def flask.cli.find_best_app (script_info, module)
Given a module instance this tries to find the best possible
application in the module or raises an exception.
get_version()
def flask.cli.get_version (ctx, param, value)
load_dotenv()
def flask.cli.load_dotenv (path = None)
Load "dotenv" files in order of precedence to set environment variables.
If an env var is already set it is not overwritten, so earlier files in the
list are preferred over later files.
This is a no-op if `python-dotenv`_ is not installed.
.. _python-dotenv: https://github.com/theskumar/python-dotenv#readme
:param path: Load the file at this location instead of searching.
:return: ``True`` if a file was loaded.
.. versionchanged:: 1.1.0
    Returns ``False`` when python-dotenv is not installed, or when
    the given path isn't a file.
.. versionchanged:: 2.0
    When loading the env files, set the default encoding to UTF-8.
.. versionadded:: 1.0
locate_app()
def flask.cli.locate_app (script_info, module_name, app_name, raise_if_not_found = True)
References flask.cli.find_app_by_string(), and flask.cli.find_best_app().
main()
None flask.cli.main ()
prepare_import()
def flask.cli.prepare_import (path)
Given a filename this will try to calculate the python path, add it
to the search path and return the actual module name that is expected.
routes_command()
None flask.cli.routes_command (str sort, bool all_methods)
Show all registered routes with endpoints and methods.
References flask.cli.main().
run_command()
def flask.cli.run_command (info, host, port, reload, debugger, eager_loading, with_threads, cert, extra_files)
Run a local development server.
This server is for development purposes only. It does not provide
the stability, security, or performance of production WSGI servers.
The reloader and debugger are enabled by default if
FLASK_ENV=development or FLASK_DEBUG=1.
References cffi.ffiplatform.compile(), pip._vendor.distlib._backport.tarfile.open, and flask.cli.shell_command().
shell_command()
None flask.cli.shell_command ()
Run an interactive Python shell in the context of a given
Flask application.  The application will populate the default
namespace of this shell according to its configuration.
This is useful for executing small snippets of management code
without having to manually configure the application.
References dotenv.cli.list(), flask.cli.routes_command(), dotenv.cli.set(), and py._builtin.sorted.
show_server_banner()
def flask.cli.show_server_banner (env, debug, app_import_path, eager_loading)
Show extra startup messages the first time the server is run,
ignoring the reloader.
with_appcontext()
def flask.cli.with_appcontext (f)
Wraps a callback so that it's guaranteed to be executed with the
script's application context.  If callbacks are registered directly
to the ``app.cli`` object then they are wrapped with this function
by default unless it's disabled.
Variable Documentation
cli
flask.cli.cli
Initial value:
 =  FlaskGroup(
     help=.format(
         cmd="export" if os.name == "posix" else "set",
         prefix="$ " if os.name == "posix" else "> ",
     )
 )
dotenv
flask.cli.dotenv = None
pass_script_info
flask.cli.pass_script_info = click.make_pass_decorator(ScriptInfo, ensure=True)
ssl
flask.cli.ssl = None
version_option
flask.cli.version_option
Initial value:
 =  click.Option(
     ["--version"],
     help="Show the flask version",
     expose_value=False,
     callback=get_version,
     is_flag=True,
     is_eager=True,
 )