Vaccine Dashboard: dotenv.parser Namespace Reference
dotenv.parser Namespace Reference
Classes
class Position
class Error
class Reader
Functions
Pattern[str] make_regex (str string, int extra_flags=0)
str decode_escapes (Pattern[str] regex, str string)
Optional[str] parse_key (Reader reader)
str parse_unquoted_value (Reader reader)
str parse_value (Reader reader)
Binding parse_binding (Reader reader)
Iterator[Binding] parse_stream (IO[str] stream)
Variables
extra_flags
Original
Binding
Function Documentation
decode_escapes()
str dotenv.parser.decode_escapes (Pattern[str] regex, str string)
make_regex()
Pattern[str] dotenv.parser.make_regex (str string, int extra_flags = 0)
parse_binding()
Binding dotenv.parser.parse_binding (Reader reader)
References dotenv.parser.Binding, dotenv.parser.parse_key(), and dotenv.parser.parse_value().
parse_key()
Optional[str] dotenv.parser.parse_key (Reader reader)
parse_stream()
Iterator[Binding] dotenv.parser.parse_stream (IO[str] stream)
References dotenv.parser.parse_binding().
parse_unquoted_value()
str dotenv.parser.parse_unquoted_value (Reader reader)
parse_value()
str dotenv.parser.parse_value (Reader reader)
References dotenv.parser.decode_escapes(), and dotenv.parser.parse_unquoted_value().
Variable Documentation
Binding
dotenv.parser.Binding
extra_flags
dotenv.parser.extra_flags
Original
dotenv.parser.Original