Vaccine Dashboard: pip._internal.operations.build.wheel_legacy Namespace Reference
pip._internal.operations.build.wheel_legacy Namespace Reference
Functions
def format_command_result (command_args, command_output)
def get_legacy_build_wheel_path (names, temp_dir, name, command_args, command_output)
def build_wheel_legacy (name, setup_py_path, source_dir, global_options, build_options, tempd)
Variables
logger = logging.getLogger(__name__)
Function Documentation
build_wheel_legacy()
def pip._internal.operations.build.wheel_legacy.build_wheel_legacy (name, setup_py_path, source_dir, global_options, build_options, tempd)
Build one unpacked package using the "legacy" build process.
Returns path to wheel if successfully built. Otherwise, returns None.
References pip._internal.utils.subprocess.call_subprocess(), pip._internal.operations.build.wheel_legacy.get_legacy_build_wheel_path(), pip._internal.utils.setuptools_build.make_setuptools_bdist_wheel_args(), and pip._internal.cli.spinners.open_spinner().
format_command_result()
def pip._internal.operations.build.wheel_legacy.format_command_result (command_args, command_output)
Format command information for logging.
References pip._internal.utils.subprocess.format_command_args().
get_legacy_build_wheel_path()
def pip._internal.operations.build.wheel_legacy.get_legacy_build_wheel_path (names, temp_dir, name, command_args, command_output)
Return the path to the wheel in the temporary build directory.
References pip._internal.operations.build.wheel_legacy.format_command_result(), and py._builtin.sorted.
Variable Documentation
logger
pip._internal.operations.build.wheel_legacy.logger = logging.getLogger(__name__)