Vaccine Dashboard: jinja2.utils Namespace Reference
jinja2.utils Namespace Reference
Classes
class _PassArg
class LRUCache
class Cycler
class Joiner
class Namespace
class Markup
Functions
F pass_context (F f)
F pass_eval_context (F f)
F pass_environment (F f)
F contextfunction (F f)
F evalcontextfunction (F f)
F environmentfunction (F f)
F internalcode (F f)
bool is_undefined (t.Any obj)
None consume (t.Iterable[t.Any] iterable)
None clear_caches ()
t.Any import_string (str import_name, bool silent=False)
t.Optional[t.IO] open_if_exists (str filename, str mode="rb")
str object_type_repr (t.Any obj)
str pformat (t.Any obj)
str urlize (str text, t.Optional[int] trim_url_limit=None, t.Optional[str] rel=None, t.Optional[str] target=None, t.Optional[t.Iterable[str]] extra_schemes=None)
str generate_lorem_ipsum (int n=5, bool html=True, int min=20, int max=100)
str url_quote (t.Any obj, str charset="utf-8", bool for_qs=False)
str unicode_urlencode (t.Any obj, str charset="utf-8", bool for_qs=False)
t.Callable[[t.Optional[str]], bool] select_autoescape (t.Collection[str] enabled_extensions=("html", "htm", "xml"), t.Collection[str] disabled_extensions=(), bool default_for_string=True, bool default=False)
markupsafe.Markup htmlsafe_json_dumps (t.Any obj, t.Optional[t.Callable[..., str]] dumps=None, **t.Any kwargs)
str escape (t.Any s)
Variables
F = t.TypeVar("F", bound=t.Callable[..., t.Any])
Any
string concat = "".join
Function Documentation
clear_caches()
None jinja2.utils.clear_caches ()
Jinja keeps internal caches for environments and lexers.  These are
used so that Jinja doesn't have to recreate environments and lexers all
the time.  Normally you don't have to care about that but if you are
measuring memory consumption you may want to clean the caches.
consume()
None jinja2.utils.consume (t.Iterable[t.Any] iterable)
Consumes an iterable without doing anything with it.
contextfunction()
F jinja2.utils.contextfunction (F f)
Pass the context as the first argument to the decorated function.
.. deprecated:: 3.0
    Will be removed in Jinja 3.1. Use :func:`~jinja2.pass_context`
    instead.
References jinja2.utils.pass_context().
environmentfunction()
F jinja2.utils.environmentfunction (F f)
Pass the environment as the first argument to the decorated
function.
.. deprecated:: 3.0
    Will be removed in Jinja 3.1. Use
    :func:`~jinja2.pass_environment` instead.
References jinja2.utils.pass_environment().
escape()
str jinja2.utils.escape (t.Any s)
evalcontextfunction()
F jinja2.utils.evalcontextfunction (F f)
Pass the eval context as the first argument to the decorated
function.
.. deprecated:: 3.0
    Will be removed in Jinja 3.1. Use
    :func:`~jinja2.pass_eval_context` instead.
.. versionadded:: 2.4
References jinja2.utils.pass_eval_context().
generate_lorem_ipsum()
str jinja2.utils.generate_lorem_ipsum (int n = 5, bool html = True, int min = 20, int max = 100)
Generate some lorem ipsum for the template.
References py._builtin.enumerate, and pip._vendor.pyparsing.range.
htmlsafe_json_dumps()
markupsafe.Markup jinja2.utils.htmlsafe_json_dumps (t.Any obj, t.Optional[t.Callable[..., str]] dumps = None, **t.Any kwargs)
Serialize an object to a string of JSON with :func:`json.dumps`,
then replace HTML-unsafe characters with Unicode escapes and mark
the result safe with :class:`~markupsafe.Markup`.
This is available in templates as the ``|tojson`` filter.
The following characters are escaped: ``<``, ``>``, ``&``, ``'``.
The returned string is safe to render in HTML documents and
``<script>`` tags. The exception is in HTML attributes that are
double quoted; either use single quotes or the ``|forceescape``
filter.
:param obj: The object to serialize to JSON.
:param dumps: The ``dumps`` function to use. Defaults to
    ``env.policies["json.dumps_function"]``, which defaults to
    :func:`json.dumps`.
:param kwargs: Extra arguments to pass to ``dumps``. Merged onto
    ``env.policies["json.dumps_kwargs"]``.
.. versionchanged:: 3.0
    The ``dumper`` parameter is renamed to ``dumps``.
.. versionadded:: 2.9
References pip._vendor.msgpack.dumps, and pip._internal.utils.filesystem.replace.
import_string()
t.Any jinja2.utils.import_string (str import_name, bool silent = False)
Imports an object based on a string.  This is useful if you want to
use import paths as endpoints or something similar.  An import path can
be specified either in dotted notation (``xml.sax.saxutils.escape``)
or with a colon as object delimiter (``xml.sax.saxutils:escape``).
If the `silent` is True the return value will be `None` if the import
fails.
:return: imported object
internalcode()
F jinja2.utils.internalcode (F f)
Marks the function as internally used
is_undefined()
bool jinja2.utils.is_undefined (t.Any obj)
Check if the object passed is undefined.  This does nothing more than
performing an instance check against :class:`Undefined` but looks nicer.
This can be used for custom filters or tests that want to react to
undefined variables.  For example a custom default filter can look like
this::
    def default(var, default=''):
        if is_undefined(var):
            return default
        return var
object_type_repr()
str jinja2.utils.object_type_repr (t.Any obj)
Returns the name of the object's type.  For some recognized
singletons the name of the object is returned instead. (For
example for `None` and `Ellipsis`).
References dotenv.cli.type.
open_if_exists()
t.Optional[t.IO] jinja2.utils.open_if_exists (str filename, str mode = "rb")
Returns a file descriptor for the filename if that file exists,
otherwise ``None``.
References pip._vendor.distlib._backport.tarfile.open.
pass_context()
F jinja2.utils.pass_context (F f)
Pass the :class:`~jinja2.runtime.Context` as the first argument
to the decorated function when called while rendering a template.
Can be used on functions, filters, and tests.
If only ``Context.eval_context`` is needed, use
:func:`pass_eval_context`. If only ``Context.environment`` is
needed, use :func:`pass_environment`.
.. versionadded:: 3.0.0
    Replaces ``contextfunction`` and ``contextfilter``.
pass_environment()
F jinja2.utils.pass_environment (F f)
Pass the :class:`~jinja2.Environment` as the first argument to
the decorated function when called while rendering a template.
Can be used on functions, filters, and tests.
.. versionadded:: 3.0.0
    Replaces ``environmentfunction`` and ``environmentfilter``.
pass_eval_context()
F jinja2.utils.pass_eval_context (F f)
Pass the :class:`~jinja2.nodes.EvalContext` as the first argument
to the decorated function when called while rendering a template.
See :ref:`eval-context`.
Can be used on functions, filters, and tests.
If only ``EvalContext.environment`` is needed, use
:func:`pass_environment`.
.. versionadded:: 3.0.0
    Replaces ``evalcontextfunction`` and ``evalcontextfilter``.
pformat()
str jinja2.utils.pformat (t.Any obj)
Format an object using :func:`pprint.pformat`.
select_autoescape()
t.Callable[[t.Optional[str]], bool] jinja2.utils.select_autoescape (t.Collection[str] enabled_extensions = ("html", "htm", "xml"), t.Collection[str] disabled_extensions = (), bool default_for_string = True, bool default = False)
Intelligently sets the initial value of autoescaping based on the
filename of the template.  This is the recommended way to configure
autoescaping if you do not want to write a custom function yourself.
If you want to enable it for all templates created from strings or
for all templates with `.html` and `.xml` extensions::
    from jinja2 import Environment, select_autoescape
    env = Environment(autoescape=select_autoescape(
        enabled_extensions=('html', 'xml'),
        default_for_string=True,
    ))
Example configuration to turn it on at all times except if the template
ends with `.txt`::
    from jinja2 import Environment, select_autoescape
    env = Environment(autoescape=select_autoescape(
        disabled_extensions=('txt',),
        default_for_string=True,
        default=True,
    ))
The `enabled_extensions` is an iterable of all the extensions that
autoescaping should be enabled for.  Likewise `disabled_extensions` is
a list of all templates it should be disabled for.  If a template is
loaded from a string then the default from `default_for_string` is used.
If nothing matches then the initial value of autoescaping is set to the
value of `default`.
For security reasons this function operates case insensitive.
.. versionadded:: 2.9
References jinja2.ext.autoescape.
unicode_urlencode()
str jinja2.utils.unicode_urlencode (t.Any obj, str charset = "utf-8", bool for_qs = False)
References jinja2.utils.url_quote().
url_quote()
str jinja2.utils.url_quote (t.Any obj, str charset = "utf-8", bool for_qs = False)
Quote a string for use in a URL using the given charset.
:param obj: String or bytes to quote. Other types are converted to
    string then encoded to bytes using the given charset.
:param charset: Encode text to bytes using this charset.
:param for_qs: Quote "/" and use "+" for spaces.
References pip._vendor.requests.compat.str.
urlize()
str jinja2.utils.urlize (str text, t.Optional[int] trim_url_limit = None, t.Optional[str] rel = None, t.Optional[str] target = None, t.Optional[t.Iterable[str]] extra_schemes = None)
Convert URLs in text into clickable links.
This may not recognize links in some situations. Usually, a more
comprehensive formatter, such as a Markdown library, is a better
choice.
Works on ``http://``, ``https://``, ``www.``, ``mailto:``, and email
addresses. Links with trailing punctuation (periods, commas, closing
parentheses) and leading punctuation (opening parentheses) are
recognized excluding the punctuation. Email addresses that include
header fields are not recognized (for example,
``mailto:address@example.com?cc=copy@example.com``).
:param text: Original text containing URLs to link.
:param trim_url_limit: Shorten displayed URL values to this length.
:param target: Add the ``target`` attribute to links.
:param rel: Add the ``rel`` attribute to links.
:param extra_schemes: Recognize URLs that start with these schemes
    in addition to the default behavior.
.. versionchanged:: 3.0
    The ``extra_schemes`` parameter was added.
.. versionchanged:: 3.0
    Generate ``https://`` links for URLs without a scheme.
.. versionchanged:: 3.0
    The parsing rules were updated. Recognize email addresses with
    or without the ``mailto:`` scheme. Validate IP addresses. Ignore
    parentheses and brackets in more cases.
References py._builtin.enumerate, pip._vendor.pyparsing.range, and pip._vendor.requests.compat.str.
Variable Documentation
Any
jinja2.utils.Any
concat
string jinja2.utils.concat = "".join
F
jinja2.utils.F = t.TypeVar("F", bound=t.Callable[..., t.Any])