Vaccine Dashboard: itsdangerous.jws.TimedJSONWebSignatureSerializer Class Reference
itsdangerous.jws.TimedJSONWebSignatureSerializer Class Reference
Public Member Functions
def __init__ (self, secret_key, expires_in=None, **kwargs)
def make_header (self, header_fields)
def loads (self, s, salt=None, return_header=False)
def get_issue_date (self, header)
def now (self)
Public Member Functions inherited from itsdangerous.jws.JSONWebSignatureSerializer
def __init__ (self, secret_key, salt=None, serializer=None, serializer_kwargs=None, signer=None, signer_kwargs=None, algorithm_name=None)
def load_payload (self, payload, serializer=None, return_header=False)
def dump_payload (self, header, obj)
def make_algorithm (self, algorithm_name)
def make_signer (self, salt=None, algorithm=None)
def dumps (self, obj, salt=None, header_fields=None)
def loads_unsafe (self, s, salt=None, return_header=False)
Public Member Functions inherited from itsdangerous.serializer.Serializer
def __init__ (self, _t_secret_key secret_key, _t_opt_str_bytes salt=b"itsdangerous", _t.Any serializer=None, _t_opt_kwargs serializer_kwargs=None, _t.Optional[_t_signer] signer=None, _t_opt_kwargs signer_kwargs=None, _t.Optional[_t_fallbacks] fallback_signers=None)
bytes secret_key (self)
_t.Any load_payload (self, bytes payload, _t.Optional[_t.Any] serializer=None)
bytes dump_payload (self, _t.Any obj)
Signer make_signer (self, _t_opt_str_bytes salt=None)
_t.Iterator[Signer] iter_unsigners (self, _t_opt_str_bytes salt=None)
_t_str_bytes dumps (self, _t.Any obj, _t_opt_str_bytes salt=None)
None dump (self, _t.Any obj, _t.IO f, _t_opt_str_bytes salt=None)
_t.Any loads (self, _t_str_bytes s, _t_opt_str_bytes salt=None, **_t.Any kwargs)
_t.Any load (self, _t.IO f, _t_opt_str_bytes salt=None)
_t_load_unsafe loads_unsafe (self, _t_str_bytes s, _t_opt_str_bytes salt=None)
_t_load_unsafe load_unsafe (self, _t.IO f, _t_opt_str_bytes salt=None)
Public Attributes
expires_in
Public Attributes inherited from itsdangerous.jws.JSONWebSignatureSerializer
algorithm_name
algorithm
Public Attributes inherited from itsdangerous.serializer.Serializer
salt
Static Public Attributes
int DEFAULT_EXPIRES_IN = 3600
Static Public Attributes inherited from itsdangerous.jws.JSONWebSignatureSerializer
dictionary jws_algorithms
string default_algorithm = "HS512"
default_serializer = _CompactJSON
Static Public Attributes inherited from itsdangerous.serializer.Serializer
Any
Detailed Description
Works like the regular :class:`JSONWebSignatureSerializer` but
also records the time of the signing and can be used to expire
signatures.
JWS currently does not specify this behavior but it mentions a
possible extension like this in the spec. Expiry date is encoded
into the header similar to what's specified in `draft-ietf-oauth
-json-web-token <http://self-issued.info/docs/draft-ietf-oauth-json
-web-token.html#expDef>`_.
Constructor & Destructor Documentation
__init__()
def itsdangerous.jws.TimedJSONWebSignatureSerializer.__init__ (self, secret_key, expires_in = None, ** kwargs)
References itsdangerous.jws.TimedJSONWebSignatureSerializer.DEFAULT_EXPIRES_IN.
Member Function Documentation
get_issue_date()
def itsdangerous.jws.TimedJSONWebSignatureSerializer.get_issue_date (self, header)
If the header contains the ``iat`` field, return the date the
signature was issued, as a timezone-aware
:class:`datetime.datetime` in UTC.
.. versionchanged:: 2.0
    The timestamp is returned as a timezone-aware ``datetime``
    in UTC rather than a naive ``datetime`` assumed to be UTC.
loads()
def itsdangerous.jws.TimedJSONWebSignatureSerializer.loads (self, s, salt = None, return_header = False)
Reverse of :meth:`dumps`. If requested via ``return_header``
it will return a tuple of payload and header.
Reimplemented from itsdangerous.jws.JSONWebSignatureSerializer.
References itsdangerous.jws.TimedJSONWebSignatureSerializer.get_issue_date(), and itsdangerous.jws.TimedJSONWebSignatureSerializer.now().
make_header()
def itsdangerous.jws.TimedJSONWebSignatureSerializer.make_header (self, header_fields)
Reimplemented from itsdangerous.jws.JSONWebSignatureSerializer.
References itsdangerous.jws.TimedJSONWebSignatureSerializer.expires_in, and itsdangerous.jws.TimedJSONWebSignatureSerializer.now().
now()
def itsdangerous.jws.TimedJSONWebSignatureSerializer.now (self)
Member Data Documentation
DEFAULT_EXPIRES_IN
int itsdangerous.jws.TimedJSONWebSignatureSerializer.DEFAULT_EXPIRES_IN = 3600 static
expires_in
itsdangerous.jws.TimedJSONWebSignatureSerializer.expires_in
The documentation for this class was generated from the following file:
back-end/flaskenv/Lib/site-packages/itsdangerous/jws.py