Vaccine Dashboard: importlib_metadata._text.FoldedCase Class Reference
importlib_metadata._text.FoldedCase Class Reference
Public Member Functions
def __lt__ (self, other)
def __gt__ (self, other)
def __eq__ (self, other)
def __ne__ (self, other)
def __hash__ (self)
def __contains__ (self, other)
def in_ (self, other)
def lower (self)
def index (self, sub)
def split (self, splitter=' ', maxsplit=0)
Detailed Description
A case insensitive string class; behaves just like str
except compares equal when the only variation is case.
>>> s = FoldedCase('hello world')
>>> s == 'Hello World'
True
>>> 'Hello World' == s
True
>>> s != 'Hello World'
False
>>> s.index('O')
4
>>> s.split('O')
['hell', ' w', 'rld']
>>> sorted(map(FoldedCase, ['GAMMA', 'alpha', 'Beta']))
['alpha', 'Beta', 'GAMMA']
Sequence membership is straightforward.
>>> "Hello World" in [s]
True
>>> s in ["Hello World"]
True
You may test for set inclusion, but candidate and elements
must both be folded.
>>> FoldedCase("Hello World") in {s}
True
>>> s in {FoldedCase("Hello World")}
True
String inclusion works as long as the FoldedCase object
is on the right.
>>> "hello" in FoldedCase("Hello World")
True
But not if the FoldedCase object is on the left:
>>> FoldedCase('hello') in 'Hello World'
False
In that case, use in_:
>>> FoldedCase('hello').in_('Hello World')
True
>>> FoldedCase('hello') > FoldedCase('Hello')
False
Member Function Documentation
__contains__()
def importlib_metadata._text.FoldedCase.__contains__ (self, other)
References importlib_metadata._text.FoldedCase.lower().
__eq__()
def importlib_metadata._text.FoldedCase.__eq__ (self, other)
References importlib_metadata._text.FoldedCase.lower().
__gt__()
def importlib_metadata._text.FoldedCase.__gt__ (self, other)
References importlib_metadata._text.FoldedCase.lower().
__hash__()
def importlib_metadata._text.FoldedCase.__hash__ (self)
References importlib_metadata._text.FoldedCase.lower().
__lt__()
def importlib_metadata._text.FoldedCase.__lt__ (self, other)
References importlib_metadata._text.FoldedCase.lower().
__ne__()
def importlib_metadata._text.FoldedCase.__ne__ (self, other)
References importlib_metadata._text.FoldedCase.lower().
in_()
def importlib_metadata._text.FoldedCase.in_ (self, other)
index()
def importlib_metadata._text.FoldedCase.index (self, sub)
References importlib_metadata._text.FoldedCase.lower().
lower()
def importlib_metadata._text.FoldedCase.lower (self)
split()
def importlib_metadata._text.FoldedCase.split (self, splitter = ' ', maxsplit = 0)
The documentation for this class was generated from the following file:
back-end/flaskenv/Lib/site-packages/importlib_metadata/_text.py