Vaccine Dashboard: werkzeug.datastructures.ImmutableHeadersMixin Class Reference
werkzeug.datastructures.ImmutableHeadersMixin Class Reference
Public Member Functions
def __delitem__ (self, key, **kwargs)
def __setitem__ (self, key, value)
def set (self, _key, _value, **kw)
def setlist (self, key, values)
def add (self, _key, _value, **kw)
def add_header (self, _key, _value, **_kw)
def remove (self, key)
def extend (self, *args, **kwargs)
def update (self, *args, **kwargs)
def insert (self, pos, value)
def pop (self, key=None, default=_missing)
def popitem (self)
def setdefault (self, key, default)
def setlistdefault (self, key, default)
Detailed Description
Makes a :class:`Headers` immutable.  We do not mark them as
hashable though since the only usecase for this datastructure
in Werkzeug is a view on a mutable structure.
.. versionadded:: 0.5
:private:
Member Function Documentation
__delitem__()
def werkzeug.datastructures.ImmutableHeadersMixin.__delitem__ (self, key, ** kwargs)
References werkzeug.datastructures.is_immutable().
__setitem__()
def werkzeug.datastructures.ImmutableHeadersMixin.__setitem__ (self, key, value)
References werkzeug.datastructures.is_immutable().
add()
def werkzeug.datastructures.ImmutableHeadersMixin.add (self, _key, _value, ** kw)
References werkzeug.datastructures.is_immutable().
add_header()
def werkzeug.datastructures.ImmutableHeadersMixin.add_header (self, _key, _value, ** _kw)
References werkzeug.datastructures.is_immutable().
extend()
def werkzeug.datastructures.ImmutableHeadersMixin.extend (self, * args, ** kwargs)
References werkzeug.datastructures.is_immutable().
insert()
def werkzeug.datastructures.ImmutableHeadersMixin.insert (self, pos, value)
References werkzeug.datastructures.is_immutable().
pop()
def werkzeug.datastructures.ImmutableHeadersMixin.pop (self, key = None, default = _missing)
References werkzeug.datastructures.is_immutable().
popitem()
def werkzeug.datastructures.ImmutableHeadersMixin.popitem (self)
References werkzeug.datastructures.is_immutable().
remove()
def werkzeug.datastructures.ImmutableHeadersMixin.remove (self, key)
References werkzeug.datastructures.is_immutable().
set()
def werkzeug.datastructures.ImmutableHeadersMixin.set (self, _key, _value, ** kw)
References werkzeug.datastructures.is_immutable().
setdefault()
def werkzeug.datastructures.ImmutableHeadersMixin.setdefault (self, key, default)
References werkzeug.datastructures.is_immutable().
setlist()
def werkzeug.datastructures.ImmutableHeadersMixin.setlist (self, key, values)
References werkzeug.datastructures.is_immutable().
setlistdefault()
def werkzeug.datastructures.ImmutableHeadersMixin.setlistdefault (self, key, default)
References werkzeug.datastructures.is_immutable().
update()
def werkzeug.datastructures.ImmutableHeadersMixin.update (self, * args, ** kwargs)
References werkzeug.datastructures.is_immutable().
The documentation for this class was generated from the following file:
back-end/flaskenv/Lib/site-packages/werkzeug/datastructures.py