Vaccine Dashboard: werkzeug.wsgi Namespace Reference
werkzeug.wsgi Namespace Reference
Classes
class ClosingIterator
class FileWrapper
class _RangeWrapper
class LimitedStream
Functions
"WSGIApplication" responder (t.Callable[..., "WSGIApplication"] f)
str get_current_url ("WSGIEnvironment" environ, bool root_only=False, bool strip_querystring=False, bool host_only=False, t.Optional[t.Iterable[str]] trusted_hosts=None)
str get_host ("WSGIEnvironment" environ, t.Optional[t.Iterable[str]] trusted_hosts=None)
t.Optional[int] get_content_length ("WSGIEnvironment" environ)
t.BinaryIO get_input_stream ("WSGIEnvironment" environ, bool safe_fallback=True)
str get_query_string ("WSGIEnvironment" environ)
str get_path_info ("WSGIEnvironment" environ, str charset="utf-8", str errors="replace")
str get_script_name ("WSGIEnvironment" environ, str charset="utf-8", str errors="replace")
t.Optional[str] pop_path_info ("WSGIEnvironment" environ, str charset="utf-8", str errors="replace")
t.Optional[str] peek_path_info ("WSGIEnvironment" environ, str charset="utf-8", str errors="replace")
t.Optional[str] extract_path_info (t.Union[str, "WSGIEnvironment"] environ_or_baseurl, t.Union[str, _URLTuple] path_or_url, str charset="utf-8", str errors="werkzeug.url_quote", bool collapse_http_schemes=True)
t.Iterable[bytes] wrap_file ("WSGIEnvironment" environ, t.BinaryIO file, int buffer_size=8192)
t.Iterator[bytes] make_line_iter (t.Union[t.Iterable[bytes], t.BinaryIO] stream, t.Optional[int] limit=None, int buffer_size=10 *1024, bool cap_at_buffer=False)
t.Iterator[bytes] make_chunk_iter (t.Union[t.Iterable[bytes], t.BinaryIO] stream, bytes separator, t.Optional[int] limit=None, int buffer_size=10 *1024, bool cap_at_buffer=False)
Function Documentation
extract_path_info()
t.Optional[str] werkzeug.wsgi.extract_path_info (t.Union[str, "WSGIEnvironment"] environ_or_baseurl, t.Union[str, _URLTuple] path_or_url, str charset = "utf-8", str errors = "werkzeug.url_quote", bool collapse_http_schemes = True)
Extracts the path info from the given URL (or WSGI environment) and
path. The path info returned is a string. The URLs might also be IRIs.
If the path info could not be determined, `None` is returned.
Some examples:
>>> extract_path_info('http://example.com/app', '/app/hello')
'/hello'
>>> extract_path_info('http://example.com/app',
...                   'https://example.com/app/hello')
'/hello'
>>> extract_path_info('http://example.com/app',
...                   'https://example.com/app/hello',
...                   collapse_http_schemes=False) is None
True
Instead of providing a base URL you can also pass a WSGI environment.
:param environ_or_baseurl: a WSGI environment dict, a base URL or
                           base IRI.  This is the root of the
                           application.
:param path_or_url: an absolute path from the server root, a
                    relative path (in which case it's the path info)
                    or a full URL.
:param charset: the charset for byte data in URLs
:param errors: the error handling on decode
:param collapse_http_schemes: if set to `False` the algorithm does
                              not assume that http and https on the
                              same server point to the same
                              resource.
.. versionchanged:: 0.15
    The ``errors`` parameter defaults to leaving invalid bytes
    quoted instead of replacing them.
.. versionadded:: 0.6
References werkzeug.wsgi.get_current_url(), werkzeug.urls.uri_to_iri(), werkzeug.urls.url_join(), and werkzeug.urls.url_parse().
get_content_length()
t.Optional[int] werkzeug.wsgi.get_content_length ("WSGIEnvironment" environ)
Returns the content length from the WSGI environment as
integer. If it's not available or chunked transfer encoding is used,
``None`` is returned.
.. versionadded:: 0.9
:param environ: the WSGI environ to fetch the content length from.
get_current_url()
str werkzeug.wsgi.get_current_url ("WSGIEnvironment" environ, bool root_only = False, bool strip_querystring = False, bool host_only = False, t.Optional[t.Iterable[str]] trusted_hosts = None)
Recreate the URL for a request from the parts in a WSGI
environment.
The URL is an IRI, not a URI, so it may contain Unicode characters.
Use :func:`~werkzeug.urls.iri_to_uri` to convert it to ASCII.
:param environ: The WSGI environment to get the URL parts from.
:param root_only: Only build the root path, don't include the
    remaining path or query string.
:param strip_querystring: Don't include the query string.
:param host_only: Only build the scheme and host.
:param trusted_hosts: A list of trusted host names to validate the
    host against.
References jwt.api_jws.encode, and werkzeug.wsgi.get_host().
get_host()
str werkzeug.wsgi.get_host ("WSGIEnvironment" environ, t.Optional[t.Iterable[str]] trusted_hosts = None)
Return the host for the given WSGI environment.
The ``Host`` header is preferred, then ``SERVER_NAME`` if it's not
set. The returned host will only contain the port if it is different
than the standard port for the protocol.
Optionally, verify that the host is trusted using
:func:`host_is_trusted` and raise a
:exc:`~werkzeug.exceptions.SecurityError` if it is not.
:param environ: A WSGI environment dict.
:param trusted_hosts: A list of trusted host names.
:return: Host, with port if necessary.
:raise ~werkzeug.exceptions.SecurityError: If the host is not
    trusted.
get_input_stream()
t.BinaryIO werkzeug.wsgi.get_input_stream ("WSGIEnvironment" environ, bool safe_fallback = True)
Returns the input stream from the WSGI environment and wraps it
in the most sensible way possible. The stream returned is not the
raw WSGI stream in most cases but one that is safe to read from
without taking into account the content length.
If content length is not set, the stream will be empty for safety reasons.
If the WSGI server supports chunked or infinite streams, it should set
the ``wsgi.input_terminated`` value in the WSGI environ to indicate that.
.. versionadded:: 0.9
:param environ: the WSGI environ to fetch the stream from.
:param safe_fallback: use an empty stream as a safe fallback when the
    content length is not set. Disabling this allows infinite streams,
    which can be a denial-of-service risk.
References werkzeug.wsgi.get_content_length().
get_path_info()
str werkzeug.wsgi.get_path_info ("WSGIEnvironment" environ, str charset = "utf-8", str errors = "replace")
Return the ``PATH_INFO`` from the WSGI environment and decode it
unless ``charset`` is ``None``.
:param environ: WSGI environment to get the path from.
:param charset: The charset for the path info, or ``None`` if no
    decoding should be performed.
:param errors: The decoding error handling.
.. versionadded:: 0.9
References jwt.api_jws.encode.
get_query_string()
str werkzeug.wsgi.get_query_string ("WSGIEnvironment" environ)
Returns the ``QUERY_STRING`` from the WSGI environment. This also
takes care of the WSGI decoding dance. The string returned will be
restricted to ASCII characters.
:param environ: WSGI environment to get the query string from.
.. versionadded:: 0.9
References jwt.api_jws.encode, and jinja2.utils.url_quote().
get_script_name()
str werkzeug.wsgi.get_script_name ("WSGIEnvironment" environ, str charset = "utf-8", str errors = "replace")
Return the ``SCRIPT_NAME`` from the WSGI environment and decode
it unless `charset` is set to ``None``.
:param environ: WSGI environment to get the path from.
:param charset: The charset for the path, or ``None`` if no decoding
    should be performed.
:param errors: The decoding error handling.
.. versionadded:: 0.9
References jwt.api_jws.encode.
make_chunk_iter()
t.Iterator[bytes] werkzeug.wsgi.make_chunk_iter (t.Union[t.Iterable[bytes], t.BinaryIO] stream, bytes separator, t.Optional[int] limit = None, int buffer_size = 10 * 1024, bool cap_at_buffer = False)
Works like :func:`make_line_iter` but accepts a separator
which divides chunks.  If you want newline based processing
you should use :func:`make_line_iter` instead as it
supports arbitrary newline markers.
.. versionadded:: 0.8
.. versionadded:: 0.9
   added support for iterators as input stream.
.. versionadded:: 0.11.10
   added support for the `cap_at_buffer` parameter.
:param stream: the stream or iterate to iterate over.
:param separator: the separator that divides chunks.
:param limit: the limit in bytes for the stream.  (Usually
              content length.  Not necessary if the `stream`
              is otherwise already limited).
:param buffer_size: The optional buffer size.
:param cap_at_buffer: if this is set chunks are split if they are longer
                      than the buffer size.  Internally this is implemented
                      that the buffer size might be exhausted by a factor
                      of two however.
References pip._vendor.six.next.
make_line_iter()
t.Iterator[bytes] werkzeug.wsgi.make_line_iter (t.Union[t.Iterable[bytes], t.BinaryIO] stream, t.Optional[int] limit = None, int buffer_size = 10 * 1024, bool cap_at_buffer = False)
Safely iterates line-based over an input stream.  If the input stream
is not a :class:`LimitedStream` the `limit` parameter is mandatory.
This uses the stream's :meth:`~file.read` method internally as opposite
to the :meth:`~file.readline` method that is unsafe and can only be used
in violation of the WSGI specification.  The same problem applies to the
`__iter__` function of the input stream which calls :meth:`~file.readline`
without arguments.
If you need line-by-line processing it's strongly recommended to iterate
over the input stream using this helper function.
.. versionchanged:: 0.8
   This function now ensures that the limit was reached.
.. versionadded:: 0.9
   added support for iterators as input stream.
.. versionadded:: 0.11.10
   added support for the `cap_at_buffer` parameter.
:param stream: the stream or iterate to iterate over.
:param limit: the limit in bytes for the stream.  (Usually
              content length.  Not necessary if the `stream`
              is a :class:`LimitedStream`.
:param buffer_size: The optional buffer size.
:param cap_at_buffer: if this is set chunks are split if they are longer
                      than the buffer size.  Internally this is implemented
                      that the buffer size might be exhausted by a factor
                      of two however.
References pip._vendor.six.next, and attr.s.
peek_path_info()
t.Optional[str] werkzeug.wsgi.peek_path_info ("WSGIEnvironment" environ, str charset = "utf-8", str errors = "replace")
Returns the next segment on the `PATH_INFO` or `None` if there
is none.  Works like :func:`pop_path_info` without modifying the
environment:
>>> env = {'SCRIPT_NAME': '/foo', 'PATH_INFO': '/a/b'}
>>> peek_path_info(env)
'a'
>>> peek_path_info(env)
'a'
If the `charset` is set to `None` bytes are returned.
.. versionadded:: 0.5
.. versionchanged:: 0.9
   The path is now decoded and a charset and encoding
   parameter can be provided.
:param environ: the WSGI environment that is checked.
References jwt.api_jws.encode.
pop_path_info()
t.Optional[str] werkzeug.wsgi.pop_path_info ("WSGIEnvironment" environ, str charset = "utf-8", str errors = "replace")
Removes and returns the next segment of `PATH_INFO`, pushing it onto
`SCRIPT_NAME`.  Returns `None` if there is nothing left on `PATH_INFO`.
If the `charset` is set to `None` bytes are returned.
If there are empty segments (``'/foo//bar``) these are ignored but
properly pushed to the `SCRIPT_NAME`:
>>> env = {'SCRIPT_NAME': '/foo', 'PATH_INFO': '/a/b'}
>>> pop_path_info(env)
'a'
>>> env['SCRIPT_NAME']
'/foo/a'
>>> pop_path_info(env)
'b'
>>> env['SCRIPT_NAME']
'/foo/a/b'
.. versionadded:: 0.5
.. versionchanged:: 0.9
   The path is now decoded and a charset and encoding
   parameter can be provided.
:param environ: the WSGI environment that is modified.
:param charset: The ``encoding`` parameter passed to
    :func:`bytes.decode`.
:param errors: The ``errors`` paramater passed to
    :func:`bytes.decode`.
responder()
"WSGIApplication" werkzeug.wsgi.responder (t.Callable[..., "WSGIApplication"] f)
Marks a function as responder.  Decorate a function with it and it
will automatically call the return value as WSGI application.
Example::
    @responder
    def application(environ, start_response):
        return Response('Hello World!')
References pycparser.ply.cpp.f.
wrap_file()
t.Iterable[bytes] werkzeug.wsgi.wrap_file ("WSGIEnvironment" environ, t.BinaryIO file, int buffer_size = 8192)
Wraps a file.  This uses the WSGI server's file wrapper if available
or otherwise the generic :class:`FileWrapper`.
.. versionadded:: 0.5
If the file wrapper from the WSGI server is used it's important to not
iterate over it from inside the application but to pass it through
unchanged.  If you want to pass out a file wrapper inside a response
object you have to set :attr:`Response.direct_passthrough` to `True`.
More information about file wrappers are available in :pep:`333`.
:param file: a :class:`file`-like object with a :meth:`~file.read` method.
:param buffer_size: number of bytes for one iteration.