Vaccine Dashboard: _pytest.assertion.util Namespace Reference
_pytest.assertion.util Namespace Reference
Functions
str format_explanation (str explanation)
bool issequence (Any x)
bool istext (Any x)
bool isdict (Any x)
bool isset (Any x)
bool isnamedtuple (Any obj)
bool isdatacls (Any obj)
bool isattrs (Any obj)
bool isiterable (Any obj)
Optional[List[str]] assertrepr_compare (config, str op, Any left, Any right)
Detailed Description
Utilities for assertion debugging.
Function Documentation
assertrepr_compare()
Optional[List[str]] _pytest.assertion.util.assertrepr_compare (config, str op, Any left, Any right)
Return specialised explanations for some operators/operands.
References _pytest.assertion.util.isattrs(), _pytest.assertion.util.isdatacls(), _pytest.assertion.util.isdict(), _pytest.assertion.util.isiterable(), _pytest.assertion.util.isnamedtuple(), _pytest.assertion.util.issequence(), _pytest.assertion.util.isset(), _pytest.assertion.util.istext(), pip._vendor.pyparsing.range, _pytest._io.saferepr.safeformat(), _pytest._io.saferepr.saferepr(), py._builtin.set, pip._vendor.requests.compat.str, and dotenv.cli.type.
format_explanation()
str _pytest.assertion.util.format_explanation (str explanation)
Format an explanation.
Normally all embedded newlines are escaped, however there are
three exceptions: \n{, \n} and \n~.  The first two are intended
cover nested explanations, see function and attribute explanations
for examples (.visit_Call(), visit_Attribute()).  The last one is
for when one explanation needs to span multiple lines, e.g. when
displaying diffs.
References dotenv.cli.list().
isattrs()
bool _pytest.assertion.util.isattrs (Any obj)
isdatacls()
bool _pytest.assertion.util.isdatacls (Any obj)
isdict()
bool _pytest.assertion.util.isdict (Any x)
isiterable()
bool _pytest.assertion.util.isiterable (Any obj)
References _pytest.assertion.util.istext().
isnamedtuple()
bool _pytest.assertion.util.isnamedtuple (Any obj)
issequence()
bool _pytest.assertion.util.issequence (Any x)
isset()
bool _pytest.assertion.util.isset (Any x)
istext()
bool _pytest.assertion.util.istext (Any x)