Vaccine Dashboard: pip._vendor.distlib._backport.sysconfig Namespace Reference
pip._vendor.distlib._backport.sysconfig Namespace Reference
Functions
def is_python_build ()
def format_value (value, vars)
def get_makefile_filename ()
def parse_config_h (fp, vars=None)
def get_config_h_filename ()
def get_scheme_names ()
def get_path_names ()
def get_paths (scheme=_get_default_scheme(), vars=None, expand=True)
def get_path (name, scheme=_get_default_scheme(), vars=None, expand=True)
def get_config_vars (*args)
def get_config_var (name)
def get_platform ()
def get_python_version ()
Function Documentation
format_value()
def pip._vendor.distlib._backport.sysconfig.format_value (value, vars)
References pip._vendor.distlib._backport.sysconfig.get_config_var(), dotenv.cli.list(), and pip._vendor.requests.compat.str.
get_config_h_filename()
def pip._vendor.distlib._backport.sysconfig.get_config_h_filename ()
Return the path of pyconfig.h.
References pip._vendor.distlib._backport.sysconfig.get_path().
get_config_var()
def pip._vendor.distlib._backport.sysconfig.get_config_var (name)
Return the value of a single variable using the dictionary returned by
'get_config_vars()'.
Equivalent to get_config_vars().get(name)
References dotenv.cli.get(), and pip._vendor.distlib._backport.sysconfig.get_config_vars().
get_config_vars()
def pip._vendor.distlib._backport.sysconfig.get_config_vars (* args)
With no arguments, return a dictionary of all configuration
variables relevant for the current platform.
On Unix, this means every variable defined in Python's installed Makefile;
On Windows and Mac OS it's a much smaller set.
With arguments, return a list of values that result from looking up
each argument in the configuration variable dictionary.
get_makefile_filename()
def pip._vendor.distlib._backport.sysconfig.get_makefile_filename ()
Return the path of the Makefile.
References pip._vendor.distlib._backport.sysconfig.get_config_h_filename(), pip._vendor.distlib._backport.sysconfig.get_path(), pip._vendor.distlib._backport.tarfile.open, and pip._vendor.distlib._backport.sysconfig.parse_config_h().
get_path()
def pip._vendor.distlib._backport.sysconfig.get_path (name, scheme = _get_default_scheme(), vars = None, expand = True)
Return a path corresponding to the scheme.
``scheme`` is the install scheme name.
References pip._vendor.distlib._backport.sysconfig.get_paths().
get_path_names()
def pip._vendor.distlib._backport.sysconfig.get_path_names ()
Return a tuple containing the paths names.
get_paths()
def pip._vendor.distlib._backport.sysconfig.get_paths (scheme = _get_default_scheme(), vars = None, expand = True)
Return a mapping containing an install scheme.
``scheme`` is the install scheme name. If not provided, it will
return the default scheme for the current platform.
get_platform()
def pip._vendor.distlib._backport.sysconfig.get_platform ()
Return a string that identifies the current platform.
This is used mainly to distinguish platform-specific build directories and
platform-specific built distributions.  Typically includes the OS name
and version and the architecture (as supplied by 'os.uname()'),
although the exact information included depends on the OS; eg. for IRIX
the architecture isn't particularly important (IRIX only runs on SGI
hardware), but for Linux the kernel version isn't particularly
important.
Examples of returned values:
   linux-i586
   linux-alpha (?)
   solaris-2.6-sun4u
   irix-5.3
   irix64-6.2
Windows will return one of:
   win-amd64 (64bit Windows on AMD64 (aka x86_64, Intel64, EM64T, etc)
   win-ia64 (64bit Windows on Itanium)
   win32 (all others - specifically, sys.platform is returned)
For other non-POSIX platforms, currently just returns 'sys.platform'.
References dotenv.cli.get(), pip._vendor.distlib._backport.sysconfig.get_config_vars(), pip._vendor.distlib._backport.tarfile.open, pip._internal.utils.filesystem.replace, py._builtin.set, and py._builtin.sorted.
get_python_version()
def pip._vendor.distlib._backport.sysconfig.get_python_version ()
References py._builtin.enumerate, pip._vendor.distlib._backport.sysconfig.get_config_vars(), pip._vendor.distlib._backport.sysconfig.get_paths(), pip._vendor.distlib._backport.sysconfig.get_platform(), and py._builtin.sorted.
get_scheme_names()
def pip._vendor.distlib._backport.sysconfig.get_scheme_names ()
Return a tuple containing the schemes names.
References py._builtin.sorted.
is_python_build()
def pip._vendor.distlib._backport.sysconfig.is_python_build ()
References pip._vendor.distlib.resources.finder(), and pip._vendor.distlib._backport.sysconfig.get_config_vars().
parse_config_h()
def pip._vendor.distlib._backport.sysconfig.parse_config_h (fp, vars = None)
Parse a config.h-style file.
A dictionary containing name/value pairs is returned.  If an
optional dictionary is passed in as the second argument, it is
used instead of a new dictionary.