Vaccine Dashboard: dotenv.cli Namespace Reference
dotenv.cli Namespace Reference
Functions
None cli (click.Context ctx, Any file, Any quote, Any export)
None list (click.Context ctx)
None set (click.Context ctx, Any key, Any value)
None get (click.Context ctx, Any key)
None unset (click.Context ctx, Any key)
None run (click.Context ctx, bool override, List[str] commandline)
int run_command (List[str] command, Dict[str, str] env)
Variables
type
file_okay
help
Function Documentation
cli()
None dotenv.cli.cli (click.Context ctx, Any file, Any quote, Any export)
This script is used to set, get or unset values from a .env file.
get()
None dotenv.cli.get (click.Context ctx, Any key)
Retrieve the value for the given key.
References _pytest.outcomes.exit(), and dotenv.main.get_key().
list()
None dotenv.cli.list (click.Context ctx)
Display all the stored key/value.
References dotenv.main.dotenv_values().
run()
None dotenv.cli.run (click.Context ctx, bool override, List[str] commandline)
Run command with environment variables present.
References dotenv.main.dotenv_values(), _pytest.outcomes.exit(), and dotenv.cli.run_command().
run_command()
int dotenv.cli.run_command (List[str] command, Dict[str, str] env)
Run command in sub process.
Runs the command in a sub process with the variables from `env`
added in the current environment variables.
Parameters
----------
command: List[str]
    The command and it's parameters
env: Dict
    The additional environment variables
Returns
-------
int
    The return code of the command
References dotenv.cli.cli().
set()
None dotenv.cli.set (click.Context ctx, Any key, Any value)
Store the given key/value.
References _pytest.outcomes.exit(), and dotenv.main.set_key().
unset()
None dotenv.cli.unset (click.Context ctx, Any key)
Removes the given key.
References _pytest.outcomes.exit(), dotenv.cli.run(), and dotenv.main.unset_key().
Variable Documentation
file_okay
dotenv.cli.file_okay
help
dotenv.cli.help
type
dotenv.cli.type