Vaccine Dashboard: toml.decoder Namespace Reference
toml.decoder Namespace Reference
Classes
class TomlDecodeError
class CommentValue
class InlineTableDict
class TomlDecoder
class TomlPreserveCommentDecoder
Functions
def load (f, _dict=dict, decoder=None)
def loads (s, _dict=dict, decoder=None)
Variables
unicode = str
basestring = str
unichr = chr
FNFError = IOError
TIME_RE = re.compile(r"([0-9]{2}):([0-9]{2}):([0-9]{2})(\.([0-9]{3,6}))?")
Function Documentation
load()
def toml.decoder.load (f, _dict = dict, decoder = None)
Parses named file or files as toml and returns a dictionary
Args:
    f: Path to the file to open, array of files to read into single dict
       or a file descriptor
    _dict: (optional) Specifies the class of the returned toml dictionary
    decoder: The decoder to use
Returns:
    Parsed toml file represented as a dictionary
Raises:
    TypeError -- When f is invalid type
    TomlDecodeError: Error while decoding toml
    IOError / FileNotFoundError -- When an array with no valid (existing)
    (Python 2 / Python 3)          file paths is passed
References toml.decoder.FNFError, toml.decoder.loads(), and py._log.warning.warn().
loads()
def toml.decoder.loads (s, _dict = dict, decoder = None)
Parses string as toml
Args:
    s: String to be parsed
    _dict: (optional) Specifies the class of the returned toml dictionary
Returns:
    Parsed toml file represented as a dictionary
Raises:
    TypeError: When a non-string is passed
    TomlDecodeError: Error while decoding toml
References pip._vendor.requests.append, py._builtin.enumerate, dotenv.cli.list(), pip._vendor.requests.compat.str, toml.decoder.unichr, and toml.decoder.unicode.
Variable Documentation
basestring
toml.decoder.basestring = str
FNFError
toml.decoder.FNFError = IOError
TIME_RE
toml.decoder.TIME_RE = re.compile(r"([0-9]{2}):([0-9]{2}):([0-9]{2})(\.([0-9]{3,6}))?")
unichr
toml.decoder.unichr = chr
unicode
toml.decoder.unicode = str