Vaccine Dashboard: jwt.algorithms.Ed25519Algorithm Class Reference
jwt.algorithms.Ed25519Algorithm Class Reference
Public Member Functions
def __init__ (self, **kwargs)
def prepare_key (self, key)
def sign (self, msg, key)
def verify (self, msg, key, sig)
Static Public Member Functions
def to_jwk (key)
def from_jwk (jwk)
Detailed Description
Performs signing and verification operations using Ed25519
This class requires ``cryptography>=2.6`` to be installed.
Constructor & Destructor Documentation
__init__()
def jwt.algorithms.Ed25519Algorithm.__init__ (self, ** kwargs)
Member Function Documentation
from_jwk()
def jwt.algorithms.Ed25519Algorithm.from_jwk (jwk) static
Deserializes a given RSA key from JWK back into a PublicKey or PrivateKey object
Reimplemented from jwt.algorithms.Algorithm.
References jwt.utils.base64url_decode().
prepare_key()
def jwt.algorithms.Ed25519Algorithm.prepare_key (self, key)
Performs necessary validation and conversions on the key and returns
the key value in the proper format for sign() and verify().
Reimplemented from jwt.algorithms.Algorithm.
sign()
def jwt.algorithms.Ed25519Algorithm.sign (self, msg, key)
Sign a message ``msg`` using the Ed25519 private key ``key``
:param str|bytes msg: Message to sign
:param Ed25519PrivateKey key: A :class:`.Ed25519PrivateKey` instance
:return bytes signature: The signature, as bytes
Reimplemented from jwt.algorithms.Algorithm.
References pip._vendor.requests.compat.bytes, and dotenv.cli.type.
to_jwk()
def jwt.algorithms.Ed25519Algorithm.to_jwk (key_obj) static
Serializes a given RSA key into a JWK
Reimplemented from jwt.algorithms.Algorithm.
References jwt.utils.base64url_encode(), jwt.api_jws.decode, and jwt.utils.force_bytes().
verify()
def jwt.algorithms.Ed25519Algorithm.verify (self, msg, key, sig)
Verify a given ``msg`` against a signature ``sig`` using the Ed25519 key ``key``
:param str|bytes sig: Ed25519 signature to check ``msg`` against
:param str|bytes msg: Message to sign
:param Ed25519PrivateKey|Ed25519PublicKey key: A private or public Ed25519 key instance
:return bool verified: True if signature is valid, False if not.
Reimplemented from jwt.algorithms.Algorithm.
References pip._vendor.requests.compat.bytes, and dotenv.cli.type.
The documentation for this class was generated from the following file:
back-end/flaskenv/Lib/site-packages/jwt/algorithms.py