Vaccine Dashboard: jinja2.idtracking.RootVisitor Class Reference
jinja2.idtracking.RootVisitor Class Reference
Public Member Functions
None __init__ (self, "Symbols" symbols)
None visit_AssignBlock (self, nodes.AssignBlock node, **t.Any kwargs)
None visit_CallBlock (self, nodes.CallBlock node, **t.Any kwargs)
None visit_OverlayScope (self, nodes.OverlayScope node, **t.Any kwargs)
None visit_For (self, nodes.For node, str for_branch="body", **t.Any kwargs)
None visit_With (self, nodes.With node, **t.Any kwargs)
None generic_visit (self, nodes.Node node, *t.Any args, **t.Any kwargs)
Public Member Functions inherited from jinja2.visitor.NodeVisitor
"t.Optional[VisitCallable]" get_visitor (self, Node node)
t.Any visit (self, Node node, *t.Any args, **t.Any kwargs)
t.Any generic_visit (self, Node node, *t.Any args, **t.Any kwargs)
Public Attributes
sym_visitor
Static Public Attributes
None visit_Template = _simple_visit
None visit_Block = _simple_visit
None visit_Macro = _simple_visit
None visit_FilterBlock = _simple_visit
None visit_Scope = _simple_visit
None visit_If = _simple_visit
None visit_ScopedEvalContextModifier = _simple_visit
Constructor & Destructor Documentation
__init__()
None jinja2.idtracking.RootVisitor.__init__ (self, "Symbols" symbols)
Member Function Documentation
generic_visit()
None jinja2.idtracking.RootVisitor.generic_visit (self, nodes.Node node, *t.Any args, **t.Any kwargs)
visit_AssignBlock()
None jinja2.idtracking.RootVisitor.visit_AssignBlock (self, nodes.AssignBlock node, **t.Any kwargs)
References jinja2.idtracking.RootVisitor.sym_visitor, and jinja2.visitor.NodeVisitor.visit().
visit_CallBlock()
None jinja2.idtracking.RootVisitor.visit_CallBlock (self, nodes.CallBlock node, **t.Any kwargs)
References jinja2.idtracking.RootVisitor.sym_visitor, and jinja2.visitor.NodeVisitor.visit().
visit_For()
None jinja2.idtracking.RootVisitor.visit_For (self, nodes.For node, str for_branch = "body", **t.Any kwargs)
References jinja2.idtracking.RootVisitor.sym_visitor, and jinja2.visitor.NodeVisitor.visit().
visit_OverlayScope()
None jinja2.idtracking.RootVisitor.visit_OverlayScope (self, nodes.OverlayScope node, **t.Any kwargs)
References jinja2.idtracking.RootVisitor.sym_visitor, and jinja2.visitor.NodeVisitor.visit().
visit_With()
None jinja2.idtracking.RootVisitor.visit_With (self, nodes.With node, **t.Any kwargs)
References jinja2.idtracking.RootVisitor.sym_visitor, and jinja2.visitor.NodeVisitor.visit().
Member Data Documentation
sym_visitor
jinja2.idtracking.RootVisitor.sym_visitor
visit_Block
None jinja2.idtracking.RootVisitor.visit_Block = _simple_visit static
visit_FilterBlock
None jinja2.idtracking.RootVisitor.visit_FilterBlock = _simple_visit static
visit_If
None jinja2.idtracking.RootVisitor.visit_If = _simple_visit static
visit_Macro
None jinja2.idtracking.RootVisitor.visit_Macro = _simple_visit static
visit_Scope
None jinja2.idtracking.RootVisitor.visit_Scope = _simple_visit static
visit_ScopedEvalContextModifier
None jinja2.idtracking.RootVisitor.visit_ScopedEvalContextModifier = _simple_visit static
visit_Template
None jinja2.idtracking.RootVisitor.visit_Template = _simple_visit static
The documentation for this class was generated from the following file:
back-end/flaskenv/Lib/site-packages/jinja2/idtracking.py