Vaccine Dashboard: _pytest.monkeypatch.MonkeyPatch Class Reference
_pytest.monkeypatch.MonkeyPatch Class Reference
Public Member Functions
None __init__ (self)
Generator["MonkeyPatch", None, None] context (cls)
None setattr (self, str target, object name, Notset value=..., bool raising=...)
None setattr (self, object target, str name, object value, bool raising=...)
None setattr (self, Union[str, object] target, Union[object, str] name, object value=notset, bool raising=True)
None delattr (self, Union[object, str] target, Union[str, Notset] name=notset, bool raising=True)
None setitem (self, MutableMapping[K, V] dic, K name, V value)
None delitem (self, MutableMapping[K, V] dic, K name, bool raising=True)
None setenv (self, str name, str value, Optional[str] prepend=None)
None delenv (self, str name, bool raising=True)
None syspath_prepend (self, path)
None chdir (self, path)
None undo (self)
Detailed Description
Helper to conveniently monkeypatch attributes/items/environment
variables/syspath.
Returned by the :fixture:`monkeypatch` fixture.
:versionchanged:: 6.2
    Can now also be used directly as `pytest.MonkeyPatch()`, for when
    the fixture is not available. In this case, use
    :meth:`with MonkeyPatch.context() as mp: <context>` or remember to call
    :meth:`undo` explicitly.
Constructor & Destructor Documentation
__init__()
None _pytest.monkeypatch.MonkeyPatch.__init__ (self)
References _pytest.monkeypatch.MonkeyPatch._cwd, and _pytest.monkeypatch.MonkeyPatch._savesyspath.
Member Function Documentation
chdir()
None _pytest.monkeypatch.MonkeyPatch.chdir (self, path)
Change the current working directory to the specified path.
Path can be a string or a py.path.local object.
References _pytest.monkeypatch.MonkeyPatch._cwd, and pip._vendor.requests.compat.str.
context()
Generator["MonkeyPatch", None, None] _pytest.monkeypatch.MonkeyPatch.context (cls)
Context manager that returns a new :class:`MonkeyPatch` object
which undoes any patching done inside the ``with`` block upon exit.
Example:
.. code-block:: python
    import functools
    def test_partial(monkeypatch):
        with monkeypatch.context() as m:
            m.setattr(functools, "partial", 3)
Useful in situations where it is desired to undo some patches before the test ends,
such as mocking ``stdlib`` functions that might break pytest itself if mocked (for examples
of this see `#3290 <https://github.com/pytest-dev/pytest/issues/3290>`_.
delattr()
None _pytest.monkeypatch.MonkeyPatch.delattr (self, Union[object, str] target, Union[str, Notset] name = notset, bool raising = True)
Delete attribute ``name`` from ``target``.
If no ``name`` is specified and ``target`` is a string
it will be interpreted as a dotted import path with the
last part being the attribute name.
Raises AttributeError it the attribute does not exist, unless
``raising`` is set to False.
References pip._vendor.requests.append, and _pytest.monkeypatch.derive_importpath().
delenv()
None _pytest.monkeypatch.MonkeyPatch.delenv (self, str name, bool raising = True)
Delete ``name`` from the environment.
Raises ``KeyError`` if it does not exist, unless ``raising`` is set to
False.
References _pytest.monkeypatch.MonkeyPatch.delitem().
delitem()
None _pytest.monkeypatch.MonkeyPatch.delitem (self, MutableMapping[K, V] dic, K name, bool raising = True)
Delete ``name`` from dict.
Raises ``KeyError`` if it doesn't exist, unless ``raising`` is set to
False.
References pip._vendor.requests.append.
setattr() [1/3]
None _pytest.monkeypatch.MonkeyPatch.setattr (self, object target, str name, object value, bool raising = ...)
References _pytest.monkeypatch.MonkeyPatch.setattr().
setattr() [2/3]
None _pytest.monkeypatch.MonkeyPatch.setattr (self, str target, object name, Notset value = ..., bool raising = ...)
setattr() [3/3]
None _pytest.monkeypatch.MonkeyPatch.setattr (self, Union[str, object] target, Union[object, str] name, object value = notset, bool raising = True)
Set attribute value on target, memorizing the old value.
For convenience you can specify a string as ``target`` which
will be interpreted as a dotted import path, with the last part
being the attribute name. For example,
``monkeypatch.setattr("os.getcwd", lambda: "/")``
would set the ``getcwd`` function of the ``os`` module.
Raises AttributeError if the attribute does not exist, unless
``raising`` is set to False.
References pip._vendor.requests.append, _pytest.monkeypatch.derive_importpath(), and _pytest.monkeypatch.MonkeyPatch.setattr().
setenv()
None _pytest.monkeypatch.MonkeyPatch.setenv (self, str name, str value, Optional[str] prepend = None)
Set environment variable ``name`` to ``value``.
If ``prepend`` is a character, read the current environment variable
value and prepend the ``value`` adjoined with the ``prepend``
character.
References _pytest.monkeypatch.MonkeyPatch.setitem(), pip._vendor.requests.compat.str, and dotenv.cli.type.
setitem()
None _pytest.monkeypatch.MonkeyPatch.setitem (self, MutableMapping[K, V] dic, K name, V value)
Set dictionary entry ``name`` to value.
References pip._vendor.requests.append.
syspath_prepend()
None _pytest.monkeypatch.MonkeyPatch.syspath_prepend (self, path)
Prepend ``path`` to ``sys.path`` list of import locations.
References _pytest.monkeypatch.MonkeyPatch._savesyspath, pip._vendor.pkg_resources.fixup_namespace_packages(), and pip._vendor.requests.compat.str.
undo()
None _pytest.monkeypatch.MonkeyPatch.undo (self)
Undo previous changes.
This call consumes the undo stack. Calling it a second time has no
effect unless you do more monkeypatching after the undo call.
There is generally no need to call `undo()`, since it is
called automatically during tear-down.
Note that the same `monkeypatch` fixture is used across a
single test function invocation. If `monkeypatch` is used both by
the test function itself and one of the test fixtures,
calling `undo()` will undo all of the changes made in
both functions.
References _pytest.monkeypatch.MonkeyPatch._cwd, _pytest.monkeypatch.MonkeyPatch._savesyspath, _pytest.monkeypatch.MonkeyPatch.delattr(), py._builtin.reversed, and _pytest.monkeypatch.MonkeyPatch.setattr().
The documentation for this class was generated from the following file:
back-end/flaskenv/Lib/site-packages/_pytest/monkeypatch.py