Vaccine Dashboard: flask_cors.extension Namespace Reference
flask_cors.extension Namespace Reference
Classes
class CORS
Functions
def make_after_request_function (resources)
Variables
LOG = logging.getLogger(__name__)
Function Documentation
make_after_request_function()
def flask_cors.extension.make_after_request_function (resources)
References flask_cors.core.get_regexp_pattern(), flask_cors.core.set_cors_headers(), and flask_cors.core.try_match().
Variable Documentation
LOG
flask_cors.extension.LOG = logging.getLogger(__name__)