Vaccine Dashboard: werkzeug.utils Namespace Reference
werkzeug.utils Namespace Reference
Classes
class cached_property
class environ_property
class header_property
class HTMLBuilder
class ArgumentValidationError
class ImportStringError
Functions
None invalidate_cached_property (object obj, str name)
str get_content_type (str mimetype, str charset)
str detect_utf_encoding (bytes data)
str format_string (str string, t.Mapping[str, t.Any] context)
str secure_filename (str filename)
str escape (t.Any s)
str unescape (str s)
"Response" redirect (str location, int code=302, t.Optional[t.Type["Response"]] Response=None)
"Response" append_slash_redirect ("WSGIEnvironment" environ, int code=301)
"Response" send_file (t.Union[os.PathLike, str, t.BinaryIO] path_or_file, "WSGIEnvironment" environ, t.Optional[str] mimetype=None, bool as_attachment=False, t.Optional[str] download_name=None, bool conditional=True, t.Union[bool, str] etag=True, t.Optional[t.Union[datetime, int, float]] last_modified=None, t.Optional[t.Union[int, t.Callable[[t.Optional[str]], t.Optional[int]]]] max_age=None, bool use_x_sendfile=False, t.Optional[t.Type["Response"]] response_class=None, t.Optional[t.Union[os.PathLike, str]] _root_path=None)
"Response" send_from_directory (t.Union[os.PathLike, str] directory, t.Union[os.PathLike, str] path, "WSGIEnvironment" environ, **t.Any kwargs)
t.Any import_string (str import_name, bool silent=False)
t.Iterator[str] find_modules (str import_path, bool include_packages=False, bool recursive=False)
def validate_arguments (func, args, kwargs, drop_extra=True)
def bind_arguments (func, args, kwargs)
Variables
html = HTMLBuilder("html")
xhtml = HTMLBuilder("xhtml")
Function Documentation
append_slash_redirect()
"Response" werkzeug.utils.append_slash_redirect ("WSGIEnvironment" environ, int code = 301)
Redirects to the same URL but with a slash appended.  The behavior
of this function is undefined if the path ends with a slash already.
:param environ: the WSGI environment for the request that triggers
                the redirect.
:param code: the status code for the redirect.
References werkzeug.utils.redirect().
bind_arguments()
def werkzeug.utils.bind_arguments (func, args, kwargs)
Bind the arguments provided into a dict.  When passed a function,
a tuple of arguments and a dict of keyword arguments `bind_arguments`
returns a dict of names as the function would see it.  This can be useful
to implement a cache decorator that uses the function arguments to build
the cache key based on the values of the arguments.
:param func: the function the arguments should be bound for.
:param args: tuple of positional arguments.
:param kwargs: a dict of keyword arguments.
:return: a :class:`dict` of bound keyword arguments.
.. deprecated:: 2.0
    Will be removed in Werkzeug 2.1. Use :meth:`Signature.bind`
    instead.
References py._builtin.set.
detect_utf_encoding()
str werkzeug.utils.detect_utf_encoding (bytes data)
Detect which UTF encoding was used to encode the given bytes.
The latest JSON standard (:rfc:`8259`) suggests that only UTF-8 is
accepted. Older documents allowed 8, 16, or 32. 16 and 32 can be big
or little endian. Some editors or libraries may prepend a BOM.
:internal:
:param data: Bytes in unknown UTF encoding.
:return: UTF encoding name
.. deprecated:: 2.0
    Will be removed in Werkzeug 2.1. This is built in to
    :func:`json.loads`.
.. versionadded:: 0.15
escape()
str werkzeug.utils.escape (t.Any s)
Replace ``&``, ``<``, ``>``, ``"``, and ``'`` with HTML-safe
sequences.
``None`` is escaped to an empty string.
.. deprecated:: 2.0
    Will be removed in Werkzeug 2.1. Use MarkupSafe instead.
References pip._vendor.requests.compat.str.
find_modules()
t.Iterator[str] werkzeug.utils.find_modules (str import_path, bool include_packages = False, bool recursive = False)
Finds all the modules below a package.  This can be useful to
automatically import all views / controllers so that their metaclasses /
function decorators have a chance to register themselves on the
application.
Packages are not returned unless `include_packages` is `True`.  This can
also recursively list modules but in that case it will import all the
packages to get the correct load path of that module.
:param import_path: the dotted name for the package to find child modules.
:param include_packages: set to `True` if packages should be returned, too.
:param recursive: set to `True` if recursion should happen.
:return: generator
References werkzeug.utils.import_string().
format_string()
str werkzeug.utils.format_string (str string, t.Mapping[str, t.Any] context)
String-template format a string:
>>> format_string('$foo and ${foo}s', dict(foo=42))
'42 and 42s'
This does not do any attribute lookup.
:param string: the format string.
:param context: a dict with the variables to insert.
.. deprecated:: 2.0
    Will be removed in Werkzeug 2.1. Use :class:`string.Template`
    instead.
get_content_type()
str werkzeug.utils.get_content_type (str mimetype, str charset)
Returns the full content type string with charset for a mimetype.
If the mimetype represents text, the charset parameter will be
appended, otherwise the mimetype is returned unchanged.
:param mimetype: The mimetype to be used as content type.
:param charset: The charset to be appended for text mimetypes.
:return: The content type.
.. versionchanged:: 0.15
    Any type that ends with ``+xml`` gets a charset, not just those
    that start with ``application/``. Known text types such as
    ``application/javascript`` are also given charsets.
import_string()
t.Any werkzeug.utils.import_string (str import_name, bool silent = False)
Imports an object based on a string.  This is useful if you want to
use import paths as endpoints or something similar.  An import path can
be specified either in dotted notation (``xml.sax.saxutils.escape``)
or with a colon as object delimiter (``xml.sax.saxutils:escape``).
If `silent` is True the return value will be `None` if the import fails.
:param import_name: the dotted name for the object to import.
:param silent: if set to `True` import errors are ignored and
               `None` is returned instead.
:return: imported object
invalidate_cached_property()
None werkzeug.utils.invalidate_cached_property (object obj, str name)
Invalidates the cache for a :class:`cached_property`:
>>> class Test(object):
...     @cached_property
...     def magic_number(self):
...         print("recalculating...")
...         return 42
...
>>> var = Test()
>>> var.magic_number
recalculating...
42
>>> var.magic_number
42
>>> invalidate_cached_property(var, "magic_number")
>>> var.magic_number
recalculating...
42
You must pass the name of the cached property as the second argument.
.. deprecated:: 2.0
    Will be removed in Werkzeug 2.1. Use ``del obj.name`` instead.
redirect()
"Response" werkzeug.utils.redirect (str location, int code = 302, t.Optional[t.Type["Response"]] Response = None)
Returns a response object (a WSGI application) that, if called,
redirects the client to the target location. Supported codes are
301, 302, 303, 305, 307, and 308. 300 is not supported because
it's not a real redirect and 304 because it's the answer for a
request with a request with defined If-Modified-Since headers.
.. versionadded:: 0.6
   The location can now be a unicode string that is encoded using
   the :func:`iri_to_uri` function.
.. versionadded:: 0.10
    The class used for the Response object can now be passed in.
:param location: the location the response should redirect to.
:param code: the redirect status code. defaults to 302.
:param class Response: a Response class to use when instantiating a
    response. The default is :class:`werkzeug.wrappers.Response` if
    unspecified.
References werkzeug.urls.iri_to_uri().
secure_filename()
str werkzeug.utils.secure_filename (str filename)
Pass it a filename and it will return a secure version of it.  This
filename can then safely be stored on a regular file system and passed
to :func:`os.path.join`.  The filename returned is an ASCII only string
for maximum portability.
On windows systems the function also makes sure that the file is not
named after one of the special device files.
>>> secure_filename("My cool movie.mov")
'My_cool_movie.mov'
>>> secure_filename("../../../etc/passwd")
'etc_passwd'
>>> secure_filename('i contain cool \xfcml\xe4uts.txt')
'i_contain_cool_umlauts.txt'
The function might return an empty filename.  It's your responsibility
to ensure that the filename is unique and that you abort or
generate a random filename if the function returned an empty one.
.. versionadded:: 0.5
:param filename: the filename to secure
References jwt.api_jws.decode, and pip._vendor.requests.compat.str.
send_file()
"Response" werkzeug.utils.send_file (t.Union[os.PathLike, str, t.BinaryIO] path_or_file, "WSGIEnvironment" environ, t.Optional[str] mimetype = None, bool as_attachment = False, t.Optional[str] download_name = None, bool conditional = True, t.Union[bool, str] etag = True, t.Optional[t.Union[datetime, int, float]] last_modified = None, t.Optional[ t.Union[int, t.Callable[[t.Optional[str]], t.Optional[int]]] ] max_age = None, bool use_x_sendfile = False, t.Optional[t.Type["Response"]] response_class = None, t.Optional[t.Union[os.PathLike, str]] _root_path = None)
Send the contents of a file to the client.
The first argument can be a file path or a file-like object. Paths
are preferred in most cases because Werkzeug can manage the file and
get extra information from the path. Passing a file-like object
requires that the file is opened in binary mode, and is mostly
useful when building a file in memory with :class:`io.BytesIO`.
Never pass file paths provided by a user. The path is assumed to be
trusted, so a user could craft a path to access a file you didn't
intend.
If the WSGI server sets a ``file_wrapper`` in ``environ``, it is
used, otherwise Werkzeug's built-in wrapper is used. Alternatively,
if the HTTP server supports ``X-Sendfile``, ``use_x_sendfile=True``
will tell the server to send the given path, which is much more
efficient than reading it in Python.
:param path_or_file: The path to the file to send, relative to the
    current working directory if a relative path is given.
    Alternatively, a file-like object opened in binary mode. Make
    sure the file pointer is seeked to the start of the data.
:param environ: The WSGI environ for the current request.
:param mimetype: The MIME type to send for the file. If not
    provided, it will try to detect it from the file name.
:param as_attachment: Indicate to a browser that it should offer to
    save the file instead of displaying it.
:param download_name: The default name browsers will use when saving
    the file. Defaults to the passed file name.
:param conditional: Enable conditional and range responses based on
    request headers. Requires passing a file path and ``environ``.
:param etag: Calculate an ETag for the file, which requires passing
    a file path. Can also be a string to use instead.
:param last_modified: The last modified time to send for the file,
    in seconds. If not provided, it will try to detect it from the
    file path.
:param max_age: How long the client should cache the file, in
    seconds. If set, ``Cache-Control`` will be ``public``, otherwise
    it will be ``no-cache`` to prefer conditional caching.
:param use_x_sendfile: Set the ``X-Sendfile`` header to let the
    server to efficiently send the file. Requires support from the
    HTTP server. Requires passing a file path.
:param response_class: Build the response using this class. Defaults
    to :class:`~werkzeug.wrappers.Response`.
:param _root_path: Do not use. For internal use only. Use
    :func:`send_from_directory` to safely send files under a path.
.. versionadded:: 2.0
    Adapted from Flask's implementation.
.. versionchanged:: 2.0
    ``download_name`` replaces Flask's ``attachment_filename``
     parameter. If ``as_attachment=False``, it is passed with
     ``Content-Disposition: inline`` instead.
.. versionchanged:: 2.0
    ``max_age`` replaces Flask's ``cache_timeout`` parameter.
    ``conditional`` is enabled and ``max_age`` is not set by
    default.
.. versionchanged:: 2.0
    ``etag`` replaces Flask's ``add_etags`` parameter. It can be a
    string to use instead of generating one.
.. versionchanged:: 2.0
    If an encoding is returned when guessing ``mimetype`` from
    ``download_name``, set the ``Content-Encoding`` header.
References cffi.api.callable, jwt.api_jws.decode, pip._vendor.distlib._backport.tarfile.open, jinja2.utils.url_quote(), and werkzeug.wsgi.wrap_file().
send_from_directory()
"Response" werkzeug.utils.send_from_directory (t.Union[os.PathLike, str] directory, t.Union[os.PathLike, str] path, "WSGIEnvironment" environ, **t.Any kwargs)
Send a file from within a directory using :func:`send_file`.
This is a secure way to serve files from a folder, such as static
files or uploads. Uses :func:`~werkzeug.security.safe_join` to
ensure the path coming from the client is not maliciously crafted to
point outside the specified directory.
If the final path does not point to an existing regular file,
returns a 404 :exc:`~werkzeug.exceptions.NotFound` error.
:param directory: The directory that ``path`` must be located under.
:param path: The path to the file to send, relative to
    ``directory``.
:param environ: The WSGI environ for the current request.
:param kwargs: Arguments to pass to :func:`send_file`.
.. versionadded:: 2.0
    Adapted from Flask's implementation.
References flask.helpers.safe_join(), and werkzeug.utils.send_file().
unescape()
str werkzeug.utils.unescape (str s)
The reverse of :func:`escape`. This unescapes all the HTML
entities, not only those inserted by ``escape``.
.. deprecated:: 2.0
    Will be removed in Werkzeug 2.1. Use MarkupSafe instead.
validate_arguments()
def werkzeug.utils.validate_arguments (func, args, kwargs, drop_extra = True)
Checks if the function accepts the arguments and keyword arguments.
Returns a new ``(args, kwargs)`` tuple that can safely be passed to
the function without causing a `TypeError` because the function signature
is incompatible.  If `drop_extra` is set to `True` (which is the default)
any extra positional or keyword arguments are dropped automatically.
The exception raised provides three attributes:
`missing`
    A set of argument names that the function expected but where
    missing.
`extra`
    A dict of keyword arguments that the function can not handle but
    where provided.
`extra_positional`
    A list of values that where given by positional argument but the
    function cannot accept.
This can be useful for decorators that forward user submitted data to
a view function::
    from werkzeug.utils import ArgumentValidationError, validate_arguments
    def sanitize(f):
        def proxy(request):
            data = request.values.to_dict()
            try:
                args, kwargs = validate_arguments(f, (request,), data)
            except ArgumentValidationError:
                raise BadRequest('The browser failed to transmit all '
                                 'the data expected.')
            return f(*args, **kwargs)
        return proxy
:param func: the function the validation is performed against.
:param args: a tuple of positional arguments.
:param kwargs: a dict of keyword arguments.
:param drop_extra: set to `False` if you don't want extra arguments
                   to be silently dropped.
:return: tuple in the form ``(args, kwargs)``.
.. deprecated:: 2.0
    Will be removed in Werkzeug 2.1. Use :func:`inspect.signature`
    instead.
References pip._vendor.certifi.__main__.parser.
Variable Documentation
html
werkzeug.utils.html = HTMLBuilder("html")
xhtml
werkzeug.utils.xhtml = HTMLBuilder("xhtml")