Vaccine Dashboard: click._compat Namespace Reference
click._compat Namespace Reference
Classes
class _NonClosingTextIOWrapper
class _FixupStream
class _AtomicFile
Functions
str get_filesystem_encoding ()
bool is_ascii_encoding (str encoding)
str get_best_encoding (t.IO stream)
t.BinaryIO get_binary_stdin ()
t.BinaryIO get_binary_stdout ()
t.BinaryIO get_binary_stderr ()
t.TextIO get_text_stdin (t.Optional[str] encoding=None, t.Optional[str] errors=None)
t.TextIO get_text_stdout (t.Optional[str] encoding=None, t.Optional[str] errors=None)
t.TextIO get_text_stderr (t.Optional[str] encoding=None, t.Optional[str] errors=None)
t.Tuple[t.IO, bool] open_stream (str filename, str mode="r", t.Optional[str] encoding=None, t.Optional[str] errors="strict", bool atomic=False)
str strip_ansi (str value)
bool should_strip_ansi (t.Optional[t.IO] stream=None, t.Optional[bool] color=None)
t.TextIO auto_wrap_for_ansi (t.TextIO stream, t.Optional[bool] color=None)
int term_len (str x)
bool isatty (t.IO stream)
Variables
CYGWIN = sys.platform.startswith("cygwin")
MSYS2 = sys.platform.startswith("win") and ("GCC" in sys.version)
string APP_ENGINE
string WIN = sys.platform.startswith("win") and not APP_ENGINE and not MSYS2
Function Documentation
auto_wrap_for_ansi()
t.TextIO click._compat.auto_wrap_for_ansi (t.TextIO stream, t.Optional[bool] color = None)
Support ANSI color and style codes on Windows by wrapping a
stream with colorama.
References click._compat.get_filesystem_encoding(), and click._compat.should_strip_ansi().
get_best_encoding()
str click._compat.get_best_encoding (t.IO stream)
Returns the default stream encoding if not found.
References click._compat.is_ascii_encoding().
get_binary_stderr()
t.BinaryIO click._compat.get_binary_stderr ()
get_binary_stdin()
t.BinaryIO click._compat.get_binary_stdin ()
get_binary_stdout()
t.BinaryIO click._compat.get_binary_stdout ()
get_filesystem_encoding()
str click._compat.get_filesystem_encoding ()
References click._compat.get_best_encoding().
get_text_stderr()
t.TextIO click._compat.get_text_stderr (t.Optional[str] encoding = None, t.Optional[str] errors = None)
References pip._vendor.distlib._backport.tarfile.open.
get_text_stdin()
t.TextIO click._compat.get_text_stdin (t.Optional[str] encoding = None, t.Optional[str] errors = None)
get_text_stdout()
t.TextIO click._compat.get_text_stdout (t.Optional[str] encoding = None, t.Optional[str] errors = None)
is_ascii_encoding()
bool click._compat.is_ascii_encoding (str encoding)
Checks if a given encoding is ascii.
isatty()
bool click._compat.isatty (t.IO stream)
open_stream()
t.Tuple[t.IO, bool] click._compat.open_stream (str filename, str mode = "r", t.Optional[str] encoding = None, t.Optional[str] errors = "strict", bool atomic = False)
References py._builtin.any, click._compat.get_binary_stdin(), click._compat.get_binary_stdout(), click._compat.get_text_stdin(), and click._compat.get_text_stdout().
should_strip_ansi()
bool click._compat.should_strip_ansi (t.Optional[t.IO] stream = None, t.Optional[bool] color = None)
References click._compat.isatty().
strip_ansi()
str click._compat.strip_ansi (str value)
term_len()
int click._compat.term_len (str x)
References click._compat.strip_ansi().
Variable Documentation
APP_ENGINE
string click._compat.APP_ENGINE
Initial value:
 =  "APPENGINE_RUNTIME" in os.environ and "Development/" in os.environ.get(
     "SERVER_SOFTWARE", ""
 )
CYGWIN
click._compat.CYGWIN = sys.platform.startswith("cygwin")
MSYS2
click._compat.MSYS2 = sys.platform.startswith("win") and ("GCC" in sys.version)
WIN
string click._compat.WIN = sys.platform.startswith("win") and not APP_ENGINE and not MSYS2