Vaccine Dashboard: pip._internal.commands.install Namespace Reference
pip._internal.commands.install Namespace Reference
Classes
class InstallCommand
Functions
def get_check_binary_allowed (format_control)
def get_lib_location_guesses (user=False, home=None, root=None, isolated=False, prefix=None # type:Optional[str])
def site_packages_writable (root, isolated)
def decide_user_install (use_user_site, prefix_path=None, target_dir=None, root_path=None, isolated_mode=False)
def reject_location_related_install_options (requirements, options)
def create_os_error_message (error, show_traceback, using_user_site)
Variables
logger = logging.getLogger(__name__)
Function Documentation
create_os_error_message()
def pip._internal.commands.install.create_os_error_message (error, show_traceback, using_user_site)
Format an error message for an OSError
It may occur anytime during the execution of the install command.
References pip._internal.utils.virtualenv.running_under_virtualenv(), and pip._vendor.requests.compat.str.
decide_user_install()
def pip._internal.commands.install.decide_user_install (use_user_site, prefix_path = None, target_dir = None, root_path = None, isolated_mode = False)
Determine whether to do a user install based on the input options.
If use_user_site is False, no additional checks are done.
If use_user_site is True, it is checked for compatibility with other
options.
If use_user_site is None, the default behaviour depends on the environment,
which is provided by the other arguments.
References pip._internal.commands.install.site_packages_writable(), and pip._internal.utils.virtualenv.virtualenv_no_global().
get_check_binary_allowed()
def pip._internal.commands.install.get_check_binary_allowed (format_control)
References packaging.utils.canonicalize_name().
get_lib_location_guesses()
def pip._internal.commands.install.get_lib_location_guesses (user = False, home = None, root = None, isolated = False, prefix = None # type: Optional[str])
References pip._internal.locations.get_scheme().
reject_location_related_install_options()
def pip._internal.commands.install.reject_location_related_install_options (requirements, options)
If any location-changing --install-option arguments were passed for
requirements or on the command-line, then show a deprecation warning.
References pip._internal.utils.distutils_args.parse_distutils_args().
site_packages_writable()
def pip._internal.commands.install.site_packages_writable (root, isolated)
References py._builtin.all, pip._internal.commands.install.get_lib_location_guesses(), py._builtin.set, and pip._internal.utils.filesystem.test_writable_dir().
Variable Documentation
logger
pip._internal.commands.install.logger = logging.getLogger(__name__)