Vaccine Dashboard: werkzeug.serving Namespace Reference
werkzeug.serving Namespace Reference
Classes
class _SslDummy
class ForkingMixIn
class DechunkedInput
class WSGIRequestHandler
class BaseWSGIServer
class ThreadedWSGIServer
class ForkingWSGIServer
Functions
t.Tuple["Certificate", "RSAPrivateKeyWithSerialization"] generate_adhoc_ssl_pair (t.Optional[str] cn=None)
t.Tuple[str, str] make_ssl_devcert (str base_path, t.Optional[str] host=None, t.Optional[str] cn=None)
"ssl.SSLContext" generate_adhoc_ssl_context ()
"ssl.SSLContext" load_ssl_context (str cert_file, t.Optional[str] pkey_file=None, t.Optional[int] protocol=None)
bool is_ssl_error (t.Optional[Exception] error=None)
socket.AddressFamily select_address_family (str host, int port)
t.Union[t.Tuple[str, int], str] get_sockaddr (str host, int port, socket.AddressFamily family)
str get_interface_ip (socket.AddressFamily family)
BaseWSGIServer make_server (str host, int port, "WSGIApplication" app, bool threaded=False, int processes=1, t.Optional[t.Type[WSGIRequestHandler]] request_handler=None, bool passthrough_errors=False, t.Optional[_TSSLContextArg] ssl_context=None, t.Optional[int] fd=None)
bool is_running_from_reloader ()
None run_simple (str hostname, int port, "WSGIApplication" application, bool use_reloader=False, bool use_debugger=False, bool use_evalex=True, t.Optional[t.Iterable[str]] extra_files=None, t.Optional[t.Iterable[str]] exclude_patterns=None, int reloader_interval=1, str reloader_type="auto", bool threaded=False, int processes=1, t.Optional[t.Type[WSGIRequestHandler]] request_handler=None, t.Optional[t.Dict[str, t.Union[str, t.Tuple[str, str]]]] static_files=None, bool passthrough_errors=False, t.Optional[_TSSLContextArg] ssl_context=None)
None run_with_reloader (*t.Any args, **t.Any kwargs)
None main ()
Variables
ssl
can_fork = hasattr(os, "fork")
ForkingMixIn = socketserver.ForkingMixIn
af_unix = None
int LISTEN_QUEUE = 128
string can_open_by_fd = "Windows" and hasattr(socket, "fromfd")
Detailed Description
A WSGI and HTTP server for use **during development only**. This
server is convenient to use, but is not designed to be particularly
stable, secure, or efficient. Use a dedicate WSGI server and HTTP
server when deploying to production.
It provides features like interactive debugging and code reloading. Use
``run_simple`` to start the server. Put this in a ``run.py`` script:
.. code-block:: python
    from myapp import create_app
    from werkzeug import run_simple
Function Documentation
generate_adhoc_ssl_context()
"ssl.SSLContext" werkzeug.serving.generate_adhoc_ssl_context ()
Generates an adhoc SSL context for the development server.
References werkzeug.serving.generate_adhoc_ssl_pair(), and werkzeug.serving.load_ssl_context().
generate_adhoc_ssl_pair()
t.Tuple["Certificate", "RSAPrivateKeyWithSerialization"] werkzeug.serving.generate_adhoc_ssl_pair (t.Optional[str] cn = None)
References cryptography.hazmat.backends.default_backend().
get_interface_ip()
str werkzeug.serving.get_interface_ip (socket.AddressFamily family)
Get the IP address of an external interface. Used when binding to
0.0.0.0 or ::1 to show a more useful URL.
:meta private:
get_sockaddr()
t.Union[t.Tuple[str, int], str] werkzeug.serving.get_sockaddr (str host, int port, socket.AddressFamily family)
Return a fully qualified socket address that can be passed to
:func:`socket.bind`.
is_running_from_reloader()
bool werkzeug.serving.is_running_from_reloader ()
Checks if the application is running from within the Werkzeug
reloader subprocess.
.. versionadded:: 0.10
is_ssl_error()
bool werkzeug.serving.is_ssl_error (t.Optional[Exception] error = None)
Checks if the given error (or the current one) is an SSL error.
load_ssl_context()
"ssl.SSLContext" werkzeug.serving.load_ssl_context (str cert_file, t.Optional[str] pkey_file = None, t.Optional[int] protocol = None)
Loads SSL context from cert/private key files and optional protocol.
Many parameters are directly taken from the API of
:py:class:`ssl.SSLContext`.
:param cert_file: Path of the certificate to use.
:param pkey_file: Path of the private key to use. If not given, the key
                  will be obtained from the certificate file.
:param protocol: A ``PROTOCOL`` constant from the :mod:`ssl` module.
    Defaults to :data:`ssl.PROTOCOL_TLS_SERVER`.
main()
None werkzeug.serving.main ()
A simple command-line interface for :py:func:`run_simple`.
References jinja2.utils.import_string(), and werkzeug.serving.run_simple().
make_server()
BaseWSGIServer werkzeug.serving.make_server (str host, int port, "WSGIApplication" app, bool threaded = False, int processes = 1, t.Optional[t.Type[WSGIRequestHandler]] request_handler = None, bool passthrough_errors = False, t.Optional[_TSSLContextArg] ssl_context = None, t.Optional[int] fd = None)
Create a new server instance that is either threaded, or forks
or just processes one request after another.
make_ssl_devcert()
t.Tuple[str, str] werkzeug.serving.make_ssl_devcert (str base_path, t.Optional[str] host = None, t.Optional[str] cn = None)
Creates an SSL key for development.  This should be used instead of
the ``'adhoc'`` key which generates a new cert on each server start.
It accepts a path for where it should store the key and cert and
either a host or CN.  If a host is given it will use the CN
``*.host/CN=host``.
For more information see :func:`run_simple`.
.. versionadded:: 0.9
:param base_path: the path to the certificate and key.  The extension
                  ``.crt`` is added for the certificate, ``.key`` is
                  added for the key.
:param host: the name of the host.  This can be used as an alternative
             for the `cn`.
:param cn: the `CN` to use.
References werkzeug.serving.generate_adhoc_ssl_pair(), and pip._vendor.distlib._backport.tarfile.open.
run_simple()
None werkzeug.serving.run_simple (str hostname, int port, "WSGIApplication" application, bool use_reloader = False, bool use_debugger = False, bool use_evalex = True, t.Optional[t.Iterable[str]] extra_files = None, t.Optional[t.Iterable[str]] exclude_patterns = None, int reloader_interval = 1, str reloader_type = "auto", bool threaded = False, int processes = 1, t.Optional[t.Type[WSGIRequestHandler]] request_handler = None, t.Optional[t.Dict[str, t.Union[str, t.Tuple[str, str]]]] static_files = None, bool passthrough_errors = False, t.Optional[_TSSLContextArg] ssl_context = None)
Start a WSGI application. Optional features include a reloader,
multithreading and fork support.
This function has a command-line interface too::
    python -m werkzeug.serving --help
.. versionchanged:: 2.0
    Added ``exclude_patterns`` parameter.
.. versionadded:: 0.5
   `static_files` was added to simplify serving of static files as well
   as `passthrough_errors`.
.. versionadded:: 0.6
   support for SSL was added.
.. versionadded:: 0.8
   Added support for automatically loading a SSL context from certificate
   file and private key.
.. versionadded:: 0.9
   Added command-line interface.
.. versionadded:: 0.10
   Improved the reloader and added support for changing the backend
   through the `reloader_type` parameter.  See :ref:`reloader`
   for more information.
.. versionchanged:: 0.15
    Bind to a Unix socket by passing a path that starts with
    ``unix://`` as the ``hostname``.
:param hostname: The host to bind to, for example ``'localhost'``.
    If the value is a path that starts with ``unix://`` it will bind
    to a Unix socket instead of a TCP socket..
:param port: The port for the server.  eg: ``8080``
:param application: the WSGI application to execute
:param use_reloader: should the server automatically restart the python
                     process if modules were changed?
:param use_debugger: should the werkzeug debugging system be used?
:param use_evalex: should the exception evaluation feature be enabled?
:param extra_files: a list of files the reloader should watch
                    additionally to the modules.  For example configuration
                    files.
:param exclude_patterns: List of :mod:`fnmatch` patterns to ignore
    when running the reloader. For example, ignore cache files that
    shouldn't reload when updated.
:param reloader_interval: the interval for the reloader in seconds.
:param reloader_type: the type of reloader to use.  The default is
                      auto detection.  Valid values are ``'stat'`` and
                      ``'watchdog'``. See :ref:`reloader` for more
                      information.
:param threaded: should the process handle each request in a separate
                 thread?
:param processes: if greater than 1 then handle each request in a new process
                  up to this maximum number of concurrent processes.
:param request_handler: optional parameter that can be used to replace
                        the default one.  You can use this to replace it
                        with a different
                        :class:`~BaseHTTPServer.BaseHTTPRequestHandler`
                        subclass.
:param static_files: a list or dict of paths for static files.  This works
                     exactly like :class:`SharedDataMiddleware`, it's actually
                     just wrapping the application in that middleware before
                     serving.
:param passthrough_errors: set this to `True` to disable the error catching.
                           This means that the server will die on errors but
                           it can be useful to hook debuggers in (pdb etc.)
:param ssl_context: an SSL context for the connection. Either an
                    :class:`ssl.SSLContext`, a tuple in the form
                    ``(cert_file, pkey_file)``, the string ``'adhoc'`` if
                    the server should automatically create one, or ``None``
                    to disable SSL (which is the default).
References werkzeug.serving.get_interface_ip(), werkzeug.serving.get_sockaddr(), werkzeug.serving.is_running_from_reloader(), werkzeug.serving.make_server(), werkzeug.serving.select_address_family(), and pip._vendor.requests.compat.str.
run_with_reloader()
None werkzeug.serving.run_with_reloader (*t.Any args, **t.Any kwargs)
Run a process with the reloader. This is not a public API, do
not use this function.
.. deprecated:: 2.0
    Will be removed in Werkzeug 2.1.
select_address_family()
socket.AddressFamily werkzeug.serving.select_address_family (str host, int port)
Return ``AF_INET4``, ``AF_INET6``, or ``AF_UNIX`` depending on
the host and port.
Variable Documentation
af_unix
werkzeug.serving.af_unix = None
can_fork
werkzeug.serving.can_fork = hasattr(os, "fork")
can_open_by_fd
string werkzeug.serving.can_open_by_fd = "Windows" and hasattr(socket, "fromfd")
ForkingMixIn
werkzeug.serving.ForkingMixIn = socketserver.ForkingMixIn
LISTEN_QUEUE
int werkzeug.serving.LISTEN_QUEUE = 128
ssl
werkzeug.serving.ssl