Vaccine Dashboard: py._vendored_packages.apipkg Namespace Reference
py._vendored_packages.apipkg Namespace Reference
Namespaces
version
Classes
class ApiModule
Functions
def distribution_version (name)
def initpkg (pkgname, exportdefs, attr=None, eager=False)
def importobj (modpath, attrname)
def AliasModule (modname, modpath, attrname=None)
Detailed Description
apipkg: control the exported namespace of a Python package.
see https://pypi.python.org/pypi/apipkg
(c) holger krekel, 2009 - MIT license
Function Documentation
AliasModule()
def py._vendored_packages.apipkg.AliasModule (modname, modpath, attrname = None)
References py._vendored_packages.apipkg.importobj(), and pip._vendor.requests.compat.str.
distribution_version()
def py._vendored_packages.apipkg.distribution_version (name)
try to get the version of the named distribution,
returs None on failure
References pkg_resources.get_distribution().
importobj()
def py._vendored_packages.apipkg.importobj (modpath, attrname)
imports a module, then resolves the attrname on it
initpkg()
def py._vendored_packages.apipkg.initpkg (pkgname, exportdefs, attr = None, eager = False)
 initialize given package from the export definitions.
References dotenv.cli.list().