Vaccine Dashboard: _pytest.pathlib Namespace Reference
_pytest.pathlib Namespace Reference
Classes
class ImportMode
class ImportPathMismatchError
Functions
_AnyPurePath get_lock_path (_AnyPurePath path)
bool on_rm_rf_error (func, str path, exc, *Path start_path)
Path ensure_extended_length_path (Path path)
str get_extended_length_path_str (str path)
None rm_rf (Path path)
Iterator[Path] find_prefixed (Path root, str prefix)
Iterator[str] extract_suffixes (Iterable[PurePath] iter, str prefix)
Iterator[str] find_suffixes (Path root, str prefix)
int parse_num (maybe_num)
Path make_numbered_dir (Path root, str prefix, int mode=0o700)
Path create_cleanup_lock (Path p)
def register_cleanup_lock_removal (Path lock_path, register=atexit.register)
None maybe_delete_a_numbered_dir (Path path)
bool ensure_deletable (Path path, float consider_lock_dead_if_created_before)
None try_cleanup (Path path, float consider_lock_dead_if_created_before)
Iterator[Path] cleanup_candidates (Path root, str prefix, int keep)
None cleanup_numbered_dir (Path root, str prefix, int keep, float consider_lock_dead_if_created_before)
Path make_numbered_dir_with_cleanup (Path root, str prefix, int keep, float lock_timeout, int mode)
Path resolve_from_str (str input, Path rootpath)
bool fnmatch_ex (str pattern, path)
Set[str] parts (str s)
def symlink_or_skip (src, dst, **kwargs)
ModuleType import_path (Union[str, py.path.local, Path] p, *Union[str, ImportMode] mode=ImportMode.prepend)
Optional[Path] resolve_package_path (Path path)
Iterator["os.DirEntry[str]"] visit (str path, Callable[["os.DirEntry[str]"], bool] recurse)
Path absolutepath (Union[Path, str] path)
Optional[Path] commonpath (Path path1, Path path2)
str bestrelpath (Path directory, Path dest)
Variables
int LOCK_TIMEOUT = 60 * 60 * 24 * 3
Function Documentation
absolutepath()
Path _pytest.pathlib.absolutepath (Union[Path, str] path)
Convert a path to an absolute path using os.path.abspath.
Prefer this over Path.resolve() (see #6523).
Prefer this over Path.absolute() (not public, doesn't normalize).
References pip._vendor.requests.compat.str.
bestrelpath()
str _pytest.pathlib.bestrelpath (Path directory, Path dest)
Return a string which is a relative path from directory to dest such
that directory/bestrelpath == dest.
The paths must be either both absolute or both relative.
If no such path can be determined, returns dest.
References _pytest.pathlib.commonpath(), and pip._vendor.requests.compat.str.
cleanup_candidates()
Iterator[Path] _pytest.pathlib.cleanup_candidates (Path root, str prefix, int keep)
List candidates for numbered directories to be removed - follows py.path.
References _pytest.pathlib.extract_suffixes(), _pytest.pathlib.find_prefixed(), and _pytest.pathlib.find_suffixes().
cleanup_numbered_dir()
None _pytest.pathlib.cleanup_numbered_dir (Path root, str prefix, int keep, float consider_lock_dead_if_created_before)
Cleanup for lock driven numbered directories.
References _pytest.pathlib.cleanup_candidates(), and _pytest.pathlib.try_cleanup().
commonpath()
Optional[Path] _pytest.pathlib.commonpath (Path path1, Path path2)
Return the common part shared with the other path, or None if there is
no common part.
If one path is relative and one is absolute, returns None.
References pip._vendor.requests.compat.str.
create_cleanup_lock()
Path _pytest.pathlib.create_cleanup_lock (Path p)
Create a lock to prevent premature folder cleanup.
References jwt.api_jws.encode, _pytest.pathlib.get_lock_path(), and pip._vendor.requests.compat.str.
ensure_deletable()
bool _pytest.pathlib.ensure_deletable (Path path, float consider_lock_dead_if_created_before)
Check if `path` is deletable based on whether the lock file is expired.
References _pytest.pathlib.get_lock_path().
ensure_extended_length_path()
Path _pytest.pathlib.ensure_extended_length_path (Path path)
Get the extended-length version of a path (Windows).
On Windows, by default, the maximum length of a path (MAX_PATH) is 260
characters, and operations on paths longer than that fail. But it is possible
to overcome this by converting the path to "extended-length" form before
performing the operation:
https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#maximum-path-length-limitation
On Windows, this function returns the extended-length absolute version of path.
On other platforms it returns path unchanged.
References _pytest.pathlib.get_extended_length_path_str(), and pip._vendor.requests.compat.str.
extract_suffixes()
Iterator[str] _pytest.pathlib.extract_suffixes (Iterable[PurePath] iter, str prefix)
Return the parts of the paths following the prefix.
:param iter: Iterator over path names.
:param prefix: Expected prefix of the path names.
find_prefixed()
Iterator[Path] _pytest.pathlib.find_prefixed (Path root, str prefix)
Find all elements in root that begin with the prefix, case insensitive.
find_suffixes()
Iterator[str] _pytest.pathlib.find_suffixes (Path root, str prefix)
Combine find_prefixes and extract_suffixes.
References _pytest.pathlib.extract_suffixes(), and _pytest.pathlib.find_prefixed().
fnmatch_ex()
bool _pytest.pathlib.fnmatch_ex (str pattern, path)
A port of FNMatcher from py.path.common which works with PurePath() instances.
The difference between this algorithm and PurePath.match() is that the
latter matches "**" glob expressions for each part of the path, while
this algorithm uses the whole path instead.
For example:
    "tests/foo/bar/doc/test_foo.py" matches pattern "tests/**/doc/test*.py"
    with this algorithm, but not with PurePath.match().
This algorithm was ported to keep backward-compatibility with existing
settings which assume paths match according this logic.
References:
* https://bugs.python.org/issue29249
* https://bugs.python.org/issue34731
References pip._vendor.requests.compat.str.
get_extended_length_path_str()
str _pytest.pathlib.get_extended_length_path_str (str path)
Convert a path to a Windows extended length path.
get_lock_path()
_AnyPurePath _pytest.pathlib.get_lock_path (_AnyPurePath path)
import_path()
ModuleType _pytest.pathlib.import_path (Union[str, py.path.local, Path] p, *Union[str, ImportMode] mode = ImportMode.prepend)
Import and return a module from the given path, which can be a file (a module) or
a directory (a package).
The import mechanism used is controlled by the `mode` parameter:
* `mode == ImportMode.prepend`: the directory containing the module (or package, taking
  `__init__.py` files into account) will be put at the *start* of `sys.path` before
  being imported with `__import__.
* `mode == ImportMode.append`: same as `prepend`, but the directory will be appended
  to the end of `sys.path`, if not already in `sys.path`.
* `mode == ImportMode.importlib`: uses more fine control mechanisms provided by `importlib`
  to import the module, which avoids having to use `__import__` and muck with `sys.path`
  at all. It effectively allows having same-named test modules in different places.
:raises ImportPathMismatchError:
    If after importing the given `path` and the module `__file__`
    are different. Only raised in `prepend` and `append` modes.
make_numbered_dir()
Path _pytest.pathlib.make_numbered_dir (Path root, str prefix, int mode = 0o700)
Create a directory with an increased number as suffix for the given prefix.
References _pytest.pathlib.find_suffixes(), and pip._vendor.pyparsing.range.
make_numbered_dir_with_cleanup()
Path _pytest.pathlib.make_numbered_dir_with_cleanup (Path root, str prefix, int keep, float lock_timeout, int mode)
Create a numbered dir with a cleanup lock and remove old ones.
References _pytest.pathlib.create_cleanup_lock(), _pytest.pathlib.make_numbered_dir(), pip._vendor.pyparsing.range, and _pytest.pathlib.register_cleanup_lock_removal().
maybe_delete_a_numbered_dir()
None _pytest.pathlib.maybe_delete_a_numbered_dir (Path path)
Remove a numbered directory if its lock can be obtained and it does
not seem to be in use.
References _pytest.pathlib.create_cleanup_lock(), _pytest.pathlib.ensure_extended_length_path(), and _pytest.pathlib.rm_rf().
on_rm_rf_error()
bool _pytest.pathlib.on_rm_rf_error (func, str path, exc, *Path start_path)
Handle known read-only errors during rmtree.
The returned value is used only by our own tests.
References pip._vendor.requests.compat.str.
parse_num()
int _pytest.pathlib.parse_num (maybe_num)
Parse number path suffixes, returns -1 on error.
parts()
Set[str] _pytest.pathlib.parts (str s)
References pip._vendor.pyparsing.range.
register_cleanup_lock_removal()
def _pytest.pathlib.register_cleanup_lock_removal (Path lock_path, register = atexit.register)
Register a cleanup function for removing a lock, by default on atexit.
resolve_from_str()
Path _pytest.pathlib.resolve_from_str (str input, Path rootpath)
resolve_package_path()
Optional[Path] _pytest.pathlib.resolve_package_path (Path path)
Return the Python package path by looking for the last
directory upwards which still contains an __init__.py.
Returns None if it can not be determined.
rm_rf()
None _pytest.pathlib.rm_rf (Path path)
Remove the path contents recursively, even if some elements
are read-only.
References _pytest.pathlib.ensure_extended_length_path(), and pip._vendor.requests.compat.str.
symlink_or_skip()
def _pytest.pathlib.symlink_or_skip (src, dst, ** kwargs)
Make a symlink, or skip the test in case symlinks are not supported.
References _pytest.outcomes.skip(), and pip._vendor.requests.compat.str.
try_cleanup()
None _pytest.pathlib.try_cleanup (Path path, float consider_lock_dead_if_created_before)
Try to cleanup a folder if we can ensure it's deletable.
References _pytest.pathlib.ensure_deletable(), and _pytest.pathlib.maybe_delete_a_numbered_dir().
visit()
Iterator["os.DirEntry[str]"] _pytest.pathlib.visit (str path, Callable[["os.DirEntry[str]"], bool] recurse)
Walk a directory recursively, in breadth-first order.
Entries at each directory level are sorted.
Variable Documentation
LOCK_TIMEOUT
int _pytest.pathlib.LOCK_TIMEOUT = 60 * 60 * 24 * 3