Vaccine Dashboard: api Namespace Reference
api Namespace Reference
Namespaces
settings
Functions
def create_app ()
def decode (params)
def getVaccineData ()
def createUser ()
def login ()
def getCard ()
Variables
app = flask.Flask(__name__)
cors = CORS(app)
mysql = MySQL()
conn = mysql.connect()
cursor = conn.cursor()
Function Documentation
create_app()
def api.create_app ()
References createUser(), decode(), getCard(), getVaccineData(), login(), and flask.helpers.send_file().
createUser()
def api.createUser ()
decode()
def api.decode (params)
getCard()
def api.getCard ()
References decode(), and flask.helpers.send_file().
getVaccineData()
def api.getVaccineData ()
login()
def api.login ()
Variable Documentation
app
api.app = flask.Flask(__name__)
conn
api.conn = mysql.connect()
cors
api.cors = CORS(app)
cursor
api.cursor = conn.cursor()
mysql
api.mysql = MySQL()