Vaccine Dashboard: _pytest.fixtures Namespace Reference
_pytest.fixtures Namespace Reference
Classes
class PseudoFixtureDef
class FuncFixtureInfo
class FixtureRequest
class SubRequest
class FixtureLookupError
class FixtureLookupErrorRepr
class FixtureDef
class FixtureFunctionMarker
class FixtureManager
Functions
None pytest_sessionstart ("Session" session)
def get_scope_package (node, "FixtureDef[object]" fixturedef)
Optional[Union[nodes.Item, nodes.Collector]] get_scope_node (nodes.Node node, "_Scope" scope)
None add_funcarg_pseudo_fixture_def (nodes.Collector collector, "Metafunc" metafunc, "FixtureManager" fixturemanager)
Optional["FixtureFunctionMarker"] getfixturemarker (object obj)
Iterator[_Key] get_parametrized_fixture_keys (nodes.Item item, int scopenum)
List[nodes.Item] reorder_items (Sequence[nodes.Item] items)
None fix_cache_order (nodes.Item item, Dict[int, Dict[nodes.Item, Dict[_Key, None]]] argkeys_cache, Dict[int, Dict[_Key, "Deque[nodes.Item]"]] items_by_argkey)
Dict[nodes.Item, None] reorder_items_atscope (Dict[nodes.Item, None] items, Dict[int, Dict[nodes.Item, Dict[_Key, None]]] argkeys_cache, Dict[int, Dict[_Key, "Deque[nodes.Item]"]] items_by_argkey, int scopenum)
None fillfixtures ("Function" function)
def get_direct_param_fixture_func (request)
bool scopemismatch ("_Scope" currentscope, "_Scope" newscope)
int scope2index (str scope, str descr, Optional[str] where=None)
"NoReturn" fail_fixturefunc (fixturefunc, str msg)
_FixtureValue call_fixture_func ("_FixtureFunc[_FixtureValue]" fixturefunc, FixtureRequest request, kwargs)
"_FixtureFunc[_FixtureValue]" resolve_fixture_function (FixtureDef[_FixtureValue] fixturedef, FixtureRequest request)
_FixtureValue pytest_fixture_setup (FixtureDef[_FixtureValue] fixturedef, SubRequest request)
_FixtureFunction wrap_function_to_error_out_if_called_directly (_FixtureFunction function, "FixtureFunctionMarker" fixture_marker)
_FixtureFunction fixture (_FixtureFunction fixture_function, *"Union[_Scope, Callable[[str, Config], _Scope]]" scope=..., Optional[Iterable[object]] params=..., bool autouse=..., Optional[Union[Iterable[Union[None, str, float, int, bool]], Callable[[Any], Optional[object]],]] ids=..., Optional[str] name=...)
FixtureFunctionMarker fixture (None fixture_function=..., *"Union[_Scope, Callable[[str, Config], _Scope]]" scope=..., Optional[Iterable[object]] params=..., bool autouse=..., Optional[Union[Iterable[Union[None, str, float, int, bool]], Callable[[Any], Optional[object]],]] ids=..., Optional[str] name=None)
Union[FixtureFunctionMarker, _FixtureFunction] fixture (Optional[_FixtureFunction] fixture_function=None, *"Union[_Scope, Callable[[str, Config], _Scope]]" scope="function", Optional[Iterable[object]] params=None, bool autouse=False, Optional[Union[Iterable[Union[None, str, float, int, bool]], Callable[[Any], Optional[object]],]] ids=None, Optional[str] name=None)
def yield_fixture (fixture_function=None, *args, scope="function", params=None, autouse=False, ids=None, name=None)
Config pytestconfig (FixtureRequest request)
None pytest_addoption (Parser parser)
Variables
name2pseudofixturedef_key = StoreKey[Dict[str, "FixtureDef[Any]"]]()
scopenum_function = scopes.index("function")
Function Documentation
add_funcarg_pseudo_fixture_def()
None _pytest.fixtures.add_funcarg_pseudo_fixture_def (nodes.Collector collector, "Metafunc" metafunc, "FixtureManager" fixturemanager)
References _pytest.fixtures.get_scope_node().
call_fixture_func()
_FixtureValue _pytest.fixtures.call_fixture_func ("_FixtureFunc[_FixtureValue]" fixturefunc, FixtureRequest request, kwargs)
References pip._vendor.packaging._typing.cast(), _pytest.outcomes.fail(), _pytest.fixtures.fail_fixturefunc(), _pytest.compat.is_generator(), and pip._vendor.six.next.
fail_fixturefunc()
"NoReturn" _pytest.fixtures.fail_fixturefunc (fixturefunc, str msg)
References _pytest.outcomes.fail(), _pytest._code.code.getfslineno(), and pip._vendor.requests.compat.str.
fillfixtures()
None _pytest.fixtures.fillfixtures ("Function" function)
Fill missing fixtures for a test function (deprecated).
fix_cache_order()
None _pytest.fixtures.fix_cache_order (nodes.Item item, Dict[int, Dict[nodes.Item, Dict[_Key, None]]] argkeys_cache, Dict[int, Dict[_Key, "Deque[nodes.Item]"]] items_by_argkey)
References dotenv.cli.get(), and pip._vendor.pyparsing.range.
fixture() [1/3]
_FixtureFunction _pytest.fixtures.fixture (_FixtureFunction fixture_function, *"Union[_Scope, Callable[[str, Config], _Scope]]" scope = ..., Optional[Iterable[object]] params = ..., bool autouse = ..., Optional[ Union[ Iterable[Union[None, str, float, int, bool]], Callable[[Any], Optional[object]], ] ] ids = ..., Optional[str] name = ...)
fixture() [2/3]
FixtureFunctionMarker _pytest.fixtures.fixture (None fixture_function = ..., *"Union[_Scope, Callable[[str, Config], _Scope]]" scope = ..., Optional[Iterable[object]] params = ..., bool autouse = ..., Optional[ Union[ Iterable[Union[None, str, float, int, bool]], Callable[[Any], Optional[object]], ] ] ids = ..., Optional[str] name = None)
References _pytest.fixtures.fixture().
fixture() [3/3]
Union[FixtureFunctionMarker, _FixtureFunction] _pytest.fixtures.fixture (Optional[_FixtureFunction] fixture_function = None, *"Union[_Scope, Callable[[str, Config], _Scope]]" scope = "function", Optional[Iterable[object]] params = None, bool autouse = False, Optional[ Union[ Iterable[Union[None, str, float, int, bool]], Callable[[Any], Optional[object]], ] ] ids = None, Optional[str] name = None)
Decorator to mark a fixture factory function.
This decorator can be used, with or without parameters, to define a
fixture function.
The name of the fixture function can later be referenced to cause its
invocation ahead of running tests: test modules or classes can use the
``pytest.mark.usefixtures(fixturename)`` marker.
Test functions can directly use fixture names as input arguments in which
case the fixture instance returned from the fixture function will be
injected.
Fixtures can provide their values to test functions using ``return`` or
``yield`` statements. When using ``yield`` the code block after the
``yield`` statement is executed as teardown code regardless of the test
outcome, and must yield exactly once.
:param scope:
    The scope for which this fixture is shared; one of ``"function"``
    (default), ``"class"``, ``"module"``, ``"package"`` or ``"session"``.
    This parameter may also be a callable which receives ``(fixture_name, config)``
    as parameters, and must return a ``str`` with one of the values mentioned above.
    See :ref:`dynamic scope` in the docs for more information.
:param params:
    An optional list of parameters which will cause multiple invocations
    of the fixture function and all of the tests using it. The current
    parameter is available in ``request.param``.
:param autouse:
    If True, the fixture func is activated for all tests that can see it.
    If False (the default), an explicit reference is needed to activate
    the fixture.
:param ids:
    List of string ids each corresponding to the params so that they are
    part of the test id. If no ids are provided they will be generated
    automatically from the params.
:param name:
    The name of the fixture. This defaults to the name of the decorated
    function. If a fixture is used in the same module in which it is
    defined, the function name of the fixture will be shadowed by the
    function arg that requests the fixture; one way to resolve this is to
    name the decorated function ``fixture_<fixturename>`` and then use
    ``@pytest.fixture(name='<fixturename>')``.
References _pytest.fixtures.fixture().
get_direct_param_fixture_func()
def _pytest.fixtures.get_direct_param_fixture_func (request)
get_parametrized_fixture_keys()
Iterator[_Key] _pytest.fixtures.get_parametrized_fixture_keys (nodes.Item item, int scopenum)
Return list of keys for all parametrized arguments which match
the specified scope.
References py._builtin.sorted.
get_scope_node()
Optional[Union[nodes.Item, nodes.Collector]] _pytest.fixtures.get_scope_node (nodes.Node node, "_Scope" scope)
References _pytest.compat.assert_never().
get_scope_package()
def _pytest.fixtures.get_scope_package (node, "FixtureDef[object]" fixturedef)
References dotenv.cli.type.
getfixturemarker()
Optional["FixtureFunctionMarker"] _pytest.fixtures.getfixturemarker (object obj)
Return fixturemarker or None if it doesn't exist or raised
exceptions.
pytest_addoption()
None _pytest.fixtures.pytest_addoption (Parser parser)
pytest_fixture_setup()
_FixtureValue _pytest.fixtures.pytest_fixture_setup (FixtureDef[_FixtureValue] fixturedef, SubRequest request)
Execution of fixture setup.
References _pytest.fixtures.call_fixture_func(), cffi.api.callable, and _pytest.fixtures.resolve_fixture_function().
pytest_sessionstart()
None _pytest.fixtures.pytest_sessionstart ("Session" session)
pytestconfig()
Config _pytest.fixtures.pytestconfig (FixtureRequest request)
Session-scoped fixture that returns the :class:`_pytest.config.Config` object.
Example::
    def test_foo(pytestconfig):
        if pytestconfig.getoption("verbose") > 0:
            ...
reorder_items()
List[nodes.Item] _pytest.fixtures.reorder_items (Sequence[nodes.Item] items)
References pip._vendor.requests.append, _pytest.fixtures.get_parametrized_fixture_keys(), dotenv.cli.list(), pip._vendor.pyparsing.range, and _pytest.fixtures.reorder_items_atscope().
reorder_items_atscope()
Dict[nodes.Item, None] _pytest.fixtures.reorder_items_atscope (Dict[nodes.Item, None] items, Dict[int, Dict[nodes.Item, Dict[_Key, None]]] argkeys_cache, Dict[int, Dict[_Key, "Deque[nodes.Item]"]] items_by_argkey, int scopenum)
References _pytest.fixtures.fix_cache_order(), py._builtin.reversed, and py._builtin.set.
resolve_fixture_function()
"_FixtureFunc[_FixtureValue]" _pytest.fixtures.resolve_fixture_function (FixtureDef[_FixtureValue] fixturedef, FixtureRequest request)
Get the actual callable that can be called to obtain the fixture
value, dealing with unittest-specific instances and bound methods.
References _pytest.compat.getimfunc().
scope2index()
int _pytest.fixtures.scope2index (str scope, str descr, Optional[str] where = None)
Look up the index of ``scope`` and raise a descriptive value error
if not defined.
References _pytest.outcomes.fail().
scopemismatch()
bool _pytest.fixtures.scopemismatch ("_Scope" currentscope, "_Scope" newscope)
wrap_function_to_error_out_if_called_directly()
_FixtureFunction _pytest.fixtures.wrap_function_to_error_out_if_called_directly (_FixtureFunction function, "FixtureFunctionMarker" fixture_marker)
Wrap the given fixture function so we can raise an error about it being called directly,
instead of used as an argument in a test function.
References pip._vendor.packaging._typing.cast(), and _pytest.outcomes.fail().
yield_fixture()
def _pytest.fixtures.yield_fixture (fixture_function = None, * args, scope = "function", params = None, autouse = False, ids = None, name = None)
(Return a) decorator to mark a yield-fixture factory function.
.. deprecated:: 3.0
    Use :py:func:`pytest.fixture` directly instead.
References _pytest.fixtures.fixture().
Variable Documentation
name2pseudofixturedef_key
_pytest.fixtures.name2pseudofixturedef_key = StoreKey[Dict[str, "FixtureDef[Any]"]]()
scopenum_function
_pytest.fixtures.scopenum_function = scopes.index("function")